//tealium universal tag - utag.100 ut4.0.202509232002, Copyright 2025 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.encode=function(a,b){b="";try{b=encodeURIComponent(a)}catch(e){utag.DB(e);}if(b==""){b=escape(a);}return b}
u.ev={"view":1};u.scriptrequested=false;u.rp=function(a,b){if(typeof a!=="undefined"&&a.indexOf("@@")>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return u.encode(b[d]);}else{return"";}});}
return a;};u.map={"_sm_100_1":"attribute.id","sales_chat_data_nosidewall":"attribute.data-nosidewall","sales_chat_data_deferee":"attribute.defer","sales_chat_data_noproactive":"attribute.data-proactive"};u.extend=[function(a,b){try{b['_sm_100_1']="oracle_chat";}catch(e){utag.DB(e);}},function(a,b){try{if(1){try{var salesContactNumber="+1.800.633.0738";var contactsGlobalLink="/corporate/contact/global.html";var callSalesTxt="Call Sales";if(utag_data!=undefined){salesContactNumber=utag_data['sales_contact_number'];if(location.pathname.startsWith('/hr')){salesContactNumber="0800 223 005";}
var siteIdValue=utag_data['meta.siteid'];contactsGlobalLink="/"+siteIdValue+"/corporate/contact/global.html";if(utag_data['meta.siteid']=='us'){contactsGlobalLink="/corporate/contact/global.html";callSalesTxt="Call US Sales";}}
if(location.hostname=="blogs-stage.oracle.com"||location.hostname=="blogs.oracle.com"){contactsGlobalLink="//www.oracle.com/corporate/contact/global.html";if(location.pathname.indexOf('/oracle-latinoamerica/')!=-1){callSalesTxt="Call Sales";contactsGlobalLink="//www.oracle.com/lad/corporate/contact/";}else if(location.pathname.indexOf('/oracle-brasil/')!=-1){callSalesTxt="Call Sales";contactsGlobalLink="//www.oracle.com/br/corporate/contact/";}}
if(utag_data!=undefined&&utag_data['page_region']=="emea"){salesContactNumber="";}
var chatHTML="<ocom-chatbot sales-txt='Talk to sales' chat-txt='Chat now' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Complete list of <a href="+contactsGlobalLink+">local country numbers' proactive='5'></ocom-chatbot>"
if(utag_data!==undefined&&utag_data['is_mobile']){chatHTML="<ocom-chatbot sales-txt='Talk to sales' chat-txt='Chat now' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Complete list of <a href="+contactsGlobalLink+">local country numbers' proactive='-1'></ocom-chatbot>"}
if(utag_data['meta.language']=='es'){callSalesTxt="Llama a ventas";chatHTML="<ocom-chatbot sales-txt='Ponte en contacto con ventas' chat-txt='Chatea ahora' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Lista completa de <a href="+contactsGlobalLink+">números locales por país' proactive='5'></ocom-chatbot>"
if(utag_data!==undefined&&utag_data['is_mobile']){chatHTML="<ocom-chatbot sales-txt='Ponte en contacto con ventas' chat-txt='Chatea ahora' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Lista completa de <a href="+contactsGlobalLink+">números locales por país' proactive='-1'></ocom-chatbot>"}}
if(utag_data['meta.language']=='pt'){callSalesTxt="Ligue para um especialista de vendas";chatHTML="<ocom-chatbot sales-txt='Fale com um especialista de vendas' chat-txt='Converse com a gente' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Lista completa de <a href="+contactsGlobalLink+">números locais dos países' proactive='5'></ocom-chatbot>"
if(utag_data!==undefined&&utag_data['is_mobile']){chatHTML="<ocom-chatbot sales-txt='Fale com um especialista de vendas' chat-txt='Converse com a gente' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Lista completa de <a href="+contactsGlobalLink+">números locais dos países' proactive='-1'></ocom-chatbot>"}}
if(utag_data['meta.language']=='fr'){callSalesTxt="Appeler l&#039équipe commerciale";chatHTML="<ocom-chatbot sales-txt='Contacter l&#039équipe commerciale' chat-txt='Discuter maintenant' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Liste complète des <a href="+contactsGlobalLink+">numéros de téléphone par pays' proactive='5'></ocom-chatbot>"
if(utag_data!==undefined&&utag_data['is_mobile']){chatHTML="<ocom-chatbot sales-txt='Contacter l&#039équipe commerciale' chat-txt='Discuter maintenant' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Liste complète des <a href="+contactsGlobalLink+">numéros de téléphone par pays' proactive='-1'></ocom-chatbot>"}}
if(utag_data['meta.language']=='de'){callSalesTxt="Vertrieb anrufen";chatHTML="<ocom-chatbot sales-txt='Mit dem Vertrieb sprechen' chat-txt='Jetzt chatten' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Vollständige Liste der <a href="+contactsGlobalLink+">lokalen Ländernummern' proactive='5'></ocom-chatbot>"
if(utag_data!==undefined&&utag_data['is_mobile']){chatHTML="<ocom-chatbot sales-txt='Mit dem Vertrieb sprechen' chat-txt='Jetzt chatten' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Vollständige Liste der <a href="+contactsGlobalLink+">lokalen Ländernummern' proactive='-1'></ocom-chatbot>"}}
if(utag_data['meta.language']=='it'){callSalesTxt="Chiama il team vendite";chatHTML="<ocom-chatbot sales-txt='Parla con il nostro team vendite' chat-txt='Avvia una chat' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Elenco completo dei <a href="+contactsGlobalLink+">numeri nazionali locali' proactive='5'></ocom-chatbot>"
if(utag_data!==undefined&&utag_data['is_mobile']){chatHTML="<ocom-chatbot sales-txt='Parla con il nostro team vendite' chat-txt='Avvia una chat' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Elenco completo dei <a href="+contactsGlobalLink+">numeri nazionali locali' proactive='-1'></ocom-chatbot>"}}
if(utag_data['meta.language']=='nl'){callSalesTxt="Verkoop bellen";chatHTML="<ocom-chatbot sales-txt='Met Verkoop spreken' chat-txt='Nu chatten' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Volledige lijst met <a href="+contactsGlobalLink+">lokale landnummers' proactive='5'></ocom-chatbot>"
if(utag_data!==undefined&&utag_data['is_mobile']){chatHTML="<ocom-chatbot sales-txt='Met Verkoop spreken' chat-txt='Nu chatten' close-txt='Close contact' number-txt='"+callSalesTxt+"'number='"+salesContactNumber+"'number-list='Volledige lijst met <a href="+contactsGlobalLink+">lokale landnummers' proactive='-1'></ocom-chatbot>"}}
document.getElementsByTagName("body")[0].insertAdjacentHTML('beforeend',chatHTML);}catch(e){console.log(e);}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&"||"&","kvp_delim":"="||"=","qs_delim":"?"||"?","tag_type":"script","base_url":"//www.oracle.com/asset/web/js/ocom-chatbot.js","secure_base_url":"","static_params":"","cachebust":"disabled","cachevar":""||"_rnd","requestscriptonce":"enabled","attribute":{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:100:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("attribute.")===0){if(e[f].indexOf("attribute.data")===0&&b[d]=="empty-string"){b[d]=b[d].replace("empty-string","");}
u.data.attribute[e[f].split(".")[1]]=b[d];}else if(!u.data.hasOwnProperty(e[f])){c.push(e[f]+"##kvp_delim##"+u.encode(b[d]));}
u.data[e[f]]=b[d];}}}
if(!u.data.base_url){if(!u.data.secure_base_url){utag.DB("Error: No Base URL or Secure HTTPS Override Provided.");return;}else{u.data.base_url=u.data.secure_base_url;utag.DB("No Base URL provided, using Secure HTTPS Override.");}}
u.data.secure_base_url=u.data.secure_base_url||u.data.base_url;u.data.url=(location.protocol==="https:"?u.data.secure_base_url:u.data.base_url);if(u.data.url.indexOf("http")!==0&&u.data.url.indexOf("/")!==0){u.data.url=location.protocol+"//"+u.data.url;}
if(u.data.static_params){c.push(u.data.static_params);}
var cb_check=new RegExp("(\\"+u.data.qs_delim+"|"+u.data.qsp_delim+")"+u.data.cachevar+"=");if(u.data.cachebust==="enabled"&&!cb_check.test(u.data.url)){c.push([u.data.cachevar,Math.random()].join(u.data.kvp_delim));}
if(c.length>0){if(u.data.url.indexOf(u.data.qs_delim)<0){u.data.url+=u.data.qs_delim;}else if(u.data.url.indexOf(u.data.qs_delim)!==(u.data.url.length-1)){u.data.url+=u.data.qsp_delim;}}
u.data.url=u.rp(u.data.url,b)+u.rp(c.join(u.data.qsp_delim),b);u.data.url=u.data.url.replace(/##kvp_delim##/g,u.data.kvp_delim);u.callback=u.callback||function(){};if(u.data.requestscriptonce==="enabled"&&u.data.tag_type==="script"){if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_100","cb":u.callback,"attrs":u.data.attribute});}else{u.callback();}}else{u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_100","cb":u.callback,"attrs":u.data.attribute});}
utag.DB("send:100:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("100","oracle.main"));}catch(error){utag.DB(error);}
