/** Safety Control Tower - Mis Autoevaluaciones */
document.addEventListener("DOMContentLoaded", function(){
 const container=document.querySelector(".container[data-csrf-token]"); if(!container)return; const csrfToken=container.dataset.csrfToken||""; const $=id=>document.getElementById(id);
 const i18nEl=$("mySelfI18n");let I18N={};try{I18N=i18nEl?JSON.parse(i18nEl.textContent||"{}"):{};}catch(_){ } const S=(k,f)=>I18N[k]||f||k;
 const pageLanguageSelect=$("pageLanguageSelect"),mySelfStatus=$("mySelfStatus"),mySelfList=$("mySelfList"),executePanel=$("executePanel"),executeTitle=$("executeTitle"),executeDescription=$("executeDescription"),executeAlert=$("executeAlert"),executeQuestions=$("executeQuestions"),executeSubmitBtn=$("executeSubmitBtn"),executeCloseBtn=$("executeCloseBtn");let currentAssignmentId=null;
 function escapeHtml(v){const e=document.createElement("div");e.textContent=v==null?"":String(v);return e.innerHTML;}function showAlert(el,msg,variant){if(!el)return;el.textContent=msg||"";el.classList.remove("d-none","alert-success","alert-danger","alert-info","alert-warning");el.classList.add("alert-"+(variant||"danger"));}function hideAlert(el){if(el)el.classList.add("d-none");}async function api(url,opt){try{const r=await fetch(url,opt||{});return await r.json();}catch(_){return{success:false,message:S("self_error_response","Respuesta inválida del servidor.")};}}function postJson(url,data){return api(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.assign({csrf_token:csrfToken},data||{}))});}function fmt(t,v){let o=t||"";Object.keys(v||{}).forEach(k=>{o=o.replaceAll("{"+k+"}",String(v[k]));});return o;}
 // El cambio de idioma (confirmación + guardado en perfil) lo maneja js/lang-switcher.js.
 async function loadAssignments(){mySelfStatus.classList.remove("d-none","alert-danger");mySelfStatus.classList.add("alert-info");mySelfStatus.textContent=S("my_self_loading","Cargando tus autoevaluaciones...");mySelfList.classList.add("d-none");const r=await api("./mis-asignaciones.php");if(!r.success){mySelfStatus.classList.remove("alert-info");mySelfStatus.classList.add("alert-danger");mySelfStatus.textContent=r.message||S("self_error_response");return;}const items=r.data||[];if(!items.length){mySelfStatus.textContent=S("my_self_empty","No tienes autoevaluaciones asignadas por el momento.");return;}mySelfStatus.classList.add("d-none");mySelfList.classList.remove("d-none");renderAssignments(items);}
 function renderAssignments(items){mySelfList.innerHTML="";items.forEach(a=>{const state=parseInt(a.state,10),used=parseInt(a.intentos_usados||0,10),remaining=Math.max(0,parseInt(a.attempts_allowed||0,10)-used),card=document.createElement("div");let cls="pending",status=S("my_self_pending","Pendiente");if(state===2){cls="approved";status=S("my_self_approved","Aprobada");}else if(state===3){cls="failed";status=S("my_self_failed","Reprobada");}else if(used>0){cls="in-progress";status=S("my_self_in_progress","En curso");}card.className="self-card "+cls;let action="";if(state===1)action=remaining>0?'<button type="button" class="btn btn-primary-custom btn-sm" data-action="execute">'+escapeHtml(S("my_self_execute","Realizar autoevaluación"))+"</button>":'<span class="text-muted">'+escapeHtml(S("my_self_no_attempts","Sin intentos disponibles"))+"</span>";const score=a.porcentaje_ultimo!=null?'<div class="result-score mt-2">'+escapeHtml(S("self_result","Resultado"))+': '+escapeHtml(a.porcentaje_ultimo)+"%</div>":"";card.innerHTML='<div class="d-flex justify-content-between gap-3 flex-wrap"><div class="flex-grow-1"><h3 class="h6 mb-1">'+escapeHtml(a.test_name)+'</h3><p class="text-muted mb-1" style="font-size:.9rem">'+escapeHtml(a.test_description)+'</p><strong>'+escapeHtml(status)+'</strong> · <span class="text-muted" style="font-size:.84rem">'+escapeHtml(S("my_self_due","Vence"))+' '+escapeHtml((a.deadline||"").substring(0,10))+'</span> · <span class="text-muted" style="font-size:.84rem">'+escapeHtml(S("self_attempts_used","Intentos usados"))+': '+escapeHtml(used)+'/'+escapeHtml(a.attempts_allowed||0)+"</span>"+score+"</div><div>"+action+"</div></div>";const b=card.querySelector('[data-action="execute"]');if(b)b.addEventListener("click",()=>openExecution(a.id_user_test_assigned));mySelfList.appendChild(card);});}
 async function openExecution(id){currentAssignmentId=parseInt(id,10);hideAlert(executeAlert);executeQuestions.innerHTML='<p class="text-muted">...</p>';executePanel.classList.remove("d-none");executePanel.scrollIntoView({behavior:"smooth"});const r=await api("./rendir-detalle.php?id_asignacion="+encodeURIComponent(currentAssignmentId));if(!r.success){showAlert(executeAlert,r.message,"danger");executeQuestions.innerHTML="";return;}executeTitle.textContent=r.data.name;executeDescription.textContent=r.data.description||"";renderQuestions(r.data.preguntas||[]);}
 function renderQuestions(qs){executeQuestions.innerHTML="";qs.forEach((q,index)=>{const block=document.createElement("div");block.className="question-block";block.dataset.idRel=q.id_rel;block.dataset.idQuestion=q.id_question;let opts="";(q.opciones||[]).forEach((o,i)=>{const id="self_opt_"+q.id_rel+"_"+i;opts+='<div class="form-check"><input class="form-check-input" type="radio" name="self_question_'+q.id_rel+'" id="'+id+'" value="'+o.id_questions_options+'"><label class="form-check-label" for="'+id+'">'+escapeHtml(o.text_option)+"</label></div>";});block.innerHTML='<p><strong>'+(index+1)+'.</strong> '+escapeHtml(q.question)+"</p>"+opts;executeQuestions.appendChild(block);});}
 if(executeSubmitBtn)executeSubmitBtn.addEventListener("click",async()=>{hideAlert(executeAlert);const blocks=Array.from(executeQuestions.querySelectorAll(".question-block")),answers=[];for(const block of blocks){const selected=block.querySelector('input[type="radio"]:checked');if(!selected){showAlert(executeAlert,S("my_self_must_answer","Debes responder todas las preguntas antes de enviar."),"warning");return;}answers.push({id_rel:parseInt(block.dataset.idRel,10),id_question:parseInt(block.dataset.idQuestion,10),id_questions_options:parseInt(selected.value,10)});}executeSubmitBtn.disabled=true;const r=await postJson("./rendir-responder.php",{id_asignacion:currentAssignmentId,respuestas:answers});executeSubmitBtn.disabled=false;if(!r.success){showAlert(executeAlert,r.message,"danger");return;}if(r.data.finalizada){const template=r.data.cumple?S("my_self_completed_ok","Autoevaluación aprobada con {score}%."):S("my_self_completed_fail","Autoevaluación finalizada con {score}%, bajo el mínimo requerido.");showAlert(executeAlert,fmt(template,{score:r.data.porcentaje}),r.data.cumple?"success":"warning");}else{const remaining=r.data.attempts_allowed-r.data.intentos_usados;showAlert(executeAlert,fmt(S("my_self_retry","Resultado actual: {score}%. Te quedan {remaining} intento(s)."),{score:r.data.porcentaje,remaining:remaining}),"warning");}setTimeout(()=>{executePanel.classList.add("d-none");loadAssignments();},2200);});
 if(executeCloseBtn)executeCloseBtn.addEventListener("click",()=>executePanel.classList.add("d-none"));loadAssignments();
});
