/** Safety Control Tower - Mis Protocolos */
document.addEventListener('DOMContentLoaded', function () {
    const root = document.querySelector('.container[data-csrf-token]'); if (!root) return;
    const $ = id => document.getElementById(id);
    let I18N={}; try { I18N=JSON.parse(($('myProtocolsI18n')||{}).textContent||'{}'); } catch(_) {}
    const S=(k,f)=>I18N[k]||f||k;
    const status=$('myProtocolsStatus'), list=$('myProtocolsList'), alert=$('myProtocolsAlert'), language=$('pageLanguageSelect');

    function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML;}
    function fmtDate(v){return v?String(v).replace('T',' ').substring(0,16):'—';}
    function show(el,msg,variant){if(!el)return;el.textContent=msg||'';el.classList.remove('d-none','alert-success','alert-danger','alert-info','alert-warning');el.classList.add('alert-'+(variant||'danger'));}
    async function api(url){try{const r=await fetch(url);return await r.json();}catch(_){return{success:false,message:S('protocols_error_response','Respuesta inválida del servidor.')}}}
    function resultLabel(r){const map={pendiente_revision:'protocols_result_pending_review',conforme:'protocols_result_conforme',observado:'protocols_result_observado',no_conforme:'protocols_result_no_conforme',no_aplica:'protocols_result_no_aplica'};return S(map[r]||'',r||'—');}
    function stateLabel(s){const map={activa:'protocols_state_active',suspendida:'protocols_state_suspended',cerrada:'protocols_state_closed',cancelada:'protocols_state_cancelled'};return S(map[s]||'',s||'—');}
    function resultClass(r){if(r==='conforme'||r==='no_aplica')return'ok';if(r==='observado'||r==='pendiente_revision')return'warn';if(r==='no_conforme')return'danger';return'';}
    function target(a){const parts=[];if(a.center_name)parts.push(a.center_name);if(a.project_name)parts.push(a.project_name);if(a.worker_name)parts.push((a.worker_name+' '+(a.worker_lastname||'')).trim());return parts.length?parts.join(' · '):S('protocols_company_wide','Empresa completa');}

    async function load(){status.classList.remove('d-none','alert-danger');status.classList.add('alert-info');status.textContent=S('protocols_my_loading','Cargando tus protocolos...');list.classList.add('d-none');const r=await api('./mis-asignaciones.php');if(!r.success){status.classList.remove('alert-info');status.classList.add('alert-danger');status.textContent=r.message;return;}const rows=r.data||[];if(!rows.length){status.textContent=S('protocols_my_empty','No tienes protocolos asignados por el momento.');return;}status.classList.add('d-none');list.classList.remove('d-none');render(rows);}

    function render(rows){list.innerHTML='';rows.forEach(a=>{const pending=a.latest_result==='pendiente_revision', overdue=parseInt(a.is_overdue||0,10)===1, active=a.state==='activa'&&parseInt(a.protocol_state||0,10)===1;const card=document.createElement('article');card.className='protocol-card '+(pending?'pending-review':(overdue?'overdue':(active?'active':'')));let action='';if(active&&!pending)action='<a class="btn btn-primary-custom btn-sm" href="./ejecutar-protocolo.php?id_assignment='+encodeURIComponent(a.id_protocol_assignment)+'">'+esc(S('protocols_execute','Ejecutar protocolo'))+'</a>';else if(pending)action='<span class="pill warn">'+esc(S('protocols_pending_review','Existe una ejecución pendiente de revisión.'))+'</span>';let source=a.source_url?'<a class="small" target="_blank" rel="noopener noreferrer" href="'+esc(a.source_url)+'"><i class="bi bi-box-arrow-up-right"></i> '+esc(S('protocols_source_official','Ver fuente oficial'))+'</a>':'';card.innerHTML='<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap"><div class="flex-grow-1"><div class="d-flex gap-2 flex-wrap align-items-center"><h2 class="h6 mb-0">'+esc(a.protocol_name)+'</h2><code>'+esc(a.code)+'</code></div><p class="text-muted small mt-2 mb-2">'+esc(a.protocol_description||'')+'</p><div class="meta-line"><span class="pill">'+esc(stateLabel(a.state))+'</span>'+(overdue?'<span class="pill danger">'+esc(S('protocols_overdue','Vencido'))+'</span>':'')+(a.latest_result?'<span class="pill '+resultClass(a.latest_result)+'">'+esc(resultLabel(a.latest_result))+'</span>':'')+'<span><i class="bi bi-calendar-event"></i> '+esc(fmtDate(a.next_due_at))+'</span><span><i class="bi bi-bullseye"></i> '+esc(target(a))+'</span></div><div class="mt-2">'+source+'</div></div><div class="d-flex gap-2 flex-wrap">'+action+'<button type="button" class="btn btn-outline-custom btn-sm" data-history>'+esc(S('protocols_history','Historial'))+' ('+esc(a.execution_count||0)+')</button></div></div><div class="history-panel" data-history-panel></div>';const btn=card.querySelector('[data-history]'),panel=card.querySelector('[data-history-panel]');btn.addEventListener('click',()=>toggleHistory(a,panel));list.appendChild(card);});}

    async function toggleHistory(a,panel){if(panel.classList.contains('active')){panel.classList.remove('active');return;}panel.classList.add('active');panel.innerHTML='<p class="text-muted small">...</p>';const r=await api('./mis-ejecuciones.php?id_protocol_assignment='+encodeURIComponent(a.id_protocol_assignment));if(!r.success){panel.innerHTML='<div class="alert alert-danger mb-0">'+esc(r.message)+'</div>';return;}const rows=r.data||[];if(!rows.length){panel.innerHTML='<p class="text-muted small mb-0">'+esc(S('protocols_history_empty','Aún no hay ejecuciones registradas.'))+'</p>';return;}panel.innerHTML='';rows.forEach(e=>{const item=document.createElement('div');item.className='execution-item';item.innerHTML='<div class="d-flex justify-content-between gap-2 flex-wrap"><div><strong>'+esc(S('protocols_cycle','Ciclo'))+' '+esc(e.cycle_number)+'</strong><div class="small text-muted">'+esc(S('protocols_submitted','Enviado'))+': '+esc(fmtDate(e.submitted_at))+(e.reviewed_at?' · '+esc(S('protocols_reviewed_at','Revisado'))+': '+esc(fmtDate(e.reviewed_at)):'')+'</div><span class="pill '+resultClass(e.result)+'">'+esc(resultLabel(e.result))+'</span></div><button type="button" class="btn btn-outline-custom btn-sm" data-detail>'+esc(S('protocols_view','Ver'))+'</button></div><div class="mt-2 d-none" data-detail-box></div>';item.querySelector('[data-detail]').addEventListener('click',()=>loadExecutionDetail(e.id_protocol_execution,item.querySelector('[data-detail-box]')));panel.appendChild(item);});}

    async function loadExecutionDetail(id,box){if(!box.classList.contains('d-none')){box.classList.add('d-none');return;}box.classList.remove('d-none');box.innerHTML='<span class="text-muted small">...</span>';const r=await api('./ejecucion-detalle.php?id_protocol_execution='+encodeURIComponent(id));if(!r.success){box.innerHTML='<div class="alert alert-danger mb-0">'+esc(r.message)+'</div>';return;}let html='';(r.data.submissions||[]).forEach(s=>{html+='<div class="mt-2"><strong>'+esc(s.form_name)+'</strong>';const answers=s.detalle&&s.detalle.respuestas?s.detalle.respuestas:[];answers.forEach(a=>{let value=a.display_value;if(Array.isArray(value))value=value.join(', ');if(a.file_path)value='<a href="../formularios/archivo-descargar.php?id_answer='+encodeURIComponent(a.id_answer)+'"><i class="bi bi-download"></i> '+esc(a.original_name||'Archivo')+'</a>';else value=esc(value==null||value===''?'—':value);html+='<div class="small border-bottom py-1"><b>'+esc(a.label)+':</b> '+value+'</div>';});html+='</div>';});if(r.data.review_notes)html+='<div class="small mt-2"><b>Obs.:</b> '+esc(r.data.review_notes)+'</div>';box.innerHTML=html||'—';}

    // El cambio de idioma (confirmación + guardado en perfil) lo maneja js/lang-switcher.js.
    load();
});
