<?php
require_once __DIR__.'/common.php';
require_once __DIR__.'/../../i18n.php';
require_once __DIR__ . '/../../partials/info-tip.php';
requireCapabilityPage($pdo, 'dynamic_forms.view', '../../acceso-denegado.php');
aplicarCabecerasSeguridad();
$embeddedActivityMode = isset($_GET['embedded']) && (string) $_GET['embedded'] === '1';
if ($embeddedActivityMode) {
    // El HUB Mi espacio sólo puede embeber actividades desde el mismo origen.
    header('X-Frame-Options: SAMEORIGIN');
}
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$csrf=htmlspecialchars((string)$_SESSION['csrf_token'],ENT_QUOTES,'UTF-8');
$userEmail=htmlspecialchars((string)($_SESSION['user_email']??''),ENT_QUOTES,'UTF-8');
$directActivityMode=filter_input(INPUT_GET,'start',FILTER_VALIDATE_INT)>0;
$jsKeys=['forms_error_response','my_forms_loading','my_forms_empty','my_forms_complete','my_forms_history_empty','my_forms_submitted','my_forms_open','my_forms_required','my_forms_submit','my_forms_cancel','forms_scope_global','forms_company_badge','forms_global_badge','forms_submission_answers','forms_file_download','forms_submission_date','forms_field_required','forms_migration_required','activities_fields_label','activity_save_draft','activity_exit','activity_draft_saved','activity_draft_restored','activity_complete_before_submit','activity_file_not_saved','activity_confirm_submit','forms_filter_all','forms_filter_global','forms_filter_company','forms_filter_label','forms_filter_empty'];
$jsStrings=[];foreach($jsKeys as $k)$jsStrings[$k]=t($k);
?>
<!DOCTYPE html><html lang="<?= htmlspecialchars(idiomaActual(),ENT_QUOTES,'UTF-8') ?>"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title><?= htmlspecialchars(t('my_forms_page_title'),ENT_QUOTES,'UTF-8') ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"><link rel="stylesheet" href="../../css/style.css?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>&ux=20260920-p32-v51">
<link rel="stylesheet" href="../../css/sct-main-sections.css?v=20260923-p79">
<style>.welcome-hero{padding:3rem 0 1.5rem}.welcome-topbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1.25rem 0;border-bottom:1px solid rgba(0,0,0,.08)}.welcome-topbar .brand-symbol img{height:32px}.topbar-actions{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;justify-content:flex-end}.welcome-greeting-icon{font-size:2.4rem;color:var(--primary);margin-bottom:.6rem}.quick-links{margin:1.5rem 0 3rem}.language-select{min-width:120px}.form-card{margin:0;min-width:0}.scope-badge{font-size:.74rem;padding:.25rem .55rem;border-radius:999px;background:rgba(0,123,197,.12);color:var(--primary-dark);font-weight:700}.scope-badge.global{background:rgba(116,66,153,.1);color:#744299}.dynamic-field{border-bottom:1px solid var(--border);padding-bottom:1rem;margin-bottom:1rem}.dynamic-field:last-child{border-bottom:0}.history-row{border:1px solid var(--border);border-radius:var(--radius-md);padding:.85rem 1rem;margin-bottom:.65rem}.answer-line{border-bottom:1px solid var(--border);padding:.75rem 0}.answer-line:last-child{border-bottom:0}.answer-label{font-weight:700}.answer-value{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:575.98px){.welcome-topbar{align-items:flex-start}.topbar-actions{max-width:72%}}</style></head><body class="sct-module-page<?= $directActivityMode?' sct-activity-mode':'' ?><?= $embeddedActivityMode ? ' sct-embedded-activity' : '' ?>">
<div class="container sct-main-shell sct-personal-module-shell" data-csrf-token="<?= $csrf ?>" data-activity-user="<?= htmlspecialchars(hash('sha256', (string) ($_SESSION['user_email'] ?? '')), ENT_QUOTES, 'UTF-8') ?>"><?php
        $sctNavbarBasePath = '../../';
        $sctNavbarBackHref = '../usuarios/gestiones.php';
        if (!$embeddedActivityMode) { require __DIR__ . '/../../partials/app-navbar.php'; }
        ?>

        <section class="welcome-hero sct-main-hero sct-personal-section-hero"><div class="sct-main-hero__copy"><span class="section-label sct-main-pill"><i class="bi bi-card-text" aria-hidden="true"></i><?= htmlspecialchars(t('mgmt_filter_personal'),ENT_QUOTES,'UTF-8') ?></span><h1 class="section-title sct-main-title mb-0"><?= htmlspecialchars(t('my_forms_title'),ENT_QUOTES,'UTF-8') ?></h1><p class="sct-page-intro sct-main-intro"><?= htmlspecialchars(t('my_forms_intro') . ' ' . ($_SESSION['user_email'] ?? ''), ENT_QUOTES, 'UTF-8') ?></p></div></section>
<?php $sctModuleMode = 'personal'; require __DIR__ . '/../../partials/module-context.php'; ?>
<?php $sctPersonalNavActive = 'forms'; $sctPersonalNavBasePath = '../'; require __DIR__ . '/../../partials/personal-activity-nav.php'; ?>
<section class="quick-links"><div id="myFormsAlert" class="alert d-none" role="alert"></div><div id="myFormsScopeFilter" class="sct-personal-status-filter sct-personal-scope-filter" role="group" aria-label="<?= htmlspecialchars(t('forms_filter_label'),ENT_QUOTES,'UTF-8') ?>"></div><div class="feature-card mb-4" data-forms-section="available"><h2 class="h5 mb-3"><?= htmlspecialchars(t('my_forms_available_title'),ENT_QUOTES,'UTF-8') ?></h2><div id="availableStatus" class="alert alert-info mb-0"><?= htmlspecialchars(t('my_forms_loading'),ENT_QUOTES,'UTF-8') ?></div><div id="availableList" class="d-none"></div></div>
<div class="feature-card mb-4" data-forms-section="history"><h2 class="h5 mb-3"><?= htmlspecialchars(t('my_forms_history_title'),ENT_QUOTES,'UTF-8') ?></h2><div id="historyList"></div></div>
<div id="fillPanel" class="feature-card mb-4 d-none"><div class="d-flex justify-content-between gap-3 align-items-start"><div><span class="section-label"><?= htmlspecialchars(t('my_forms_complete'),ENT_QUOTES,'UTF-8') ?></span><h2 id="fillTitle" class="h5 mb-0">-</h2></div><?php if (!$embeddedActivityMode): ?><button id="fillClose" class="btn btn-outline-custom btn-sm" type="button"><i class="bi bi-box-arrow-left"></i> <?= htmlspecialchars(t('activity_exit'),ENT_QUOTES,'UTF-8') ?></button><?php endif; ?></div><p id="fillDescription" class="text-muted mt-2"></p><div id="fillAlert" class="alert d-none" role="alert"></div><form id="fillForm" enctype="multipart/form-data"><div id="fillFields"></div><div class="sct-activity-actions mt-3"><button id="fillSave" class="btn btn-outline-custom" type="button"><i class="bi bi-save"></i> <?= htmlspecialchars(t('activity_save_draft'),ENT_QUOTES,'UTF-8') ?></button><button id="fillSubmit" class="btn btn-primary-custom" type="submit"><i class="bi bi-send"></i> <?= htmlspecialchars(t('my_forms_submit'),ENT_QUOTES,'UTF-8') ?></button></div></form></div>
<div id="historyDetail" class="feature-card d-none"><div class="d-flex justify-content-between gap-3"><h2 class="h5"><?= htmlspecialchars(t('forms_submission_answers'),ENT_QUOTES,'UTF-8') ?></h2><button id="historyDetailClose" class="btn btn-outline-custom btn-sm" type="button"><?= htmlspecialchars(t('my_forms_cancel'),ENT_QUOTES,'UTF-8') ?></button></div><div id="historyAnswers"></div></div></section></div>
<script id="myFormsI18n" type="application/json"><?= json_encode($jsStrings,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script><script src="../../js/sct-activity-session.js?v=20260920-p24-v48"></script><script src="../../js/formularios-mis.js?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>-p34-v52"></script><script src="../../js/lang-switcher.js?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"></script>
    <?php if (!$embeddedActivityMode) { require __DIR__ . '/../../partials/app-footer.php'; } ?>

<script src="../../js/sct-module-ui.js?v=20260920-p43"></script>
</body></html>
