(function(){
'use strict';
var modalEl=document.querySelector('[data-health-modal]');if(!modalEl)return;
var form=document.getElementById('workerHealthForm');if(!form)return;
var csrf=modalEl.getAttribute('data-csrf')||'';var forced=modalEl.getAttribute('data-forced')==='1';
var getUrl=modalEl.getAttribute('data-get-url');var saveUrl=modalEl.getAttribute('data-save-url');
var alertEl=modalEl.querySelector('[data-health-alert]');var steps=Array.prototype.slice.call(modalEl.querySelectorAll('[data-health-step]'));var idx=0;
var modal=null;
function getModal(){if(!modal&&window.bootstrap){modal=bootstrap.Modal.getOrCreateInstance(modalEl,{backdrop:forced?'static':true,keyboard:!forced});}return modal;}
function showAlert(msg,type){alertEl.className='alert mt-3 alert-'+(type||'danger');alertEl.textContent=msg||'';if(!msg)alertEl.classList.add('d-none');}
function showStep(n){idx=Math.max(0,Math.min(steps.length-1,n));steps.forEach(function(s,i){s.classList.toggle('d-none',i!==idx);});modalEl.querySelectorAll('[data-health-step-dot]').forEach(function(d,i){d.classList.toggle('is-active',i<=idx);d.classList.toggle('is-current',i===idx);});var pct=Math.round(((idx+1)/steps.length)*100);var bar=modalEl.querySelector('[data-health-progress]');if(bar)bar.style.width=pct+'%';var prog=modalEl.querySelector('.health-progress');if(prog)prog.setAttribute('aria-valuenow',String(pct));modalEl.querySelector('[data-health-prev]').classList.toggle('invisible',idx===0);modalEl.querySelector('[data-health-next]').classList.toggle('d-none',idx===steps.length-1);modalEl.querySelector('[data-health-submit]').classList.toggle('d-none',idx!==steps.length-1);showAlert('');updateConditional();if(idx===steps.length-1)updateSummary();}
function valueOf(name){var checked=form.querySelector('input[name="'+name+'"]:checked');return checked?checked.value:'';}
function checkedValues(name){return Array.prototype.slice.call(form.querySelectorAll('input[name="'+name+'[]"]:checked')).map(function(x){return x.value;});}
function hasAllergy(){return checkedValues('allergies').some(function(v){return v!=='none'&&v!=='prefer_not';});}
function textForChecked(name){return Array.prototype.slice.call(form.querySelectorAll('input[name="'+name+'[]"]:checked')).map(function(x){var lab=x.closest('label');return lab?lab.textContent.trim():x.value;}).join(', ');}
function textForRadio(name){var x=form.querySelector('input[name="'+name+'"]:checked');if(!x)return '—';var lab=x.closest('label');return lab?lab.textContent.trim():x.value;}
function setSummary(key,value){var el=modalEl.querySelector('[data-health-summary="'+key+'"]');if(el)el.textContent=value||'—';}
function updateSummary(){setSummary('phone',form.phone.value.trim());setSummary('contact',[form.emergency_name_1.value.trim(),form.emergency_phone_1.value.trim()].filter(Boolean).join(' · '));setSummary('conditions',textForChecked('conditions'));setSummary('allergies',textForChecked('allergies'));setSummary('occupational',textForRadio('occupational_choice'));setSummary('restriction',textForRadio('restriction_choice'));}
function updateConditional(){modalEl.querySelectorAll('[data-show-if]').forEach(function(el){var rule=el.getAttribute('data-show-if');var show=false;if(rule==='has_allergy')show=hasAllergy();else{var parts=rule.split(':');var name=parts[0],wanted=parts[1];show=name==='conditions'||name==='allergies'||name==='occupational_diseases'?checkedValues(name).indexOf(wanted)>=0:valueOf(name)===wanted;}el.classList.toggle('d-none',!show);});}
function setupExclusive(group){var box=modalEl.querySelector('[data-exclusive-group="'+group+'"]');if(!box)return;box.addEventListener('change',function(ev){var input=ev.target;if(!input.matches('input[type=checkbox]'))return;var exclusive=input.value==='none'||input.value==='prefer_not';var all=box.querySelectorAll('input[type=checkbox]');if(input.checked&&exclusive){all.forEach(function(x){if(x!==input)x.checked=false;});}else if(input.checked){all.forEach(function(x){if(x.value==='none'||x.value==='prefer_not')x.checked=false;});}updateConditional();});}
setupExclusive('conditions');setupExclusive('allergies');form.addEventListener('change',updateConditional);
function isValidPhone(value){return /^\+?[0-9][0-9\s().-]{6,24}$/.test((value||'').trim());}
function markInvalid(el,isInvalid){if(!el)return;el.classList.toggle('is-invalid',!!isInvalid);}
function validateCurrent(){
 var step=steps[idx];var ok=true;
 Array.prototype.slice.call(step.querySelectorAll('[required]')).forEach(function(el){if(el.offsetParent===null)return;if(!el.checkValidity()){el.classList.add('is-invalid');ok=false;}else el.classList.remove('is-invalid');});
 if(idx===0){
  var phoneOk=isValidPhone(form.phone.value);markInvalid(form.phone,!phoneOk);if(!phoneOk)ok=false;
  var e1PhoneOk=isValidPhone(form.emergency_phone_1.value);markInvalid(form.emergency_phone_1,!e1PhoneOk);if(!e1PhoneOk)ok=false;
  var e2Name=form.emergency_name_2.value.trim(),e2Rel=form.emergency_relation_2.value,e2Phone=form.emergency_phone_2.value.trim();
  var e2Any=!!(e2Name||e2Rel||e2Phone);var e2Complete=!e2Any||(e2Name&&e2Rel&&isValidPhone(e2Phone));
  markInvalid(form.emergency_name_2,e2Any&&!e2Name);markInvalid(form.emergency_relation_2,e2Any&&!e2Rel);markInvalid(form.emergency_phone_2,e2Any&&!isValidPhone(e2Phone));if(!e2Complete)ok=false;
 }
 if(idx===1){if(!checkedValues('conditions').length||!valueOf('medication_choice')||!checkedValues('allergies').length)ok=false;if(checkedValues('conditions').indexOf('other')>=0&&!form.condition_other.value.trim())ok=false;if(valueOf('medication_choice')==='yes'&&!form.medications_text.value.trim())ok=false;if(hasAllergy()&&(!form.allergy_details.value.trim()||!valueOf('severe_reaction')))ok=false;}
 if(idx===2){if(!valueOf('occupational_choice'))ok=false;if(valueOf('occupational_choice')==='yes'&&!checkedValues('occupational_diseases').length)ok=false;if(checkedValues('occupational_diseases').indexOf('other')>=0&&!form.occupational_other.value.trim())ok=false;}
 if(idx===3){if(!valueOf('restriction_choice'))ok=false;if(valueOf('restriction_choice')==='yes'&&!form.restriction_details.value.trim())ok=false;}
 if(idx===4&&!form.accepted.checked)ok=false;if(!ok)showAlert((window.SCT_HEALTH_I18N||{}).required||'');return ok;
}
modalEl.querySelector('[data-health-prev]').addEventListener('click',function(){showStep(idx-1);});modalEl.querySelector('[data-health-next]').addEventListener('click',function(){if(validateCurrent())showStep(idx+1);});
function payload(){return {csrf_token:csrf,phone:form.phone.value.trim(),health_system:form.health_system.value,emergency_name_1:form.emergency_name_1.value.trim(),emergency_relation_1:form.emergency_relation_1.value,emergency_phone_1:form.emergency_phone_1.value.trim(),emergency_name_2:form.emergency_name_2.value.trim(),emergency_relation_2:form.emergency_relation_2.value,emergency_phone_2:form.emergency_phone_2.value.trim(),conditions:checkedValues('conditions'),condition_other:form.condition_other.value.trim(),medication_choice:valueOf('medication_choice'),medications_text:form.medications_text.value.trim(),medications_emergency:form.medications_emergency.value.trim(),allergies:checkedValues('allergies'),allergy_details:form.allergy_details.value.trim(),severe_reaction:valueOf('severe_reaction'),severe_reaction_info:form.severe_reaction_info.value.trim(),occupational_choice:valueOf('occupational_choice'),occupational_diseases:checkedValues('occupational_diseases'),occupational_other:form.occupational_other.value.trim(),restriction_choice:valueOf('restriction_choice'),restriction_details:form.restriction_details.value.trim(),accepted:form.accepted.checked?1:0};}
function post(url,data){return fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(data)}).then(function(r){return r.json().then(function(j){return {ok:r.ok,data:j};});});}
modalEl.querySelector('[data-health-submit]').addEventListener('click',function(){if(!validateCurrent())return;var btn=this;btn.disabled=true;post(saveUrl,payload()).then(function(r){if(!r.ok||!r.data.success)throw new Error((r.data&&r.data.message)||((window.SCT_HEALTH_I18N||{}).saveError||''));showAlert((r.data&&r.data.message)||((window.SCT_HEALTH_I18N||{}).saved||''),'success');setTimeout(function(){if(forced)window.location.href=window.location.pathname+'?health_completed=1';else{var m=getModal();if(m)m.hide();}},500);}).catch(function(e){showAlert(e.message||((window.SCT_HEALTH_I18N||{}).saveError||''));}).then(function(){btn.disabled=false;});});
function setValue(name,val){var el=form.elements[name];if(!el)return;if(el instanceof RadioNodeList){return;}el.value=val==null?'':String(val);}
function fill(data){if(!data)return;['phone','health_system','emergency_name_1','emergency_relation_1','emergency_phone_1','emergency_name_2','emergency_relation_2','emergency_phone_2','condition_other','medications_text','medications_emergency','allergy_details','severe_reaction_info','occupational_other','restriction_details'].forEach(function(k){if(typeof data[k]!=='undefined'&&form.elements[k])form.elements[k].value=data[k]||'';});['medication_choice','severe_reaction','occupational_choice','restriction_choice'].forEach(function(k){if(data[k]){var el=form.querySelector('input[name="'+k+'"][value="'+data[k]+'"]');if(el)el.checked=true;}});[['conditions','conditions'],['allergies','allergies'],['occupational_diseases','occupational_diseases']].forEach(function(pair){(data[pair[0]]||[]).forEach(function(v){var el=form.querySelector('input[name="'+pair[1]+'[]"][value="'+v+'"]');if(el)el.checked=true;});});updateConditional();}
function load(){showAlert('');return post(getUrl,{csrf_token:csrf}).then(function(r){if(!r.ok||!r.data.success)throw new Error((r.data&&r.data.message)||'');var d=r.data.data||{};if(d.profile)fill(d.profile);else if(d.phone&&form.phone)form.phone.value=d.phone;return d;}).catch(function(e){showAlert(e.message||((window.SCT_HEALTH_I18N||{}).saveError||''));return null;});}
modalEl.addEventListener('show.bs.modal',function(){showStep(0);load();});
document.querySelectorAll('[data-open-health-form]').forEach(function(btn){btn.addEventListener('click',function(){var m=getModal();if(m)m.show();});});
document.addEventListener('DOMContentLoaded',function(){showStep(0);if(forced){var m=getModal();if(m)m.show();}});
})();
