<?php
require_once __DIR__.'/common.php';
require_once __DIR__.'/../../i18n.php';
requireCapabilityPage($pdo, 'dynamic_forms.view', '../../acceso-denegado.php');
aplicarCabecerasSeguridad();
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$isGlobalAdmin=formularioIsGlobalAdmin($pdo);
$csrf=htmlspecialchars((string)$_SESSION['csrf_token'],ENT_QUOTES,'UTF-8');
$userEmail=htmlspecialchars((string)($_SESSION['user_email']??''),ENT_QUOTES,'UTF-8');
$jsKeys=[
'forms_loading','forms_empty','forms_select_company','forms_scope_global','forms_scope_company','forms_global_badge','forms_company_badge','forms_locked','forms_edit','forms_manage','forms_deactivate','forms_reactivate','forms_confirm_deactivate','forms_confirm_reactivate','forms_error_response','forms_error_load','forms_error_detail','forms_error_submissions','forms_form_new','forms_form_edit','forms_save','forms_update','forms_cancel_edit','forms_fields_empty','forms_field_new','forms_field_edit','forms_field_saved','forms_field_deleted','forms_confirm_field_delete','forms_options_help','forms_required_yes','forms_required_no','forms_submissions_empty','forms_submission_view','forms_submission_from','forms_submission_date','forms_submission_answers','forms_file_download','forms_readonly_global','forms_migration_required','common_active','common_inactive'
];
$jsStrings=[];foreach($jsKeys as $k)$jsStrings[$k]=t($k);
?>
<!DOCTYPE html>
<html lang="<?= htmlspecialchars(idiomaActual(),ENT_QUOTES,'UTF-8') ?>">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title><?= htmlspecialchars(t('forms_page_title'),ENT_QUOTES,'UTF-8') ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="../../css/style.css?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>">
<style>
.welcome-hero{padding:3rem 0 1.5rem}.welcome-topbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1.25rem 0;border-bottom:1px solid rgba(0,0,0,.08)}.welcome-topbar .brand-symbol img{height:32px}.topbar-actions{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;justify-content:flex-end}.welcome-greeting-icon{font-size:2.4rem;color:var(--primary);margin-bottom:.6rem}.quick-links{margin:1.5rem 0 3rem}.language-select{min-width:120px}.forms-detail{display:none}.forms-detail.active{display:block}.field-row{display:flex;gap:1rem;align-items:center;justify-content:space-between;border:1px solid var(--border);border-radius:var(--radius-md);padding:.8rem 1rem;margin-bottom:.65rem;background:var(--background-soft)}.field-row .meta{font-size:.8rem;color:var(--text-secondary)}.scope-badge{font-size:.74rem;padding:.25rem .55rem;border-radius:999px;background:rgba(0,163,244,.12);color:var(--primary-dark);font-weight:700}.scope-badge.global{background:rgba(124,58,237,.1);color:#7c3aed}.submission-row{border:1px solid var(--border);border-radius:var(--radius-md);padding:.9rem 1rem;margin-bottom:.65rem}.locked-note{border-left:4px solid #d97706}.answer-line{border-bottom:1px solid var(--border);padding:.75rem 0}.answer-line:last-child{border-bottom:0}.answer-label{font-weight:700}.answer-value{white-space:pre-wrap;overflow-wrap:anywhere}.form-field-grid{display:grid;grid-template-columns:1fr 170px 130px 110px auto;gap:.6rem;align-items:end}@media(max-width:991.98px){.form-field-grid{grid-template-columns:1fr 1fr}.form-field-grid .wide{grid-column:1/-1}}@media(max-width:575.98px){.form-field-grid{grid-template-columns:1fr}.welcome-topbar{align-items:flex-start}.topbar-actions{max-width:72%}}
</style>
</head>
<body>
<div class="container" data-csrf-token="<?= $csrf ?>" data-is-global-admin="<?= $isGlobalAdmin?'1':'0' ?>">
<div class="welcome-topbar"><div class="brand-wrapper"><div class="brand-symbol"><img src="../../images/logos/Logo-SCT-white.png" alt="Safety Control Tower"></div></div><div class="topbar-actions"><select id="pageLanguageSelect" class="form-select form-select-sm language-select" aria-label="<?= htmlspecialchars(t('common_language'),ENT_QUOTES,'UTF-8') ?>"><?php foreach(idiomasDisponiblesConNombre() as $code=>$name): ?><option value="<?= htmlspecialchars($code,ENT_QUOTES,'UTF-8') ?>" <?= $code===idiomaActual()?'selected':'' ?>><?= htmlspecialchars($name,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select><a href="../usuarios/gestiones.php" class="btn btn-outline-custom btn-sm"><?= htmlspecialchars(t('mgmt_back'),ENT_QUOTES,'UTF-8') ?> <i class="bi bi-arrow-left"></i></a><a href="../../logout.php" class="btn btn-outline-custom btn-sm"><?= htmlspecialchars(t('common_logout'),ENT_QUOTES,'UTF-8') ?> <i class="bi bi-box-arrow-right"></i></a></div></div>
<section class="welcome-hero text-center"><div class="welcome-greeting-icon"><i class="bi bi-card-checklist"></i></div><span class="section-label">SAFETY CONTROL TOWER</span><h1 class="section-title"><?= htmlspecialchars(t('forms_title'),ENT_QUOTES,'UTF-8') ?></h1><p class="section-description intro-description-centered"><?= htmlspecialchars(t('forms_intro'),ENT_QUOTES,'UTF-8') ?> <strong><?= $userEmail ?></strong>.</p></section>
<section class="quick-links">
<?php if($isGlobalAdmin): ?><div class="feature-card mb-4"><div class="row g-3 align-items-end"><div class="col-12 col-md-6"><label for="companySelect" class="form-label"><?= htmlspecialchars(t('forms_scope'),ENT_QUOTES,'UTF-8') ?></label><select id="companySelect" class="form-select"><option value="global"><?= htmlspecialchars(t('forms_scope_global'),ENT_QUOTES,'UTF-8') ?></option></select></div></div></div><?php endif; ?>
<div id="formsAlert" class="alert d-none mb-3" role="alert" aria-live="polite"></div>
<div class="feature-card mb-4"><h2 class="h5 mb-3" id="formEditorTitle"><?= htmlspecialchars(t('forms_form_new'),ENT_QUOTES,'UTF-8') ?></h2><form id="formEditor" novalidate><input type="hidden" id="formMode" value="create"><input type="hidden" id="formTarget" value=""><div class="row g-3"><div class="col-12 col-md-5"><label class="form-label" for="formName"><?= htmlspecialchars(t('forms_name'),ENT_QUOTES,'UTF-8') ?></label><input id="formName" class="form-control" maxlength="150" required></div><div class="col-12 col-md-7"><label class="form-label" for="formDescription"><?= htmlspecialchars(t('forms_description'),ENT_QUOTES,'UTF-8') ?></label><textarea id="formDescription" class="form-control" rows="2" maxlength="5000"></textarea></div></div><div class="d-flex gap-2 mt-3 flex-wrap"><button id="formSubmitBtn" class="btn btn-primary-custom btn-sm" type="submit"><?= htmlspecialchars(t('forms_save'),ENT_QUOTES,'UTF-8') ?></button><button id="formCancelEditBtn" class="btn btn-outline-custom btn-sm d-none" type="button"><?= htmlspecialchars(t('forms_cancel_edit'),ENT_QUOTES,'UTF-8') ?></button></div></form></div>
<div class="feature-card"><h2 class="h5 mb-3"><?= htmlspecialchars(t('forms_list_title'),ENT_QUOTES,'UTF-8') ?></h2><div id="formsStatus" class="alert alert-info mb-0" role="status"><?= htmlspecialchars(t('forms_loading'),ENT_QUOTES,'UTF-8') ?></div><div id="formsTableWrap" class="table-responsive mt-3 d-none"><table class="table table-hover align-middle mb-0"><thead><tr><th><?= htmlspecialchars(t('forms_name'),ENT_QUOTES,'UTF-8') ?></th><th><?= htmlspecialchars(t('forms_scope'),ENT_QUOTES,'UTF-8') ?></th><th><?= htmlspecialchars(t('forms_fields'),ENT_QUOTES,'UTF-8') ?></th><th><?= htmlspecialchars(t('forms_submissions'),ENT_QUOTES,'UTF-8') ?></th><th><?= htmlspecialchars(t('companies_col_state'),ENT_QUOTES,'UTF-8') ?></th><th><?= htmlspecialchars(t('companies_col_actions'),ENT_QUOTES,'UTF-8') ?></th></tr></thead><tbody id="formsTableBody"></tbody></table></div></div>
<div id="formsDetail" class="feature-card mt-4 forms-detail"><div class="d-flex justify-content-between gap-3 align-items-start"><div><span class="section-label"><?= htmlspecialchars(t('forms_detail_title'),ENT_QUOTES,'UTF-8') ?></span><h2 id="formsDetailName" class="h5 mb-0">-</h2></div><button type="button" id="formsDetailClose" class="btn btn-outline-custom btn-sm"><?= htmlspecialchars(t('self_close'),ENT_QUOTES,'UTF-8') ?></button></div><div id="detailAlert" class="alert d-none mt-3" role="alert"></div><div id="lockedNote" class="alert alert-warning locked-note d-none mt-3"><?= htmlspecialchars(t('forms_locked_help'),ENT_QUOTES,'UTF-8') ?></div>
<div class="mt-4"><h3 class="h6"><?= htmlspecialchars(t('forms_fields_title'),ENT_QUOTES,'UTF-8') ?></h3><div id="fieldsList" class="mb-3"></div><form id="fieldForm"><input type="hidden" id="fieldMode" value="create"><input type="hidden" id="fieldTarget" value=""><div class="form-field-grid"><div class="wide"><label class="form-label" for="fieldLabel"><?= htmlspecialchars(t('forms_field_label'),ENT_QUOTES,'UTF-8') ?></label><input id="fieldLabel" class="form-control" maxlength="150" required></div><div><label class="form-label" for="fieldType"><?= htmlspecialchars(t('forms_field_type'),ENT_QUOTES,'UTF-8') ?></label><select id="fieldType" class="form-select"><option value="text">text</option><option value="number">number</option><option value="date">date</option><option value="select">select</option><option value="checkbox">checkbox</option><option value="file">file</option></select></div><div><label class="form-label" for="fieldOrder"><?= htmlspecialchars(t('forms_field_order'),ENT_QUOTES,'UTF-8') ?></label><input id="fieldOrder" type="number" min="0" max="10000" value="0" class="form-control"></div><div class="form-check pb-2"><input id="fieldRequired" class="form-check-input" type="checkbox"><label class="form-check-label" for="fieldRequired"><?= htmlspecialchars(t('forms_field_required'),ENT_QUOTES,'UTF-8') ?></label></div><div><button id="fieldSubmitBtn" class="btn btn-primary-custom btn-sm w-100" type="submit"><?= htmlspecialchars(t('forms_field_new'),ENT_QUOTES,'UTF-8') ?></button></div><div class="wide"><label class="form-label" for="fieldOptions"><?= htmlspecialchars(t('forms_field_options'),ENT_QUOTES,'UTF-8') ?></label><input id="fieldOptions" class="form-control" placeholder="<?= htmlspecialchars(t('forms_options_help'),ENT_QUOTES,'UTF-8') ?>"></div><div class="wide"><button id="fieldCancelEdit" type="button" class="btn btn-outline-custom btn-sm d-none"><?= htmlspecialchars(t('forms_cancel_edit'),ENT_QUOTES,'UTF-8') ?></button></div></div></form></div>
<div class="mt-4 border-top pt-4"><h3 class="h6"><?= htmlspecialchars(t('forms_submissions_title'),ENT_QUOTES,'UTF-8') ?></h3><div id="submissionsList"></div></div>
<div id="submissionDetail" class="mt-4 border-top pt-4 d-none"><div class="d-flex justify-content-between gap-3"><h3 class="h6"><?= htmlspecialchars(t('forms_submission_answers'),ENT_QUOTES,'UTF-8') ?></h3><button id="submissionDetailClose" type="button" class="btn btn-outline-custom btn-sm"><?= htmlspecialchars(t('self_close'),ENT_QUOTES,'UTF-8') ?></button></div><div id="submissionAnswers" class="mt-2"></div></div>
</div>
</section></div>
<script id="formsI18n" type="application/json"><?= json_encode($jsStrings,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script><script src="../../js/formularios-admin.js?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"></script><script src="../../js/lang-switcher.js?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"></script>
</body></html>
