<?php
$healthFormForced = !empty($healthFormForced);
$healthBasePath = isset($healthBasePath) ? (string)$healthBasePath : './';
if (substr($healthBasePath,-1)!=='/') $healthBasePath .= '/';
if (empty($_SESSION['csrf_token'])) $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
$healthOptions = [
  'conditions'=>[
    'asthma'=>'health_condition_asthma','diabetes'=>'health_condition_diabetes','epilepsy'=>'health_condition_epilepsy','hypertension'=>'health_condition_hypertension','cardiac'=>'health_condition_cardiac','severe_allergy'=>'health_condition_severe_allergy','musculoskeletal'=>'health_condition_musculoskeletal','other'=>'health_condition_other','none'=>'health_none','prefer_not'=>'health_prefer_not'
  ],
  'allergies'=>['medicines'=>'health_allergy_medicines','food'=>'health_allergy_food','insects'=>'health_allergy_insects','latex'=>'health_allergy_latex','other'=>'health_allergy_other','none'=>'health_none','prefer_not'=>'health_prefer_not'],
  'diseases'=>['hearing'=>'health_occ_hearing','silicosis'=>'health_occ_silicosis','musculoskeletal'=>'health_occ_musculoskeletal','dermatitis'=>'health_occ_dermatitis','chemical'=>'health_occ_chemical','uv'=>'health_occ_uv','altitude'=>'health_occ_altitude','mental'=>'health_occ_mental','other'=>'health_occ_other']
];
?>
<div class="modal fade health-modal" id="workerHealthModal" tabindex="-1" aria-labelledby="workerHealthModalTitle" aria-hidden="true" data-health-modal data-forced="<?= $healthFormForced?'1':'0' ?>" data-get-url="<?= htmlspecialchars($healthBasePath.'api/salud/formulario-obtener.php',ENT_QUOTES,'UTF-8') ?>" data-save-url="<?= htmlspecialchars($healthBasePath.'api/salud/formulario-guardar.php',ENT_QUOTES,'UTF-8') ?>" data-csrf="<?= htmlspecialchars($_SESSION['csrf_token'],ENT_QUOTES,'UTF-8') ?>" <?= $healthFormForced?'data-bs-backdrop="static" data-bs-keyboard="false"':'' ?>>
  <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <div><div class="health-modal__eyebrow">Safety Control Tower</div><h2 class="modal-title h5" id="workerHealthModalTitle"><?= htmlspecialchars(t('health_modal_title'),ENT_QUOTES,'UTF-8') ?></h2></div>
        <?php if(!$healthFormForced): ?><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars(t('common_close_label'),ENT_QUOTES,'UTF-8') ?>"></button><?php endif; ?>
      </div>
      <div class="modal-body">
        <p class="health-modal__intro"><?= htmlspecialchars(t('health_intro'),ENT_QUOTES,'UTF-8') ?></p>
        <div class="health-stepper" aria-label="<?= htmlspecialchars(t('health_progress_label'),ENT_QUOTES,'UTF-8') ?>">
          <?php foreach([0=>'health_step_data',1=>'health_step_conditions',2=>'health_step_occupational',3=>'health_step_restrictions',4=>'health_step_declaration'] as $n=>$key): ?><span data-health-step-dot="<?= $n ?>"><b><?= $n+1 ?></b><small><?= htmlspecialchars(t($key),ENT_QUOTES,'UTF-8') ?></small></span><?php endforeach; ?>
        </div>
        <div class="progress health-progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="20"><div class="progress-bar" data-health-progress style="width:20%"></div></div>
        <div class="alert d-none mt-3" role="alert" data-health-alert></div>
        <form id="workerHealthForm" novalidate>
          <section class="health-step" data-health-step="0">
            <h3><?= htmlspecialchars(t('health_step_data'),ENT_QUOTES,'UTF-8') ?></h3>
            <div class="row g-3">
              <div class="col-12 col-md-6"><label class="form-label" for="healthPhone"><?= htmlspecialchars(t('health_mobile'),ENT_QUOTES,'UTF-8') ?></label><input class="form-control" id="healthPhone" name="phone" type="tel" maxlength="30" required autocomplete="tel"></div>
              <div class="col-12 col-md-6"><label class="form-label" for="healthSystem"><?= htmlspecialchars(t('health_system'),ENT_QUOTES,'UTF-8') ?></label><select class="form-select" id="healthSystem" name="health_system" required><option value=""></option><option value="fonasa"><?= htmlspecialchars(t('health_system_fonasa'),ENT_QUOTES,'UTF-8') ?></option><option value="isapre"><?= htmlspecialchars(t('health_system_isapre'),ENT_QUOTES,'UTF-8') ?></option><option value="other"><?= htmlspecialchars(t('health_system_other'),ENT_QUOTES,'UTF-8') ?></option><option value="prefer_not"><?= htmlspecialchars(t('health_prefer_not_indicate'),ENT_QUOTES,'UTF-8') ?></option></select></div>
            </div>
            <div class="health-subcard"><h4><?= htmlspecialchars(t('health_emergency_primary'),ENT_QUOTES,'UTF-8') ?></h4><div class="row g-3"><div class="col-12 col-md-5"><label class="form-label"><?= htmlspecialchars(t('health_full_name'),ENT_QUOTES,'UTF-8') ?></label><input class="form-control" name="emergency_name_1" maxlength="150" required></div><div class="col-12 col-md-3"><label class="form-label"><?= htmlspecialchars(t('health_relation'),ENT_QUOTES,'UTF-8') ?></label><select class="form-select" name="emergency_relation_1" required><option value=""></option><?php foreach(['partner'=>'health_relation_partner','parent'=>'health_relation_parent','child'=>'health_relation_child','sibling'=>'health_relation_sibling','family'=>'health_relation_family','friend'=>'health_relation_friend','other'=>'health_relation_other'] as $v=>$k): ?><option value="<?= $v ?>"><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-12 col-md-4"><label class="form-label"><?= htmlspecialchars(t('health_contact_phone'),ENT_QUOTES,'UTF-8') ?></label><input class="form-control" name="emergency_phone_1" type="tel" maxlength="30" required></div></div></div>
            <div class="health-subcard"><h4><?= htmlspecialchars(t('health_emergency_secondary'),ENT_QUOTES,'UTF-8') ?></h4><div class="row g-3"><div class="col-12 col-md-5"><label class="form-label"><?= htmlspecialchars(t('health_full_name'),ENT_QUOTES,'UTF-8') ?></label><input class="form-control" name="emergency_name_2" maxlength="150"></div><div class="col-12 col-md-3"><label class="form-label"><?= htmlspecialchars(t('health_relation'),ENT_QUOTES,'UTF-8') ?></label><select class="form-select" name="emergency_relation_2"><option value=""></option><?php foreach(['partner'=>'health_relation_partner','parent'=>'health_relation_parent','child'=>'health_relation_child','sibling'=>'health_relation_sibling','family'=>'health_relation_family','friend'=>'health_relation_friend','other'=>'health_relation_other'] as $v=>$k): ?><option value="<?= $v ?>"><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-12 col-md-4"><label class="form-label"><?= htmlspecialchars(t('health_contact_phone'),ENT_QUOTES,'UTF-8') ?></label><input class="form-control" name="emergency_phone_2" type="tel" maxlength="30"></div></div></div>
          </section>

          <section class="health-step d-none" data-health-step="1">
            <h3><?= htmlspecialchars(t('health_step_conditions'),ENT_QUOTES,'UTF-8') ?></h3>
            <fieldset class="health-fieldset" data-exclusive-group="conditions"><legend><?= htmlspecialchars(t('health_conditions'),ENT_QUOTES,'UTF-8') ?></legend><div class="health-check-grid"><?php foreach($healthOptions['conditions'] as $v=>$k): ?><label><input type="checkbox" name="conditions[]" value="<?= $v ?>"><span><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?></div></fieldset>
            <div class="mt-3 d-none" data-show-if="conditions:other"><label class="form-label"><?= htmlspecialchars(t('health_indicate_which'),ENT_QUOTES,'UTF-8') ?></label><input class="form-control" name="condition_other" maxlength="255"></div>
            <div class="health-subcard"><label class="form-label d-block"><?= htmlspecialchars(t('health_medications'),ENT_QUOTES,'UTF-8') ?></label><div class="health-radio-row"><?php foreach(['yes'=>'health_yes','no'=>'health_no','prefer_not'=>'health_prefer_not'] as $v=>$k): ?><label><input type="radio" name="medication_choice" value="<?= $v ?>"><span><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?></div><div class="row g-3 mt-1 d-none" data-show-if="medication_choice:yes"><div class="col-12 col-md-6"><label class="form-label"><?= htmlspecialchars(t('health_medications_names'),ENT_QUOTES,'UTF-8') ?></label><textarea class="form-control" name="medications_text" rows="2" maxlength="1000"></textarea></div><div class="col-12 col-md-6"><label class="form-label"><?= htmlspecialchars(t('health_medications_emergency'),ENT_QUOTES,'UTF-8') ?></label><textarea class="form-control" name="medications_emergency" rows="2" maxlength="1500"></textarea></div></div></div>
            <fieldset class="health-fieldset" data-exclusive-group="allergies"><legend><?= htmlspecialchars(t('health_allergies'),ENT_QUOTES,'UTF-8') ?></legend><div class="health-check-grid"><?php foreach($healthOptions['allergies'] as $v=>$k): ?><label><input type="checkbox" name="allergies[]" value="<?= $v ?>"><span><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?></div></fieldset>
            <div class="d-none mt-3" data-show-if="has_allergy"><label class="form-label"><?= htmlspecialchars(t('health_allergy_details'),ENT_QUOTES,'UTF-8') ?></label><textarea class="form-control" name="allergy_details" rows="2" maxlength="1000"></textarea><label class="form-label mt-3 d-block"><?= htmlspecialchars(t('health_severe_reaction'),ENT_QUOTES,'UTF-8') ?></label><div class="health-radio-row"><?php foreach(['yes'=>'health_yes','no'=>'health_no','dont_know'=>'health_dont_know'] as $v=>$k): ?><label><input type="radio" name="severe_reaction" value="<?= $v ?>"><span><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?></div><div class="d-none mt-3" data-show-if="severe_reaction:yes"><label class="form-label"><?= htmlspecialchars(t('health_severe_info'),ENT_QUOTES,'UTF-8') ?></label><textarea class="form-control" name="severe_reaction_info" rows="2" maxlength="1500"></textarea></div></div>
          </section>

          <section class="health-step d-none" data-health-step="2"><h3><?= htmlspecialchars(t('health_step_occupational'),ENT_QUOTES,'UTF-8') ?></h3><label class="form-label d-block"><?= htmlspecialchars(t('health_occupational_question'),ENT_QUOTES,'UTF-8') ?></label><div class="health-radio-row"><?php foreach(['yes'=>'health_yes','no'=>'health_no','under_evaluation'=>'health_under_evaluation','prefer_not'=>'health_prefer_not'] as $v=>$k): ?><label><input type="radio" name="occupational_choice" value="<?= $v ?>"><span><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?></div><div class="d-none mt-3" data-show-if="occupational_choice:yes"><fieldset class="health-fieldset"><legend><?= htmlspecialchars(t('health_occupational_which'),ENT_QUOTES,'UTF-8') ?></legend><div class="health-check-grid"><?php foreach($healthOptions['diseases'] as $v=>$k): ?><label><input type="checkbox" name="occupational_diseases[]" value="<?= $v ?>"><span><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?></div></fieldset><div class="d-none mt-3" data-show-if="occupational_diseases:other"><label class="form-label"><?= htmlspecialchars(t('health_indicate_which'),ENT_QUOTES,'UTF-8') ?></label><textarea class="form-control" name="occupational_other" rows="2" maxlength="1000"></textarea></div></div></section>

          <section class="health-step d-none" data-health-step="3"><h3><?= htmlspecialchars(t('health_step_restrictions'),ENT_QUOTES,'UTF-8') ?></h3><label class="form-label d-block"><?= htmlspecialchars(t('health_restriction_question'),ENT_QUOTES,'UTF-8') ?></label><div class="health-radio-row"><?php foreach(['yes'=>'health_yes','no'=>'health_no','prefer_not'=>'health_prefer_not'] as $v=>$k): ?><label><input type="radio" name="restriction_choice" value="<?= $v ?>"><span><?= htmlspecialchars(t($k),ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?></div><div class="d-none mt-3" data-show-if="restriction_choice:yes"><label class="form-label"><?= htmlspecialchars(t('health_restriction_details'),ENT_QUOTES,'UTF-8') ?></label><textarea class="form-control" name="restriction_details" rows="3" maxlength="1500"></textarea></div></section>

          <section class="health-step d-none" data-health-step="4"><h3><?= htmlspecialchars(t('health_step_declaration'),ENT_QUOTES,'UTF-8') ?></h3><div class="health-summary"><h4><?= htmlspecialchars(t('health_summary_title'),ENT_QUOTES,'UTF-8') ?></h4><dl><div><dt><?= htmlspecialchars(t('health_mobile'),ENT_QUOTES,'UTF-8') ?></dt><dd data-health-summary="phone">—</dd></div><div><dt><?= htmlspecialchars(t('health_emergency_primary'),ENT_QUOTES,'UTF-8') ?></dt><dd data-health-summary="contact">—</dd></div><div><dt><?= htmlspecialchars(t('health_conditions'),ENT_QUOTES,'UTF-8') ?></dt><dd data-health-summary="conditions">—</dd></div><div><dt><?= htmlspecialchars(t('health_allergies'),ENT_QUOTES,'UTF-8') ?></dt><dd data-health-summary="allergies">—</dd></div><div><dt><?= htmlspecialchars(t('health_step_occupational'),ENT_QUOTES,'UTF-8') ?></dt><dd data-health-summary="occupational">—</dd></div><div><dt><?= htmlspecialchars(t('health_step_restrictions'),ENT_QUOTES,'UTF-8') ?></dt><dd data-health-summary="restriction">—</dd></div></dl></div><div class="health-declaration"><p><?= htmlspecialchars(t('health_declaration_text'),ENT_QUOTES,'UTF-8') ?></p><label class="health-accept"><input type="checkbox" name="accepted" value="1"><span><?= htmlspecialchars(t('health_accept'),ENT_QUOTES,'UTF-8') ?></span></label></div></section>
        </form>
      </div>
      <div class="modal-footer health-modal__footer"><button type="button" class="btn btn-outline-custom" data-health-prev><?= htmlspecialchars(t('health_previous'),ENT_QUOTES,'UTF-8') ?></button><span class="health-modal__spacer"></span><button type="button" class="btn btn-primary-custom" data-health-next><?= htmlspecialchars(t('health_next'),ENT_QUOTES,'UTF-8') ?></button><button type="button" class="btn btn-primary-custom d-none" data-health-submit><?= htmlspecialchars(t('health_submit'),ENT_QUOTES,'UTF-8') ?></button></div>
    </div>
  </div>
</div>
<script>window.SCT_HEALTH_I18N={required:<?= json_encode(t('health_required_error'),JSON_UNESCAPED_UNICODE) ?>,saveError:<?= json_encode(t('health_save_error'),JSON_UNESCAPED_UNICODE) ?>,saved:<?= json_encode(t('health_saved'),JSON_UNESCAPED_UNICODE) ?>};</script>
<script src="<?= htmlspecialchars($healthBasePath.'js/health-form.js?v='.$ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"></script>
