<?php
require_once __DIR__ . '/common.php';
require_once __DIR__ . '/../../lib/repositorios/InduccionRepository.php';
requireCapabilityPage($pdo,'induction.view','../../acceso-denegado.php');
aplicarCabecerasSeguridad();
$perfil=currentUserProfile($pdo)?:[];$roles=currentUserRoles($pdo);$id=currentUserId();
$certificados=[];
try{
 $stmt=$pdo->prepare('SELECT c.id_certificate,c.code,c.issued_at,c.id_user_test_assigned,t.name,t.type,a.id_test FROM certificates c INNER JOIN users_test_assigned a ON a.id_user_test_assigned=c.id_user_test_assigned INNER JOIN company_test t ON t.id_test=a.id_test WHERE a.id_users=:id_users AND c.state=1 ORDER BY c.issued_at DESC,c.id_certificate DESC');
 $stmt->execute(['id_users'=>$id]);$certificados=$stmt->fetchAll();
}catch(Throwable $e){error_log('mis-certificados.php: '.$e->getMessage());}
?>
<!doctype html><html lang="<?= htmlspecialchars(idiomaActual(),ENT_QUOTES,'UTF-8') ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars(t('certificates_title'),ENT_QUOTES,'UTF-8') ?> - SCT</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"><link rel="stylesheet" href="../../css/style.css?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"><script>document.documentElement.classList.add('sct-vs4-frontend');try{if(localStorage.getItem('sct-theme')==='dark')document.documentElement.classList.add('sct-theme-dark');}catch(e){}</script><link rel="stylesheet" href="../../css/sct-v3-frontend.css?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"></head><body><?php $sctNavbarBasePath='../../';require __DIR__.'/../../partials/app-navbar.php';?><main class="worker-home"><section class="worker-home__greeting"><div><span class="worker-home__eyebrow">Safety Control Tower</span><h1><?= htmlspecialchars(t('certificates_title'),ENT_QUOTES,'UTF-8') ?></h1><p><?= htmlspecialchars(t('certificates_intro'),ENT_QUOTES,'UTF-8') ?></p></div></section><section class="worker-module-section"><?php if(!$certificados): ?><div class="feature-card"><p class="mb-0"><?= htmlspecialchars(t('certificates_empty'),ENT_QUOTES,'UTF-8') ?></p></div><?php else: ?><div class="feature-card table-responsive"><table class="table align-middle mb-0"><thead><tr><th><?= htmlspecialchars(t('home_courses'),ENT_QUOTES,'UTF-8') ?></th><th><?= htmlspecialchars(t('common_date'),ENT_QUOTES,'UTF-8') ?></th><th></th></tr></thead><tbody><?php foreach($certificados as $c): ?><tr><td><strong><?= htmlspecialchars($c['name'],ENT_QUOTES,'UTF-8') ?></strong><div class="small text-muted"><?= htmlspecialchars(strtoupper((string)$c['type']),ENT_QUOTES,'UTF-8') ?></div></td><td><?= htmlspecialchars((string)$c['issued_at'],ENT_QUOTES,'UTF-8') ?></td><td class="text-end"><a class="btn btn-primary-custom btn-sm" target="_blank" rel="noopener" href="certificado-descargar.php?id_asignacion=<?= (int)$c['id_user_test_assigned'] ?>"><i class="bi bi-download"></i> <?= htmlspecialchars(t('certificates_download'),ENT_QUOTES,'UTF-8') ?></a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></main></body></html>
