<?php
require_once __DIR__.'/common.php';
programasRequirePage($pdo,'../../acceso-denegado.php');
aplicarCabecerasSeguridad();
if (empty($_SESSION['csrf_token'])) $_SESSION['csrf_token']=bin2hex(random_bytes(32));
$isGlobalAdmin=programasIsGlobalAdmin($pdo);
$canCreate=currentUserHasCapability($pdo,'programs.create');
$canEdit=currentUserHasCapability($pdo,'programs.edit');
$canState=currentUserHasCapability($pdo,'programs.state');
$canTracking=currentUserHasCapability($pdo,'programs.tracking');
$schemaReady=programasSchemaReady($pdo);
$userEmail=htmlspecialchars((string)($_SESSION['user_email']??''),ENT_QUOTES,'UTF-8');
$csrf=htmlspecialchars((string)$_SESSION['csrf_token'],ENT_QUOTES,'UTF-8');
$jsKeys=[
'programs_loading','programs_error','programs_empty','programs_saved','programs_updated','programs_state_updated','programs_tracking_saved',
'programs_select_company','programs_all_status','programs_all_state','programs_all_projects','programs_active','programs_inactive','programs_no_project','programs_select_responsible','programs_no_tracking','programs_new',
'programs_edit','programs_view_detail','programs_deactivate','programs_activate','programs_confirm_state','programs_tracking_edit','programs_behind','programs_on_track',
'programs_status_planificado','programs_status_en_curso','programs_status_completado','programs_status_suspendido','programs_status_cancelado'
];
$jsStrings=[]; foreach($jsKeys as $k)$jsStrings[$k]=t($k);
?>
<!DOCTYPE html>
<html lang="<?=htmlspecialchars(idiomaActual(),ENT_QUOTES,'UTF-8')?>">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=htmlspecialchars(t('programs_page_title'),ENT_QUOTES,'UTF-8')?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="../../css/style.css?v=<?=htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8')?>">
<style>
.program-shell{padding-bottom:4rem}.welcome-hero{padding:3rem 0 1.5rem}.welcome-topbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1.25rem 0;border-bottom:1px solid rgba(0,0,0,.08)}.welcome-topbar .brand-symbol img{height:32px}.topbar-actions{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap}.language-select{min-width:120px}.program-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.8rem}.program-kpi{border:1px solid var(--border);border-radius:14px;padding:1rem;background:var(--background-soft)}.program-kpi strong{display:block;font-size:1.55rem;color:var(--primary-darkest)}.program-list{display:grid;gap:.8rem}.program-card{border:1px solid var(--border);border-radius:14px;padding:1rem;background:#fff}.program-card.inactive{opacity:.68}.program-card-top{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.program-meta{display:flex;gap:.45rem;flex-wrap:wrap;font-size:.8rem}.program-actions{display:flex;gap:.4rem;flex-wrap:wrap}.progress{height:9px}.detail-panel{display:none}.detail-panel.active{display:block}.tracking-table td,.tracking-table th{vertical-align:middle}.variance.pos{font-weight:700}.variance.neg{font-weight:700}.form-actions{display:flex;gap:.5rem;flex-wrap:wrap}.small-muted{font-size:.82rem;color:var(--text-secondary)}
@media(max-width:991.98px){.program-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:767.98px){.welcome-topbar{align-items:flex-start}.topbar-actions{justify-content:flex-end}.program-card-top{flex-direction:column}.program-kpis{grid-template-columns:1fr 1fr}.tracking-table thead{display:none}.tracking-table,.tracking-table tbody,.tracking-table tr,.tracking-table td{display:block;width:100%}.tracking-table tr{border:1px solid var(--border);border-radius:12px;margin-bottom:.75rem;padding:.45rem}.tracking-table td{border:0;padding:.35rem .5rem}.tracking-table td::before{content:attr(data-label);display:block;font-size:.72rem;font-weight:700;color:var(--text-secondary);text-transform:uppercase}}
</style>
</head>
<body>
<div class="container program-shell" data-csrf-token="<?=$csrf?>" data-is-global-admin="<?=$isGlobalAdmin?'1':'0'?>" data-can-create="<?=$canCreate?'1':'0'?>" data-can-edit="<?=$canEdit?'1':'0'?>" data-can-state="<?=$canState?'1':'0'?>" data-can-tracking="<?=$canTracking?'1':'0'?>">
<div class="welcome-topbar"><div class="brand-wrapper"><div class="brand-symbol"><img src="../../images/logos/Logo-SCT-white.png" alt="Safety Control Tower"></div></div><div class="topbar-actions"><select id="pageLanguageSelect" class="form-select form-select-sm language-select" aria-label="<?=htmlspecialchars(t('common_language'),ENT_QUOTES,'UTF-8')?>"><?php foreach(idiomasDisponiblesConNombre() as $code=>$name):?><option value="<?=htmlspecialchars($code,ENT_QUOTES,'UTF-8')?>" <?=$code===idiomaActual()?'selected':''?>><?=htmlspecialchars($name,ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select><a href="../usuarios/gestiones.php" class="btn btn-outline-custom btn-sm"><?=htmlspecialchars(t('mgmt_back'),ENT_QUOTES,'UTF-8')?> <i class="bi bi-arrow-left"></i></a><a href="../../logout.php" class="btn btn-outline-custom btn-sm"><?=htmlspecialchars(t('common_logout'),ENT_QUOTES,'UTF-8')?> <i class="bi bi-box-arrow-right"></i></a></div></div>
<section class="welcome-hero text-center"><div class="welcome-greeting-icon"><i class="bi bi-calendar3-range"></i></div><span class="section-label">SAFETY CONTROL TOWER</span><h1 class="section-title"><?=htmlspecialchars(t('programs_title'),ENT_QUOTES,'UTF-8')?></h1><p class="section-description intro-description-centered"><?=htmlspecialchars(t('programs_intro'),ENT_QUOTES,'UTF-8')?> <strong><?=$userEmail?></strong>.</p></section>
<?php if(!$schemaReady):?><div class="alert alert-warning"><?=htmlspecialchars(t('programs_migration_required'),ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div id="programsAlert" class="alert d-none" role="alert" aria-live="polite"></div>

<section class="feature-card mb-4">
<div class="row g-3 align-items-end">
<?php if($isGlobalAdmin):?><div class="col-12 col-lg-4"><label class="form-label" for="companySelect"><?=htmlspecialchars(t('programs_company'),ENT_QUOTES,'UTF-8')?></label><select id="companySelect" class="form-select"><option value=""><?=htmlspecialchars(t('programs_select_company'),ENT_QUOTES,'UTF-8')?></option></select></div><?php endif;?>
<div class="col-6 col-lg-2"><label class="form-label" for="statusFilter"><?=htmlspecialchars(t('programs_status'),ENT_QUOTES,'UTF-8')?></label><select id="statusFilter" class="form-select"><option value=""><?=htmlspecialchars(t('programs_all_status'),ENT_QUOTES,'UTF-8')?></option><?php foreach(PROGRAM_STATUS as $st):?><option value="<?=$st?>"><?=htmlspecialchars(t('programs_status_'.$st),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div>
<div class="col-6 col-lg-2"><label class="form-label" for="stateFilter"><?=htmlspecialchars(t('programs_record_state'),ENT_QUOTES,'UTF-8')?></label><select id="stateFilter" class="form-select"><option value=""><?=htmlspecialchars(t('programs_all_state'),ENT_QUOTES,'UTF-8')?></option><option value="1"><?=htmlspecialchars(t('programs_active'),ENT_QUOTES,'UTF-8')?></option><option value="0"><?=htmlspecialchars(t('programs_inactive'),ENT_QUOTES,'UTF-8')?></option></select></div>
<div class="col-12 col-lg-2"><label class="form-label" for="projectFilter"><?=htmlspecialchars(t('programs_project'),ENT_QUOTES,'UTF-8')?></label><select id="projectFilter" class="form-select"><option value=""><?=htmlspecialchars(t('programs_all_projects'),ENT_QUOTES,'UTF-8')?></option></select></div>
<div class="col-12 col-lg-2"><label class="form-label" for="searchFilter"><?=htmlspecialchars(t('programs_search'),ENT_QUOTES,'UTF-8')?></label><input id="searchFilter" class="form-control" maxlength="100" placeholder="<?=htmlspecialchars(t('programs_search_placeholder'),ENT_QUOTES,'UTF-8')?>"></div>
</div></section>

<section class="program-kpis mb-4"><div class="program-kpi"><span><?=htmlspecialchars(t('programs_kpi_total'),ENT_QUOTES,'UTF-8')?></span><strong id="kpiTotal">0</strong></div><div class="program-kpi"><span><?=htmlspecialchars(t('programs_kpi_active'),ENT_QUOTES,'UTF-8')?></span><strong id="kpiActive">0</strong></div><div class="program-kpi"><span><?=htmlspecialchars(t('programs_kpi_average'),ENT_QUOTES,'UTF-8')?></span><strong id="kpiAverage">0%</strong></div><div class="program-kpi"><span><?=htmlspecialchars(t('programs_kpi_completed'),ENT_QUOTES,'UTF-8')?></span><strong id="kpiCompleted">0</strong></div><div class="program-kpi"><span><?=htmlspecialchars(t('programs_kpi_behind'),ENT_QUOTES,'UTF-8')?></span><strong id="kpiBehind">0</strong></div></section>

<?php if($canCreate||$canEdit):?><section class="feature-card mb-4"><h2 class="h5 mb-3" id="programFormTitle"><?=htmlspecialchars(t('programs_new'),ENT_QUOTES,'UTF-8')?></h2><form id="programForm" novalidate><input type="hidden" id="programId"><div class="row g-3"><div class="col-12 col-lg-6"><label class="form-label" for="programName"><?=htmlspecialchars(t('programs_name'),ENT_QUOTES,'UTF-8')?></label><input id="programName" class="form-control" maxlength="150" required></div><div class="col-12 col-lg-6"><label class="form-label" for="programProject"><?=htmlspecialchars(t('programs_project'),ENT_QUOTES,'UTF-8')?></label><select id="programProject" class="form-select"><option value=""><?=htmlspecialchars(t('programs_no_project'),ENT_QUOTES,'UTF-8')?></option></select></div><div class="col-12"><label class="form-label" for="programDescription"><?=htmlspecialchars(t('programs_description'),ENT_QUOTES,'UTF-8')?></label><textarea id="programDescription" class="form-control" rows="2" maxlength="5000"></textarea></div><div class="col-12 col-md-4"><label class="form-label" for="programResponsible"><?=htmlspecialchars(t('programs_responsible'),ENT_QUOTES,'UTF-8')?></label><select id="programResponsible" class="form-select" required><option value=""><?=htmlspecialchars(t('programs_select_responsible'),ENT_QUOTES,'UTF-8')?></option></select></div><div class="col-6 col-md-3"><label class="form-label" for="programStart"><?=htmlspecialchars(t('programs_start'),ENT_QUOTES,'UTF-8')?></label><input id="programStart" type="date" class="form-control" required></div><div class="col-6 col-md-3"><label class="form-label" for="programEnd"><?=htmlspecialchars(t('programs_end'),ENT_QUOTES,'UTF-8')?></label><input id="programEnd" type="date" class="form-control"></div><div class="col-12 col-md-2"><label class="form-label" for="programStatus"><?=htmlspecialchars(t('programs_status'),ENT_QUOTES,'UTF-8')?></label><select id="programStatus" class="form-select"><?php foreach(PROGRAM_STATUS as $st):?><option value="<?=$st?>"><?=htmlspecialchars(t('programs_status_'.$st),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div></div><div class="form-actions mt-3"><button class="btn btn-primary-custom" id="programSaveBtn" type="submit"><?=htmlspecialchars(t('programs_save'),ENT_QUOTES,'UTF-8')?></button><button class="btn btn-outline-secondary d-none" id="programCancelBtn" type="button"><?=htmlspecialchars(t('programs_cancel_edit'),ENT_QUOTES,'UTF-8')?></button></div></form></section><?php endif;?>

<section class="feature-card mb-4"><div class="d-flex justify-content-between align-items-center gap-3 flex-wrap mb-3"><div><h2 class="h5 mb-1"><?=htmlspecialchars(t('programs_list_title'),ENT_QUOTES,'UTF-8')?></h2><p class="small-muted mb-0"><?=htmlspecialchars(t('programs_list_intro'),ENT_QUOTES,'UTF-8')?></p></div><button id="reloadBtn" class="btn btn-outline-custom btn-sm"><i class="bi bi-arrow-clockwise"></i> <?=htmlspecialchars(t('programs_reload'),ENT_QUOTES,'UTF-8')?></button></div><div id="programsStatus" class="alert alert-info"><?=htmlspecialchars(t('programs_loading'),ENT_QUOTES,'UTF-8')?></div><div id="programsList" class="program-list"></div></section>

<section id="detailPanel" class="feature-card detail-panel"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-3"><div><span class="section-label"><?=htmlspecialchars(t('programs_detail'),ENT_QUOTES,'UTF-8')?></span><h2 class="h4 mb-1" id="detailName"></h2><p id="detailMeta" class="small-muted mb-0"></p></div><button id="closeDetailBtn" class="btn btn-outline-secondary btn-sm"><i class="bi bi-x-lg"></i></button></div><div id="detailDescription" class="mb-3"></div><div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="program-kpi"><span><?=htmlspecialchars(t('programs_responsible'),ENT_QUOTES,'UTF-8')?></span><strong class="fs-6" id="detailResponsible">—</strong></div></div><div class="col-6 col-lg-3"><div class="program-kpi"><span><?=htmlspecialchars(t('programs_latest_progress'),ENT_QUOTES,'UTF-8')?></span><strong id="detailProgress">—</strong></div></div><div class="col-6 col-lg-3"><div class="program-kpi"><span><?=htmlspecialchars(t('programs_latest_target'),ENT_QUOTES,'UTF-8')?></span><strong id="detailTarget">—</strong></div></div><div class="col-6 col-lg-3"><div class="program-kpi"><span><?=htmlspecialchars(t('programs_tracking_count'),ENT_QUOTES,'UTF-8')?></span><strong id="detailTrackingCount">0</strong></div></div></div>
<?php if($canTracking):?><div class="border rounded-3 p-3 mb-4"><h3 class="h6 mb-3"><?=htmlspecialchars(t('programs_tracking_form'),ENT_QUOTES,'UTF-8')?></h3><form id="trackingForm"><input type="hidden" id="trackingProgramId"><div class="row g-3"><div class="col-6 col-lg-2"><label class="form-label" for="trackingMonth"><?=htmlspecialchars(t('programs_period'),ENT_QUOTES,'UTF-8')?></label><input id="trackingMonth" type="month" class="form-control" required></div><div class="col-6 col-lg-2"><label class="form-label" for="trackingTarget"><?=htmlspecialchars(t('programs_target'),ENT_QUOTES,'UTF-8')?> %</label><input id="trackingTarget" type="number" class="form-control" min="0" max="100" step="0.01"></div><div class="col-6 col-lg-2"><label class="form-label" for="trackingProgress"><?=htmlspecialchars(t('programs_progress'),ENT_QUOTES,'UTF-8')?> %</label><input id="trackingProgress" type="number" class="form-control" min="0" max="100" step="0.01" required></div><div class="col-12 col-lg-6"><label class="form-label" for="trackingComments"><?=htmlspecialchars(t('programs_comments'),ENT_QUOTES,'UTF-8')?></label><input id="trackingComments" class="form-control" maxlength="5000"></div></div><div class="form-actions mt-3"><button class="btn btn-primary-custom" type="submit"><?=htmlspecialchars(t('programs_tracking_save'),ENT_QUOTES,'UTF-8')?></button><button class="btn btn-outline-secondary d-none" id="trackingCancelBtn" type="button"><?=htmlspecialchars(t('programs_cancel_edit'),ENT_QUOTES,'UTF-8')?></button></div></form></div><?php endif;?>
<h3 class="h6 mb-3"><?=htmlspecialchars(t('programs_tracking_history'),ENT_QUOTES,'UTF-8')?></h3><div class="table-responsive"><table class="table tracking-table"><thead><tr><th><?=htmlspecialchars(t('programs_period'),ENT_QUOTES,'UTF-8')?></th><th><?=htmlspecialchars(t('programs_target'),ENT_QUOTES,'UTF-8')?></th><th><?=htmlspecialchars(t('programs_progress'),ENT_QUOTES,'UTF-8')?></th><th><?=htmlspecialchars(t('programs_variance'),ENT_QUOTES,'UTF-8')?></th><th><?=htmlspecialchars(t('programs_comments'),ENT_QUOTES,'UTF-8')?></th><th><?=htmlspecialchars(t('programs_reported_by'),ENT_QUOTES,'UTF-8')?></th><?php if($canTracking):?><th><?=htmlspecialchars(t('common_actions'),ENT_QUOTES,'UTF-8')?></th><?php endif;?></tr></thead><tbody id="trackingBody"></tbody></table></div></section>
</div>
<script id="programsI18n" type="application/json"><?=json_encode($jsStrings,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
<script src="../../js/programas-admin.js?v=<?=htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8')?>"></script>
<script src="../../js/lang-switcher.js?v=<?=htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8')?>"></script>
</body></html>
