<?php
require_once __DIR__.'/common.php';
require_once __DIR__.'/../../i18n.php';
requireCapabilityPage($pdo, 'dynamic_forms.view', '../../acceso-denegado.php');
aplicarCabecerasSeguridad();
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$csrf=htmlspecialchars((string)$_SESSION['csrf_token'],ENT_QUOTES,'UTF-8');
$userEmail=htmlspecialchars((string)($_SESSION['user_email']??''),ENT_QUOTES,'UTF-8');
$jsKeys=['forms_error_response','my_forms_loading','my_forms_empty','my_forms_complete','my_forms_history_empty','my_forms_submitted','my_forms_open','my_forms_required','my_forms_submit','my_forms_cancel','forms_scope_global','forms_company_badge','forms_global_badge','forms_submission_answers','forms_file_download','forms_submission_date','forms_field_required','forms_migration_required'];
$jsStrings=[];foreach($jsKeys as $k)$jsStrings[$k]=t($k);
$langSwitcherStrings=['title'=>t('common_confirm_language_title'),'text'=>t('common_confirm_language_text'),'confirm'=>t('common_confirm'),'cancel'=>t('common_cancel'),'updated'=>t('common_language_updated')];
?>
<!DOCTYPE html><html lang="<?= htmlspecialchars(idiomaActual(),ENT_QUOTES,'UTF-8') ?>"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title><?= htmlspecialchars(t('my_forms_page_title'),ENT_QUOTES,'UTF-8') ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"><link rel="stylesheet" href="../../css/style.css?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>">
<style>.welcome-hero{padding:3rem 0 1.5rem}.welcome-topbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1.25rem 0;border-bottom:1px solid rgba(0,0,0,.08)}.welcome-topbar .brand-symbol img{height:32px}.topbar-actions{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;justify-content:flex-end}.welcome-greeting-icon{font-size:2.4rem;color:var(--primary);margin-bottom:.6rem}.quick-links{margin:1.5rem 0 3rem}.language-select{min-width:120px}.form-card{border:1px solid var(--border);border-radius:var(--radius-md);padding:1.1rem;margin-bottom:.85rem;background:#fff}.scope-badge{font-size:.74rem;padding:.25rem .55rem;border-radius:999px;background:rgba(0,163,244,.12);color:var(--primary-dark);font-weight:700}.scope-badge.global{background:rgba(124,58,237,.1);color:#7c3aed}.dynamic-field{border-bottom:1px solid var(--border);padding-bottom:1rem;margin-bottom:1rem}.dynamic-field:last-child{border-bottom:0}.history-row{border:1px solid var(--border);border-radius:var(--radius-md);padding:.85rem 1rem;margin-bottom:.65rem}.answer-line{border-bottom:1px solid var(--border);padding:.75rem 0}.answer-line:last-child{border-bottom:0}.answer-label{font-weight:700}.answer-value{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:575.98px){.welcome-topbar{align-items:flex-start}.topbar-actions{max-width:72%}}</style></head><body>
<div class="container" data-csrf-token="<?= $csrf ?>"><div class="welcome-topbar"><div class="brand-wrapper"><div class="brand-symbol"><img src="../../images/logos/Logo-SCT-white.png" alt="Safety Control Tower"></div></div><div class="topbar-actions"><select id="pageLanguageSelect" class="form-select form-select-sm language-select" aria-label="<?= htmlspecialchars(t('common_language'),ENT_QUOTES,'UTF-8') ?>"><?php foreach(idiomasDisponiblesConNombre() as $code=>$name): ?><option value="<?= htmlspecialchars($code,ENT_QUOTES,'UTF-8') ?>" <?= $code===idiomaActual()?'selected':'' ?>><?= htmlspecialchars($name,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select><a href="../usuarios/gestiones.php" class="btn btn-outline-custom btn-sm"><?= htmlspecialchars(t('mgmt_back'),ENT_QUOTES,'UTF-8') ?> <i class="bi bi-arrow-left"></i></a><a href="../../logout.php" class="btn btn-outline-custom btn-sm"><?= htmlspecialchars(t('common_logout'),ENT_QUOTES,'UTF-8') ?> <i class="bi bi-box-arrow-right"></i></a></div></div>
<section class="welcome-hero text-center"><div class="welcome-greeting-icon"><i class="bi bi-card-text"></i></div><span class="section-label">SAFETY CONTROL TOWER</span><h1 class="section-title"><?= htmlspecialchars(t('my_forms_title'),ENT_QUOTES,'UTF-8') ?></h1><p class="section-description intro-description-centered"><?= htmlspecialchars(t('my_forms_intro'),ENT_QUOTES,'UTF-8') ?> <strong><?= $userEmail ?></strong>.</p></section>
<section class="quick-links"><div id="myFormsAlert" class="alert d-none" role="alert"></div><div class="feature-card mb-4"><h2 class="h5 mb-3"><?= htmlspecialchars(t('my_forms_available_title'),ENT_QUOTES,'UTF-8') ?></h2><div id="availableStatus" class="alert alert-info mb-0"><?= htmlspecialchars(t('my_forms_loading'),ENT_QUOTES,'UTF-8') ?></div><div id="availableList" class="d-none"></div></div>
<div class="feature-card mb-4"><h2 class="h5 mb-3"><?= htmlspecialchars(t('my_forms_history_title'),ENT_QUOTES,'UTF-8') ?></h2><div id="historyList"></div></div>
<div id="fillPanel" class="feature-card mb-4 d-none"><div class="d-flex justify-content-between gap-3 align-items-start"><div><span class="section-label"><?= htmlspecialchars(t('my_forms_complete'),ENT_QUOTES,'UTF-8') ?></span><h2 id="fillTitle" class="h5 mb-0">-</h2></div><button id="fillClose" class="btn btn-outline-custom btn-sm" type="button"><?= htmlspecialchars(t('my_forms_cancel'),ENT_QUOTES,'UTF-8') ?></button></div><p id="fillDescription" class="text-muted mt-2"></p><div id="fillAlert" class="alert d-none" role="alert"></div><form id="fillForm" enctype="multipart/form-data"><div id="fillFields"></div><button id="fillSubmit" class="btn btn-primary-custom mt-2" type="submit"><?= htmlspecialchars(t('my_forms_submit'),ENT_QUOTES,'UTF-8') ?></button></form></div>
<div id="historyDetail" class="feature-card d-none"><div class="d-flex justify-content-between gap-3"><h2 class="h5"><?= htmlspecialchars(t('forms_submission_answers'),ENT_QUOTES,'UTF-8') ?></h2><button id="historyDetailClose" class="btn btn-outline-custom btn-sm" type="button"><?= htmlspecialchars(t('my_forms_cancel'),ENT_QUOTES,'UTF-8') ?></button></div><div id="historyAnswers"></div></div></section></div>
<script id="myFormsI18n" type="application/json"><?= json_encode($jsStrings,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
<script>window.SCT_LANG_SWITCHER_I18N = <?= json_encode($langSwitcherStrings, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;</script>
<script src="../../js/lang-switcher.js?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"></script>
<script src="../../js/formularios-mis.js?v=<?= htmlspecialchars($ASSET_VERSION,ENT_QUOTES,'UTF-8') ?>"></script></body></html>
