/*
 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 analytics.js v1.0
 Created: 2025-02-03T15:47:01+0000

*/
(function(l,a){if(!l.ORA.analytics){var b=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PRODUCT_READY,ORA.Event.STATUS_SUCCESS));ORA.common.TrackingPipeline.productIsReady("analytics");ORA.Debug.debug("setProductReady()","ANA")};ORA.analytics={dcsRef:null,plugins:{},addEventListener:ORA.addDOMEvent,eventQueue:null,version:{major:1,minor:0,inc:4},versionStr:"1.0.4",qryparams:{},dcsdelay:25,productReadyLatch:{},isSeedMessageTriggered:!1,elemOfEvent:function(c,d){var f=c.target||c.srcElement,
g=d||{};"string"===typeof d&&(g={},g[d.toUpperCase()]=1);for(;f&&f.tagName&&!g[f.tagName.toUpperCase()];)f=f.parentElement||f.parentNode;return f},multiTrack:function(c){try{return ORA.analytics.dcsRef.dcsMultiTrack(c),!1}catch(d){throw ORA.Debug.error("Error ORA.analytics.multiTrack: "+d.toSource(),"ANA"),d;}},instantiateExternal:function(){ORA.analytics.qryparams=ORA.common.QueryParamCache.getCache();ORA.analytics.loadJS=ORA.common.loadJS;ORA.analytics.eventQueue=new ORA.common.Queue;ORA.analytics.prettify=
ORA.common.JSONPrettify;ORA.analytics.dcsSaveCookie=ORA.common._setCookie;ORA.analytics.dcsDeleteCookie=ORA.common._deleteCookie;ORA.analytics.extendArray=ORA.common.extendArray;ORA.analytics.isFn=ORA.common.isFn;ORA.analytics.isArray=ORA.common.isArray;ORA.analytics.getCookieAsObj=ORA.common._getCookieAsObj;ORA.analytics.isEmpty=ORA.common.isEmpty;ORA.analytics.click=ORA.click;ORA.analytics.view=ORA.view;ORA.analytics.collect=ORA.collect;ORA.analytics.regPlugin=ORA.regPlugin;ORA.analytics.getTagId=
ORA.getTagId;ORA.analytics.getContextName=ORA.getContextName;ORA.analytics.getPluginsConfig=ORA.analytics._getPluginsConfig;ORA.analytics.setCookie=ORA.common._setCookie;ORA.analytics.deleteCookie=ORA.common._deleteCookie;ORA.analytics.getCookieRaw=ORA.common._getCookieRaw;ORA.analytics.getIEVer=ORA.common._getIEVer;ORA.analytics.isOptedOut=ORA.common._isOptedOut;ORA.analytics.setInfinityOptOut=ORA.common._setInfinityOptOut;ORA.analytics.addMutation=ORA.analytics.addMutation;ORA.analytics.rmMutation=
ORA.analytics.rmMutation;ORA.analytics.getFPC=function(){var c=ORA.analytics.getCookieAsObj(ORA.analytics.dcsRef.FPCConfig.name);return c&&c.id?c.id:null}},reset:function(){ORA.Debug.info("Analytics reset()","ANA");ORA.analytics.dscRef={}},execute:function(c){ORA.Debug.info("Analytics execute()","ANA");ORA.analytics.reset();var d=ORA.analyticsModule.prototype.oraConfigObj;c&&c.params&&ORA.hasVal(c.params)?(c=ORA.common.getMergedConfigs(d,c.params),ORA.analytics.setup(c)):ORA.analytics.setup(d)},performView:function(){ORA.common.clientID.isWaitForSetClientId&&
ORA.common.clientID.isClientIdSet&&(ORA.addEventHandler(ORA.Event.ANA_PRODUCT_READY,ORA.view()),ORA.common.clientID.isWaitForSetClientId=!1)},registerLoaderEvents:function(){ORA.addEventHandler(ORA.Event.LOADER_RESET,this.reset);ORA.addEventHandler(ORA.Event.LOADER_EXECUTE,this.execute);ORA.common.clientID.isClientIdSet?this.performView():ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,this.performView)},setupPluginMgr:function(c){var d=ORA.analytics.getPluginCount("ora-plugins"),f=ORA.common.pluginMgr,
g=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - ora Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<d?(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+d+"), deferring initPluginsCallback until plugins loaded","ANA"),f.setNumExpectedPlugins(d),f.setInitPluginsCallback(g),f.setInjectConfigsCb(ORA.analytics._getPluginsConfig,"ora-plugins")):(0===d&&c.waitForGetClientIDCallback.apply(c)?
(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+d+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS))):ORA.Debug.debug("setupPluginMgr - ora pluginCount("+d+"), not waiting on getId so countDown immediately","ANA"),g());f.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_ORA_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS));f=ORA.analytics.getPluginCount("hosted-plugins");var q=ORA.common.hostedPluginMgr,
u=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - Hosted Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<f?(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+f+"), deferring initPluginsCallback until plugins loaded","ANA"),q.setNumExpectedPlugins(f),q.setInitPluginsCallback(u),q.setInjectConfigsCb(ORA.analytics._getPluginsConfig),q.processHostedPlugins(c.config["hosted-plugins"])):
0===f&&c.waitForGetClientIDCallback.apply(c)?(ORA.Debug.debug("setupPluginMgr - hosted pluginCount("+d+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS)),g()):(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+d+"), not waiting on getId so countDown immediately","ANA"),u());q.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS))},setupProductCountdownLatch:function(c){var d=
2;c.waitForGetClientIDCallback.apply(c)&&(ORA.Debug.trace("prodCountdownLatch: waitForGetIdCall, latchCount++","ANA"),d++);ORA.analytics.productReadyLatch=new ORA.common.CountDownLatchClass(d,b,"ProductReadyLatch");ORA.Debug.debug("set productReadyLatch to "+d,"ANA")},setCheckSetDisableSeed:function(c){!0===c.s_disableSeed&&ORA.common.TrackingPipeline.disableSeed()},setWaitForSetClientId:function(c){!0===c.s_waitForSetClientId&&ORA.common.clientID.waitForSetClientId()},setup:function(c){try{ORA.Debug.debug("Analytics setup() started",
"ANA");this.instantiateExternal();this.setCheckSetDisableSeed(c);this.setWaitForSetClientId(c);var d=new ORA.analytics.dcs;d.init(c);this.setupProductCountdownLatch(d);d.setup();this.dcsRef=d;this.setupPluginMgr(this.dcsRef);this.registerLoaderEvents();ORA.fireEvent(new ORA.Event(ORA.Event.ANA_SETUP_COMPLETE,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("Analytics setup() has finished","ANA")}catch(f){ORA.Debug.error("Analytics setup() failure",201,f,"ANA")}},addMutation:function(c,d,f){return ORA.common.TrackingPipeline.registerMutation(c,
d,f?f:2)},rmMutation:function(c){return ORA.common.TrackingPipeline.deregisterMutation(c)},getProductTimeout:function(){return ORA.common.TrackingPipeline.getProduct("analytics").timeout},_getPluginsConfig:function(c,d){var f={};ORA.analyticsModule.prototype.oraConfigObj[d]&&ORA.analyticsModule.prototype.oraConfigObj[d][c]&&(f=ORA.analyticsModule.prototype.oraConfigObj[d][c]);return f},getPluginCount:function(c){return ORA.analyticsModule.prototype.oraConfigObj[c]?ORA.common.extendObject(ORA.analyticsModule.prototype.oraConfigObj[c]).length():
0},getConfigParams:function(){var c=ORA.analytics,d={},f=ORA.analytics.dcsRef;f&&ORA.common.extendArray(["accountGuid","destinations","enabled","i18n","timezone"]).forEach(function(g){f[g]&&(d[g]=f[g])});d.version=c.version;d.versionStr=[d.version.major,d.version.minor,d.version.inc].join(".");d.dcsdelay=c.dcsdelay;return d},getEndPoint:function(){return"https://"+ORA.analytics.dcsRef.destinations[0].collectionServer+"/v3/"+ORA.analytics.dcsRef.destinations[0].accountGuid}};ORA.Debug.debug("ORA.analytics instantiation success",
"ANA")}})(window,window.document);
(function(l,a){ORA.analytics.dcs=function(){var b=l.RegExp?RegExp("dcs(uri)|(ref)|(aut)|(met)|(sta)|(sip)|(pro)|(byt)|(dat)|(p3p)|(cfg)|(redirect)|(cip)","i"):"";this.exre=b;this.re={};this.plugins=this.plugins={};this.trackingData=this.trackingData={};this.DCS=this.DCS={};this.destinations=[];this.DCSext=this.DCSext={};this.errors=this.errors=[];this.FPCConfig=this.FPCConfig={};this._onsitedoms=[];this.gTempWtId=this.gWtAccountRollup=this.oraId="";this.prettify=ORA.analytics.prettify;return this};
ORA.analytics.dcs.prototype={init:function(b){var c=b;try{ORA.Debug.debug("dcs init() start","ANA");"undefined"===typeof c&&(c={});this.config=c;var d=this;b=function(u,t){return c.hasOwnProperty(u)?c[u]:t};var f=function(u,t,r){return u?u.hasOwnProperty(t)?u[t]:r:r};this.extendArray=ORA.common.extendArray;this.errorlogger=function(u){ORA.Debug.error("Dcs",100,u,"ANA")};c.defaultCollectionServer||ORA.Debug.error("dcs init:  missing defaultCollectionServer");this.destinations=this.destinations=function(u){if(!u||
0===u.length)throw Error("Destinations are not configured");for(var t=[],r=0;r<u.length;r++){var e=f(u[r],"collectionServer",c.defaultCollectionServer),m={};m.collectionServer=m.collectionServer=e;m.timeout=m.timeout=f(u[r],"timeout",2E3);m.accountGuid=m.accountGuid=u[r].accountGuid;m.endpoint=m.endpoint=d.collectionEndpoint(e,u[r].accountGuid);t.push(m)}return t}(c.destinations);this.accountGuid=this.accountGuid=this.destinations[0].accountGuid;this.queue=this.queue=b("queue",[]);this.wtidTimeout=
b("wtidTimeout",1E3);this.timezone=this.timezone=b("timezone",-8);this.enabled=this.enabled=b("enabled",!0);this.i18n=this.i18n=b("i18n",!1);this.re=l.RegExp?d.i18n?{"%25":/%/g,"%26":/&/g,"%23":/#/g}:{"%25":/%/g,"%09":/\t/g,"%20":/\x20|\xA0|\x7F/g,"%23":/#/g,"%26":/&/g,"%2B":/\+/g,"%3F":/\?/g,"%5C":/\\/g,"%22":/"/g}:"";if(c.metanames){var g=c.metanames.toLowerCase();this.metanames=ORA.common.extendArray(g.split(","))}if(!0===c.metatagAuto||"true"===c.metatagAuto)this.metatagAuto=!0;this.skip_qp_no_value=
this.skip_qp_no_value=b("skip_qp_no_value",!1);this.skip_qp_no_equals=this.skip_qp_no_equals=b("skip_qp_no_equals",!1);this.skip_qp=this.skip_qp=b("skip_qp",!1);this.paidsearchparams=b("paidsearchparams","gclid");ORA.analytics.dcsdelay=c.dcsdelay||ORA.analytics.dcsdelay;this.delayAll=this.delayAll=b("delayAll",!1);this.preserve=this.preserve=b("preserve",!0);this._onsitedoms=b("onsitedoms","");ORA.common.isFn(this._onsitedoms.test)||(this._onsitedoms=ORA.common.extendArray(this._onsitedoms.toLowerCase().split(",")),
this._onsitedoms.forEach(function(u,t,r){r[t]=u.replace(/^\s*/,"").replace(/\s*$/,"")}));b("adimpressions",!1)&&(this.adclickparam=b("adsparam","WT.ac"));this.FPCConfig.enabled=this.FPCConfig.enabled=f(c.FPCConfig,"enabled",!0);this.FPCConfig.domain=this.FPCConfig.domain=f(c.FPCConfig,"domain","");this.FPCConfig.name=this.FPCConfig.name=f(c.FPCConfig,"name","ORA_FPC");this.FPCConfig.optOutCName=this.FPCConfig.optOutCName=f(c.FPCConfig,"optOutCName","Infinity.optout");this.FPCConfig.legacyCName=this.FPCConfig.legacyCName=
f(c.FPCConfig,"legacyCName","WT_FPC");this.FPCConfig.expiry=this.FPCConfig.expiry=f(c.FPCConfig,"expires",63113851500);63113851500<this.FPCConfig.expiry&&(this.FPCConfig.expiry=63113851500);this.FPCConfig.expireDate=new Date(this.getTime()+this.FPCConfig.expiry);this.FPCConfig.sessionOnly=0===this.FPCConfig.expiry||f(c.FPCConfig,"sessionOnly",!1);this.FPCConfig.autoTLD=this.FPCConfig.autoTLD=f(c.FPCConfig,"autoTLD",!1);c.cookieTypes&&(this.FPCConfig.enabled="none"!==c.cookieTypes.toLowerCase());var q=
{DNTBehavior:ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT",wtidTimeout:this.wtidTimeout,cookie:{enable:this.FPCConfig.enabled,name:this.FPCConfig.name,expires:this.FPCConfig.expiry,autoTLD:this.FPCConfig.autoTLD,sessionOnly:this.FPCConfig.sessionOnly,expireDate:this.FPCConfig.expireDate,domain:this.FPCConfig.domain},endpoint:{clientIDServer:this.destinations[0].collectionServer,accountGuid:this.destinations[0].accountGuid,protocol:"https"}};ORA.common.clientID.clientId=
this.dcsGetFPC().id||null;ORA.common.clientID.setConfig(q);this.plugins=c.plugins||{};ORA.analytics.dcs.prototype.action_collect=ORA.analytics.dcs.prototype.action_collect;ORA.analytics.dcs.prototype.init=ORA.analytics.dcs.prototype.init;ORA.analytics.dcs.prototype.setup=ORA.analytics.dcs.prototype.setup;ORA.analytics.dcs.prototype.dcsGetFPC=ORA.analytics.dcs.prototype.dcsGetFPC;ORA.analytics.dcs.prototype.dcsGetCookie=ORA.analytics.dcs.prototype.dcsGetCookie;ORA.analytics.dcs.prototype.dcsNavigation=
ORA.analytics.dcs.prototype.dcsNavigation;this.registerProtocol();ORA.Debug.debug("dcs init() finish","ANA");return this}catch(u){throw ORA.Debug.error("Error in init() - "+u.toString()),u;}},registerProtocol:function(){var b=ORA.common.TrackingPipeline;null===b.getCommProtocol(ORA.common.CommManager.GIF)&&(ORA.common._analyticsProtocol=ORA.common.protocols.gifProtocol,b.setCommProtocol(ORA.common.CommManager.GIF,ORA.common._analyticsProtocol))},collectionEndpoint:function(b,c,d){b||ORA.Debug.debug("Warning:  missing collectServer");
b=b?b:"";if(!c)throw Error("accountGuid must be configured for "+b);return"https://"+b+"/"+c+"/"+(d?d:"dcs.gif")},setReady:function(){ORA.Debug.debug("setReady()","ANA");this._readySet||(this.flushqueue(),this.redirectqueue(),this._readySet=!0)},flushqueue:function(){ORA.Debug.trace("flushqueue()","ANA");for(var b=0;b<this.queue.length;b++)this.doAction(this.queue[b]);this.queue=[]},redirectqueue:function(){var b=this;this.queue.push=function(c){b.doAction(c)}},dcsGetCookie:function(b){return ORA.analytics.dcsGetCookie(b,
this.FPCConfig.name)},dcsIsFpcSet:function(b,c){var d=ORA.analytics.getCookieAsObj,f=ORA.analytics.isEmpty;d=d(b);this.gTempWtId=d.id;return f(d)?2:c===d.id?0:3},dcsGetFPC:function(){return ORA.analytics.getCookieAsObj(this.FPCConfig.name)},dcsFPC:function(){var b=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";if(!ORA.analytics.isOptedOut())if(this.FPCConfig.enabled){this.trackingData.ce="1";var c=this.trackingData,d=this.FPCConfig.name,f=new Date,g=6E4*f.getTimezoneOffset()+
36E5*this.timezone;f.setTime(f.getTime()+g);var q=new Date(f.getTime());c.co_f="";c.vtvs=c.vt_f="";var u=ORA.analytics.getCookieAsObj(d);g=function(r){var e=u.id;null!==e&&(c.co_f=e,f.getTime()>q.getTime()+288E5&&q.setTime(f.getTime()),"undefined"===typeof r.gTempWtId||r.gTempWtId!==e)&&(c.vt_f="1",r.gTempWtId=e)};if(!ORA.common._isDNTSet()||"honorDNT"!==b){g(this);c.co_f=escape(c.co_f);u.id=c.co_f;this.FPCConfig.sessionOnly?ORA.common.mobile.nativeAppCkSend({name:d,value:u,domain:this.FPCConfig.domain,
date:this.FPCConfig.expireDate,path:"/",type:"session",timeout:this.FPCConfig.expiry}):ORA.common.mobile.nativeAppCkSend({name:d,value:u,domain:this.FPCConfig.domain,date:this.FPCConfig.expireDate,path:"/",type:"persisted",timeout:this.FPCConfig.expiry});b=ORA.common.isFpcSet(d,c.co_f);0!==b&&(c.co_f="",c.vt_f=b);var t={};ORA.common.extendObject(c).forEach(function(r,e){null!==r&&""!==r&&(t["WT."+e]=r)});return t}}else this.trackingData.ce="0"},dcsGetIdCallback:function(b){"undefined"!==typeof b&&
(this.oraId||(this.oraId=b),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_GETID,ORA.Event.STATUS_SUCCESS)));this.setReady();ORA.analytics.productReadyLatch.countDown()},waitForGetClientIDCallback:function(){var b=ORA.common._getCookieAsObj(),c=2!==this.dcsIsFpcSet(this.FPCConfig.name),d=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";d=ORA.common._isDNTSet()&&"honorDNT"===d;return ORA.common._isOptedOut(b)||c||!this.FPCConfig.enabled||d||ORA.common._getConfigObject().s_waitForSetClientId?
!1:!0},setup:function(){try{var b=this,c=function(d){b.dcsGetIdCallback.apply(b,[d])};this.FPCConfig.enabled?ORA.common.mobile.delay(function(){b.waitForGetClientIDCallback.apply(b)?ORA.common.clientID.getClientID(c):(ORA.common.clientID.getId(ORA.common.clientID.cfg.endpoint,null),b.setReady.apply(b,[]))},"ANA",ORA.analyticsModule.prototype.oraConfigObj):this.setReady();this.enQueue("collect",{element:void 0,event:void 0});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_DCS_SETUP,ORA.Event.STATUS_SUCCESS));
ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,function(d){b.oraId=d.params},null,!0);ORA.addEventHandler(ORA.Event.CLEAR_CLIENT_ID,function(){ORA.analytics.pageAnalysis["WT.co_f"]=null},null,!0);return this}catch(d){this.errors.push(d),this.errorlogger(d)}},addQueryParameters:function(b,c){var d=this.DCS;if(0<b.length()&&!this.skip_qp){b.forEach(function(q,u){var t=q;if(!((this.skip_qp_no_value||this.skip_qp_no_equals)&&"undefined"===typeof q||this.skip_qp_no_equals&&""===q)){if("undefined"===typeof q||
null===q)t="undefined";d[u]=t}},this);var f=this.paidsearchparams.length?this.paidsearchparams.toLowerCase().split(","):[];for(var g=0;g<f.length;g++)if(ORA.common.QueryParamCache.contains(f[g],!0)){c.srch="1";break}}},dcsVar:function(){var b=this.trackingData;this.i18n&&(b.le="string"===typeof a.defaultCharset?a.defaultCharset:"string"===typeof a.characterSet?a.characterSet:"unknown");b.tv=ORA.analytics.versionStr;var c=ORA.common.QueryParamCache.getCache();this.addQueryParameters(c,b);!0===this.metatagAuto&&
ORA.common.visitMetaTags(this.dcsMetaTagsAutoScrape,a,this.DCSext);this.metanames&&ORA.common.visitMetaTags(this.dcsMetaTagArrScrape(this.metanames),a,this.DCSext)},dcsMetaTagArrScrape:function(b){return function(c,d,f){c=c.toLowerCase();-1!==b.indexOf(c)&&(f["meta_"+c]=d)}},dcsMetaTagsAutoScrape:function(b,c,d){0===b.indexOf("ORA.")?d[b]=c:0===b.indexOf("DCS.")?(b=b.split("DCS."),b[1]&&(d[b[1]]=c)):0===b.indexOf("DCSext.")&&(b=b.split("DCSext."),b[1]&&(d[b[1]]=c))},getPageAnalysis:function(){var b=
ORA.analytics.dcsRef.dcsFPC(),c=ORA.common.extendArray;ORA.analytics.pageAnalysis?c(["vt_f"]).forEach(function(d){ORA.analytics.pageAnalysis["WT."+d]&&delete ORA.analytics.pageAnalysis["WT."+d]}):ORA.analytics.pageAnalysis=ORA.analytics.dcsRef.genPageAnalysis();return ORA.paramsMerge(ORA.analytics.pageAnalysis,b)},genPageAnalysis:function(){try{if(ORA.fireEvent(new ORA.Event(ORA.Event.ANA_BEFORE_PAGE_ANALYSIS,ORA.Event.STATUS_SUCCESS)),!ORA.analytics.isOptedOut()){var b=this.trackingData,c=this.DCS,
d=this.DCSext,f=this.i18n;f&&(b.dep="");var g={},q;for(q in c)c.hasOwnProperty(q)&&void 0!==c[q]&&"function"!==typeof c[q]&&(g[q]=c[q]);for(var u in b)b.hasOwnProperty(u)&&""!==b[u]&&void 0!==b[u]&&"function"!==typeof b[u]&&(g["WT."+u]=b[u]);for(var t in d)d.hasOwnProperty(t)&&""!==d[t]&&void 0!==d[t]&&"function"!==typeof d[t]&&(f&&(b.dep=0===b.dep.length?t:b.dep+";"+t),g[t]=d[t]);f&&0<b.dep.length&&(g["WT.dep"]=b.dep);ORA.Debug.superfine("pageAnalysis: "+this.prettify(g),"ANA");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_PAGE_ANALYSIS,
ORA.Event.STATUS_SUCCESS));return g}}catch(r){ORA.Debug.error("error in pageAnalyze: "+r.toString())}},doRequest:function(){var b=this.destinations,c=this.getPageAnalysis;ORA.common.TrackingPipeline.registerMutation("analyticsAnnotate",function(d){if(d.params.mutation&&(!0===d.params.mutation.pageview||!0===d.params.mutation.conversion||!0===d.params.mutation.click||!0===d.params.mutation.collect&&!1!==d.params.sendSessionInfo||!0===d.params.mutation.view)){var f=c(),g;for(g in f)f.hasOwnProperty(g)&&
!d.getParam(g)&&d.setParam(g,f[g]);d.setParam("ora.tag_id",ORA.getTagId());d.setParam("ora.tag_config",ORA.getContextName());ORA.Debug.debug(d.params.desc?"annotating "+d.params.desc+" w/ analytics page analysis":"annotating w/ analytics page analysis","ANA");ORA.Debug.trace("annotating payload w/ "+ORA.analytics.prettify(f),"ANA");ORA.Debug.trace("Endpoints: "+ORA.analytics.prettify(b),"ANA");if("collect"!==d.params.desc)for(f=0;f<b.length;f++)d.endpoints.push({endpoint:b[f].endpoint,timeout:b[f].timeout,
conf:ORA.analytics.dcsRef,protocolType:ORA.common.CommManager.GIF});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PV_MUTATE,ORA.Event.STATUS_SUCCESS))}},1);ORA.Debug.debug("doRequest() - register mutation","ANA")},pageAnalyze:function(){ORA.Debug.trace("pageAnalyze()");this.dcsVar();this.adclickparam&&0<this.adclickparam.length&&this.dcsAdSearch();this.pageAnalyzehasRun=!0},getTime:function(){return(new Date).getTime()},dumpCounter:0,spinLock:function(b){for(var c=this.getTime();this.getTime()-c<b;)this.dumpCounter++},
enQueue:function(b,c){var d=b;ORA.Debug.debug("enQueue() - action: "+JSON.stringify(d)+" msg: "+JSON.stringify(c),"ANA");d||(d="collect");this.queue.push({action:d,message:c})},doAction:function(b){ORA.Debug.debug("doAction() - cmd: "+this.prettify(b),"ANA");var c="action_"+b.action;b=b.message;this.pageAnalyzehasRun||this.pageAnalyze();b.event&&!b.element&&(b.element=ORA.analytics.elemOfEvent(b.event,{A:1}));if(ORA.analytics.isFn(this[c]))this[c](b)},action_collect:function(b){ORA.Debug.debug("action_collect()",
"ANA");this.doRequest(b)},dcsIsOnsite:function(b,c){var d=b;if(0<d.length){d=d.toLowerCase();if(d===window.location.hostname.toLowerCase())return!0;if(ORA.analytics.isFn(c.test))return c.test(d);if(0<c.length)for(var f=c.length,g=0;g<f;g++)if(d===c[g])return!0}return!1},dcsNavigation:function(b,c){var d="",f="",g=c.length,q;for(q=0;q<g;q++){var u=c[q];if(u.length&&(f=ORA.analytics.elemOfEvent(b,u),d=f.getAttribute&&f.getAttribute("id")?f.getAttribute("id"):"",f=f.className||"",d.length||f.length))break}return d.length?
d:f},dcsAdSearch:function(){if(a.links){var b=this.adclickparam+"\x3d",c=b.length;b=new RegExp(b,"i");var d=a.links.length,f=a.URL+"",g=f.search(b);if(-1!==g){var q=f.indexOf("\x26",g);var u=-1!==q?f.substring(g,q):f.substring(g,f.length);var t=new RegExp(u+"(\x26|#)","i")}for(f=0;f<d;f++)if(a.links[f].href){var r=a.links[f].href+"";u&&0<u.length&&(r=r.replace(t,"$1"));q=r.search(b);-1!==q&&(g=q+c,q=r.indexOf("\x26",g),q=-1!==q?r.substring(g,q):r.substring(g,r.length),this.trackingData.ad=this.trackingData.ad?
this.trackingData.ad+";"+q:q)}}}};ORA.Debug.debug("dcs class loaded","ANA")})(window,window.document);
(function(l,a,b){ORA.analytics.find=function(c){ORA.analytics.selectorEngine||(ORA.analytics.selectorEngine=ORA.analytics.findSelector());return ORA.analytics.selectorEngine(c)};ORA.analytics.findSelector=function(){var c=/MSIE (\d+)/.exec(b.userAgent);c=c?c[1]:99;var d=a.body;if(a.querySelectorAll&&d&&8<c)return function(f){return d.querySelectorAll(f)};if(l.jQuery)return l.jQuery.find;if(l.Sizzle)return l.Sizzle;if(l.YAHOO&&YAHOO.util&&YAHOO.util.Selector)return YAHOO.util.Selector.query;if("qwery"in
l)return qwery;l.YUI&&YUI().use("node",function(f){return f.all});return a.querySelectorAll&&d?function(f){return d.querySelectorAll(f)}:function(){return[]}};ORA.Debug.debug("selectorEngine initialized","ANA")})(window,window.document,window.navigator);
(function(){var l={cache:[],pollId:null,playerBoundCount:0,config:{load:!1,loadMeta:!1,pause:!0,quartile:!0,beacon:!1,beaconType:"auto",seek:!0,mute:!0,beaconRate:30,pctInc:25,volume:!0,bins:15,fullscreen:!0,playerId:"div[id^\x3d'vjs_video']:not([id$\x3d'_api']):not([id*\x3d'_component'])",trackCallback:function(a){ORA.click({data:a.args})},nameCallback:null,preProcess:null,transformCallback:null,beaconCurve:{60:10,120:20,300:30,420:45,600:60,1800:150},postMessage:!1,pollRate:250,poll:!0,playerReadyTimeout:20,
maxBinds:10,mediaTags:!0},videoStates:function(){this.data={ORA:{clip_n:null,clip_id:null,clip_secs:null,clip_mins:null,clip_ct:null,clip_perc:null,clip_ev:null,clip_duration:null,clip_t:"Flash",clip_player:"Brightcove vjs",clip_vol:null,clip_res:null,clip_player_res:null,clip_duration_n:null,clip_tv:"1.0.3",clip_mode:"FixedDuration",clip_player_ver:null,player_id:null,player_playlist_id:null,clip_video_id:null,clip_accountId:null,dl:41},_state:0,_lastBeacon:0,_lastQuartile:0,_volSettle:-1,_seekSettle:-1,
_loaded:!1,_duration:null,_timer:null,_start:!1,_sentLoad:!1,_myBeaconRate:0,_isMuted:!1,player:null,_fullScreen:!1,_isValidMeta:!1,_waitMeta:!1}},playEvent:function(a,b,c){var d=this.config,f=!1;if("play"===a.data._state||!a.data._loaded||a.data._waitMeta||0<a.data._seekSettle)return!1;!a.data._isValidMeta&&b.isReady_&&this.bcCallback(a,"meta",c);"pause"===a.data._state||"stop"===a.data._state?d.pause&&(a.data.ORA.clip_ev="Resume",f=!0,a.data._state="play"):(a.data.ORA.clip_ev="Play",f=a.data._loaded=
!0,a.data._state="play",a.data._lastBeacon=0,a.data._lastQuartile=0,a.data.ORA.clip_perc="0",a.data.ORA.clip_secs=null,a.data.ORA.clip_mins=null,a.data.ORA.clip_res=b.height()+"x"+b.width(),a.data._seekSettle=55);a.data._start=!0;return f},metaEvent:function(a,b,c){var d=this.config,f=!1,g=b.mediainfo;if(void 0===g)return f;var q=b.options();b.currentType()&&(a.data.ORA.clip_ct=b.currentType());"string"===typeof b.techName_&&(a.data.ORA.clip_t=b.techName_.toUpperCase());a.data.ORA.clip_id=g.id;a.data.ORA.player_id=
q["data-player"];a.data.ORA.clip_player_ver=videojs.VERSION;a.data.ORA.player_playlist_id=q["data-playlist-id"];a.data.ORA.clip_video_id=g.id;a.data.ORA.clip_accountId=g.account_id;this.setMediaDuration(a,g);a.data._duration||(a.data.ORA.clip_mode="Stream",a.data.ORA.clip_duration=null,a.data._duration=null);a.data._myBeaconRate=d.beaconRate;this.setName(a,g,b);this.setBins(a);d.mediaTags&&void 0!==g.tags&&0<g.tags.length&&this.metaTags(a,g);a.data._fullScreen=b.isFullscreen();a.data._sentLoad?a.data._loaded=
!0:this.bcCallback(a,"load",c);a.data._isValidMeta=!0;a.data._waitMeta=!1;d.loadMeta&&(f=!0,a.data.ORA.clip_ev="Meta",a.data.ORA.dl=41);return f},setMediaDuration:function(a,b){b.duration?(a.data.ORA.clip_duration=Math.floor(100*b.duration)/100,a.data._duration=b.duration):(a.data.ORA.clip_duration=null,a.data._duration=null)},setName:function(a,b,c){var d=this.config;a.data.ORA.clip_n=void 0!==b.name?b.name:b.src?b.src.split("/")[b.src.split("/").length-1].split(".")[0]:"not provided in meta";"function"===
typeof d.nameCallback&&(a.data.ORA.clip_n=d.nameCallback(c))},setBins:function(a){var b=this.config;if(b.bins&&a.data._duration&&0<a.data._duration){var c=Math.floor((a.data._duration+b.bins)/b.bins);a.data.ORA.clip_durration_n=(c-1)*b.bins+"-"+c*b.bins}},metaTags:function(a,b){try{for(var c=[],d=0;d<b.tags.length;d++){var f=b.tags[d].split("\x3d")[0];1<b.tags[d].split("\x3d").length?a.data.ORA["clip_tag_"+f]=b.tags[d].split("\x3d")[1]:c.push(f)}0<c.length&&(a.data.ORA.clip_tags=c.join(";"))}catch(g){}},
pauseEvent:function(a,b,c,d){b=this.config;var f=!1;if(0<a.data._seekSettle)return f;if(97<a.data.ORA.clip_perc)this.bcCallback(a,"complete",c);else{if(!a.data._loaded||!a.data._start||"start"===a.data._state&&"begin"===a.data._state)return f;b.pause&&(f=!0);a.data._state=d;a.data.ORA.clip_ev="Pause"}return f},completeEvent:function(a,b,c,d){b=!1;a.data._state=d;this.bcCallback(a,"timeupdate",c);"Complete"!==a.data.ORA.clip_ev&&(b=!0);a.data.ORA.clip_ev="Complete";a.data._start=!1;a.data.ORA.clip_perc=
100;a.data._loaded=!1;a.data._isValidMeta=!1;return b},errorEvent:function(a,b){a.data.ORA.clip_ev="Error ";a.data.ORA.clip_ev+=b.error_.type;return!0},progressEvent:function(a,b,c){var d=this.config,f=b.currentTime(),g=!1;0<a.data._seekSettle&&--a.data._seekSettle;5<Math.abs(Math.floor(100*f)/100-a.data.ORA.clip_secs)&&"complete"!==a.data._state&&this.bcCallback(a,"seek",c);a.data.ORA.clip_secs=Math.floor(f);a.data.ORA.clip_mins=Math.floor(f/60*100)/100;if(d.quartile&&this.processQuartile(a)||this.processBeacon(a,
f))return!0;0<=a.data._volSettle&&--a.data._volSettle;g=this.checkEnded(a,b,c,g);this.setBins(a);this.isMuted(a,b,c);this.isPaused(a,b,c);this.setScreen(a,b,c);this.setVolume(a,b);return g},isPaused:function(a,b,c){a.data._start||b.paused()||this.bcCallback(a,"play",c)},isMuted:function(a,b,c){b.muted()!==a.data._isMuted&&this.bcCallback(a,"mute",c)},checkEnded:function(a,b,c,d,f){b=f;"ended"===a.data._state&&(a.data.ORA.clip_ev="complete",a.data.ORA.clip_secs="0",a.data.ORA.clip_mins="0",a.data.ORA.clip_perc=
null,b=!1,a.data._state="ended");return b},setVolume:function(a,b){void 0!==b.volume()&&(b.volume()===isNaN?a.data.ORA.clip_vol=100:a.data.ORA.clip_vol=Math.floor(1E3*b.volume())/10)},setScreen:function(a,b,c){a.data._fullScreen!==b.isFullscreen()&&0<b.readyState()&&(a.data._fullScreen=b.isFullscreen(),b.isFullscreen()?this.bcCallback(a,"fullscreen",c):this.bcCallback(a,"fullscreenexit",c))},processQuartile:function(a){var b=this.config;if(a.data.ORA.clip_perc>=a.data._lastQuartile+b.pctInc)return a.data.ORA.clip_perc=
Math.floor(a.data.ORA.clip_perc/b.pctInc)*b.pctInc,a.data._lastQuartile=a.data.ORA.clip_perc,a.data.ORA.clip_ev="Quartile",!0;"complete"===a.data._state&&100!==a.data._lastQuartile?(a.data.ORA.clip_perc=100,a.data._lastQuartile=a.data.ORA.clip_perc,a.data.ORA.clip_ev="Quartile",a=!0):a=!1;return a},beaconCurve:function(a){var b=this.config,c;for(c in b.beaconCurve)if(b.beaconCurve.hasOwnProperty(c)&&a<=c)return b.beaconCurve[c];return null},processBeacon:function(a,b){var c=this.config,d=!1,f=null!==
a.data.ORA.clip_mode&&"stream"===a.data.ORA.clip_mode.toLowerCase(),g=this.beaconCurve(b);try{("auto"===c.beaconType.toLowerCase()&&f||"curve"===c.beaconType)&&null!==beaconCurve?(0===b&&(a.data._lastBeacon=0),a.data._myBeaconRate=g):a.data._myBeaconRate=c.beaconRate}catch(q){a.data._myBeaconRate=c.beaconRate}b>a.data._lastBeacon+a.data._myBeaconRate&&c.beacon&&(a.data.ORA.clip_ev="Beacon",d=!0,a.data._lastBeacon+=a.data._myBeaconRate);return d},seekedEvent:function(a,b,c,d){c=this.config;b=b.currentTime();
var f=!1;a.data._lastBeacon=b;"ended"!==a.data._state&&c.seek&&0===a.data._seekSettle&&0!==b&&(a.data.ORA.clip_ev="Seek",f=!0,a.data._seekSettle=20);a.data._state=d;return f},cancelseekEvent:function(a){a.data._seekSettle=-1;return!1},fullscreenEvent:function(a,b){var c=!1;this.config.fullscreen&&b.isFullscreen()&&(a.data.ORA.clip_ev="Fullscreen",c=!0);return c},loadstartEvent:function(a){var b=!1;this.config.load&&(b=a.data._sentLoad=!1);return b},loadEvent:function(a){var b=!1;this.config.load&&
!a.data._sentLoad&&(a.data.ORA.clip_ev="Load",b=!0);a.data._sentLoad=!0;a.data._loaded=!0;return b},fullscreenexitEvent:function(a,b){var c=!1;this.config.fullscreen&&!b.isFullscreen()&&(a.data.ORA.clip_ev="Fullscreenexit",c=!0);return c},muteEvent:function(a,b){var c=!1;this.config.mute&&(b.muted()?(a.data.ORA.clip_ev="Muted",a.data._isMuted=!0):(a.data.ORA.clip_ev="UnMuted",a.data._isMuted=!1),a.data._isMuted=b.muted(),c=!0);return c},volumechangeEvent:function(a,b){var c=!1;!this.config.volume||
-1!==a.data._volSettle||a.data._isMuted||b.muted()||(a.data.ORA.clip_vol=Math.floor(1E3*b.volume())/10,a.data._volSettle=20,a.data.ORA.clip_ev="Volume",c=!0);return c},bcCallback:function(a,b,c){var d=document.getElementById(c),f=window.videojs(c).player(),g=!1,q=f.currentTime();window.ORA&&ORA.Debug&&"progress"!==b&&"timeupdate"!==b&&ORA.Debug.debug("video_bc Plugin event "+b,"ANA");a.data.ORA.clip_perc=q&&a.data._duration&&0<a.data._duration?Math.floor(q/a.data._duration*1E4)/100:null;a.data.ORA.dl=
40;this.loadedmetadataEvent=this.metaEvent;this.endEvent=this.completeEvent;this.timeupdateEvent=this.progressEvent;this.seekEvent=this.seekedEvent;"undefined"!==typeof this[b+"Event"]&&(g=this[b+"Event"](a,f,c,b,g));g&&this.sendTrackEvent(a,d)},sendTrackEvent:function(a,b){var c=this.config;window.ORA&&ORA.Debug.info("video_bc queueing data for "+a.data.ORA.clip_n+" : "+a.data.ORA.clip_ev,"ANA");var d={},f;for(f in a.data.ORA)a.data.ORA.hasOwnProperty(f)&&this.setTagParm(a,f,d);this.cache.push({element:this,
args:d,transform:c.transformCallback,data:a.data.ORA,videoEle:b});if("function"===typeof c.trackCallback)try{c.trackCallback(this.cache.pop())}catch(g){window.ORA&&ORA.Debug.info("video_bc Error with trackCallback","ANA")}},setTagParm:function(a,b,c){"number"===typeof a.data.ORA[b]?("clip_secs"===b||"clip_perc"===b||"clip_mins"===b)&&0===a.data.ORA[b]||isNaN(a.data.ORA[b])?delete c["WT."+b]:c["WT."+b]=a.data.ORA[b].toString():null===a.data.ORA[b]?delete c["WT."+b]:c["WT."+b]=a.data.ORA[b]},bindPlayer:function(a){var b=
"pause play end mute complete loadstart loadeddata resize progress seeked error meta timeupdate cancelseek volumechange loadedmetadata".split(" ");if(l.playerBoundCount>this.config.maxBinds)window.ORA&&ORA.Debug.info("video_bc max binds reached","ANA");else try{window.videojs(a).ready(function(){var c=new l.videoStates,d=this,f=l.config;c.data.player=this;b.forEach(function(g){(function(){this.config=f;d.on(g,function(){l.bcCallback(c,g,a)})}).apply(this,[g,a,c,d,f])});window.videojs(a).isReady_&&
l.bcCallback(c,"meta",a);window.ORA&&ORA.Debug.info("video_bc Plugin bound to player "+a,"ANA")})}catch(c){window.ORA&&ORA.Debug.info("video_bc Plugin error binding to player "+a,"ANA")}l.playerBoundCount++},waitForPlayer:function(a){var b=this,c=a;setTimeout(function(){void 0!==window.videojs&&0<document.querySelectorAll(l.config.playerId+':not([data-wt\x3d"wtBound"])').length?b.lookForPlayers():"infinite"===c||0<c?(isNaN(c)||c--,b.waitForPlayer(c)):window.ORA&&ORA.Debug.info("video_bc Plugin time out waiting for player",
"ANA")},500)},pollPlayer:function(a){var b=this;this.pollId=setInterval(function(){b.lookForPlayers()},a)},reset:function(){if(this.pollId){clearInterval(this.pollId);var a=document.querySelectorAll(l.config.playerId);if(0<a.length)for(var b=0;b<a.length;b++)a[b].setAttribute("data-wtbc","")}},lookForPlayers:function(){try{var a=document.querySelectorAll(this.config.playerId)}catch(c){window.ORA&&ORA.Debug.info("video_bc Plugin error with selector "+this.config.playerId,"ANA")}if(void 0!==window.videojs&&
0<document.querySelectorAll(this.config.playerId+":not([data-wtbc\x3d'Bound'])").length)for(var b=0;b<a.length;b++)this.bindPlayer(a[b].id),a[b].setAttribute("data-wtbc","Bound"),window.ORA&&ORA.Debug.info("video_bc Plugin binding to player "+a[b].id,"ANA")},bcInit:function(a){a=a.config||{};this.bcInfo("video_bc Plugin init start");if(void 0===a.enable||a.enable){var b=ORA.common._getIEVer();if(b&&11>=b)this.bcInfo("video_bc Plugin requires \x3e ie11, disabling plugin");else{for(var c in this.config)this.config.hasOwnProperty(c)&&
void 0!==a[c]&&(this.config[c]=a[c]);this.reset();this.config.poll?this.pollPlayer(this.config.pollRate):(this.lookForPlayers(),this.waitForPlayer(this.config.playerReadyTimeout));this.bcInfo("video_bc Plugin init complete")}}else this.bcInfo("video_bc Plugin is disabled")},bcInfo:function(a){window.ORA&&ORA.Debug.info(a,"ANA")},init:function(a){l.bcInit(a)}};window.ORA&&ORA.regPlugin&&(ORA.regPlugin("bc",l.init),window.ORA.Debug.info("video_html5 Plugin registration request","ANA"),ORA.analytics.plugins||
(ORA.analytics.plugins={}),ORA.analytics.plugins.bcVideo=l)})();
(function(){var l,a,b,c,d={enable:!0,cookieDays:365,cookieName:"ORAPERSIST",cookieDomain:"",params:"dcsvid infy riid rid customer_id elqCID elq_cid elq_mid product".split(" "),defPrefix:"DCSext",priority:100,useMostRecent:!0,lowerCaseValues:!0},f=new function(){var t=this;t.getQueryParamsMap=function(r,e){var m=ORA.common.extendObject({}),v=[],k=r,p=e||d;try{m=JSON.parse(r)}catch(w){"string"===typeof k&&(k=k.replace(/^[&\?\s]+/i,""),v=k.split("\x26"));for(var h=0,n=v.length;h<n;++h){k=v[h];k=k.split("\x3d");
var x=k[0].toLowerCase();""!==x&&(m[x]=p.lowerCaseValues?decodeURIComponent(k[1].toLowerCase()):decodeURIComponent(k[1]))}}return m};t.getValueOfExistingParam=function(r,e,m,v,k){var p=null,h,n=k||d;r.forEach(function(x,w){if(w.toLowerCase()===m||w.toLowerCase()===e)h=n.lowerCaseValues&&"string"===typeof x?x.toLowerCase():x});h?(p=h,ORA.Debug.debug("Taking current value from QRY: "+m+'\x3d"'+p+'"',"ANA - pp")):null!==v.getParam(m)&&(p=v.getParam(m),ORA.Debug.debug("Taking current value from dcsMsg: "+
m+'\x3d"'+p+'"',"ANA - pp"));p&&ORA.Debug.debug("Param (current value): "+m+'\x3d"'+p+'"',"ANA - pp");return p};t.getParamValue=function(r,e,m,v,k){r=t.getValueOfExistingParam(r,e,m,v);m=t.getQueryParam(k,m);null===r||"undefined"===r||!d.useMostRecent&&null!==m||(m=r);return m};t.getQueryParam=function(r,e){var m=null;r.forEach(function(v,k){k.toLowerCase()===e&&(m=v)});return m};t.applyPreviouslyPersistedParamsValues=function(r,e,m){for(var v="",k=ORA.common.extendObject({}),p=0,h=d.params.length;p<
h;++p){var n=d.params[p],x=n;ORA.Debug.info("Processing param: "+n,"ANA - pp");e[n]=t.getParamValue(r,n,x,m,e);var w=t.getQueryParam(e,n);w&&(ORA.Debug.info("Overriding MSG value with saved value: "+x+'\x3d"'+w+'"',"ANA - pp"),m.setParam(x,w,!0),k[x]=w);(x=t.getQueryParam(r,n)||t.getQueryParam(r,x))&&ORA.common.QueryParamCache.set(n,x)}k.forEach(function(y,z){v=v+"\x26"+z+"\x3d"+encodeURIComponent(y)});return v=v.replace(/^[&\?\s]+/i,"")};t.arrayIndexOf=function(r,e){if(!ORA.analytics.isArray(r))return-1;
if(Array.prototype.indexOf)return r.indexOf(e);for(var m=0,v=r.length;m<v;m++)if(r[m]===e)return m;return-1}},g=function(){this.getCookieDomain=function(){var t="",r=d.cookieDomain;r==location.hostname&&(r="");b&&b.FPCConfig&&b.FPCConfig.domain&&(t=b.FPCConfig.domain);ORA.Debug.debug("sDCSDomain: "+t,"ANA - pp");r&&"."===r.charAt(0)&&(r=r.slice(1));if(d.cookieDomain)return ORA.Debug.debug("PP config domain: "+t,"ANA - pp"),r;if(b&&b.FPCConfig&&!0===b.FPCConfig.autoTLD)return ORA.Debug.debug("Using TLD Domain: "+
ORA.cookieMgr.checkCookieOnDomainAndGetTLDomain(),"ANA - pp"),ORA.cookieMgr.checkCookieOnDomainAndGetTLDomain();if(t)return ORA.Debug.debug("Tag config domain: "+t,"ANA - pp"),t}},q=function(){this.savePersistedParams=function(t,r,e,m){var v=new Date;v.setDate(v.getDate()+m);m=";domain\x3d"+e+";path\x3d/;expires\x3d"+v.toUTCString();e||(m=";path\x3d/;expires\x3d"+v.toUTCString());l(t,r,m)};this.getPersistedParams=function(t){var r=ORA.common.extendObject({});t=a(t);return null===t?r:r=f.getQueryParamsMap(t)}};
var u=new function(){var t=this,r=new g,e=new q;t.ppMutation=function(m){var v=ORA.common.QueryParamCache.getCache(),k=e.getPersistedParams(d.cookieName);ORA.Debug.debug("QRY params: "+JSON.stringify(v),"ANA - pp");m=f.applyPreviouslyPersistedParamsValues(v,k,m);c||(c=r.getCookieDomain(),ORA.Debug.debug("Cookie domain to use: "+c,"ANA - pp"));ORA.Debug.debug("Saving persistent params in cookie: "+d.cookieName+'\x3d"'+m+'"',"ANA - pp");e.savePersistedParams(d.cookieName,m,c,d.cookieDays)};t.ppInit=
function(m,v){var k=m.config;if(k){for(var p in k)k.hasOwnProperty(p)&&(d[p]=k[p]);k=[];p=0;for(var h=d.params.length;p<h;++p)d.params[p]=d.params[p].toLowerCase(),k.push(d.params[p]);d.params=k}ORA.Debug.info("initializing...","ANA - pp");d.enable?d.params&&0!==d.params.length?(ORA.Debug.debug("params to persist: "+d.params.join(", "),"ANA - pp"),l=ORA.analytics.setCookie,a=ORA.analytics.getCookieRaw,b=ORA.analytics.dcsRef,ORA.analytics.addMutation("persistParams",t.ppMutation,3)):ORA.Debug.debug("no persist params defined - will not run",
"ANA - pp"):ORA.Debug.debug("disabled in config - will not run","ANA - pp");d.blockCollect&&v&&v()}};ORA.regPlugin("pp",u.ppInit);ORA.plugins||(ORA.plugins={});ORA.plugins.pp||(ORA.plugins.pp={});ORA.Debug.debug("PP: Plugin initialized","ANA - pp");ORA.plugins.pp.Domain=new g;ORA.plugins.pp.PersistParams=new q;ORA.plugins.pp.OraclePP=u;ORA.plugins.pp.helper=f;ORA.plugins.pp.config=d})();ORA.Debug.debug("PP: Loading Plugin","ANA");
(function(){var l={cfg:{standardEvents:{download:!1,offsite:!1,onsite:!1,rightclick:!1,anchor:!1,javascript:!1,scrollTracking:!1},scroll_frequency:25,eventList:{},downloadtypes:"xls,doc,pdf,txt,csv,zip,docx,xlsx,rar,gzip",socialTypes:{},trackSocial:!0},init:function(a,b){var c=a.config||{},d=b||function(){};ORA.Debug.debug("Event Track plugin Start Init","ANA-ET");try{for(var f in c)c.hasOwnProperty(f)&&(l.cfg[f]=c[f]);if(void 0!==l.cfg.enable&&!l.cfg.enable)return ORA.Debug.debug("Event Track plugin is disabled - exiting",
"ANA-ET"),d();var g=ORA.getIEVer();if(g&&9>g)return ORA.Debug.info("requires \x3e\x3d ie9, disabling plugin","ANA-ET"),d();ORA.Debug.info("Adding standard events","ANA-ET");l._addStandardEvents();if(!document.querySelectorAll)return ORA.Debug.info("Event Track plugin requires querySelectorAll function","ANA-ET"),d(),!1;l._addMatches();ORA.Debug.info("Binding to objects","ANA-ET");l._bind()}catch(q){ORA.Debug.error("Event Track plugin Init Error"+q.message,"ANA-ET"),d()}d();ORA.Debug.debug("Event Track plugin Start Init Complete",
"ANA-ET")},_getFullUrl:function(a){if("A"===a.nodeName){var b=a.cloneNode(!0);b.href=a.href;return b}return a},_eventCallback:function(a,b){try{for(var c=a.eventTrigger&&a.eventTrigger.split(" ")||["mousedown"],d=function(g,q,u){u._evtMsg(g);try{var t=u._fnCreator(a.eventCallback)(g,q);u._isEmptyObj(t)||(ORA.collect({config:{endpoints:[{endpoint:ORA.analytics.getEndPoint(),protocolType:"beaconProtocol"}],applyMutations:!0},data:t.data}),u._fnCreator(a.fnFinishCallback)(g))}catch(r){ORA.Debug.error("Event Track error in event callback: "+
r.message,"ANA-ET")}},f=0;f<c.length;f++)"immediate"!==c[f].toLowerCase()?(ORA.Debug.info("Event Track for "+b+" bind to "+a.selector+" event: "+c[f],"ANA"),this._delegate(document,c[f].toLowerCase(),a.selector,d,a,this)):(ORA.Debug.info("Event Track Immediate: "+b,"ANA"),d(null,null,this))}catch(g){ORA.Debug.error("Error binding adding selector for: "+b+" err: "+g.message,"ANA-ET")}},_delegate:function(a,b,c,d,f,g){function q(t){return function(r,e,m){var v=r.target||r.srcElement,k=v;"scroll"===
r.type&&d.call(null,r,e,m);for("A"===v.nodeName&&v.href&&(k=l._getFullUrl(v));k&&k!==document;)k.matches(c)&&d.call(k,r,e,m),k=k.parentNode}.apply(this,[t,f,g])}if(a.addEventListener)a.addEventListener(b,function(t){q(t)});else{var u=b;"click"===b&&(u="mousedown");a.attachEvent("on"+u,function(t){q(t)})}},_bind:function(){var a=this.cfg.eventList,b;for(b in a)a.hasOwnProperty(b)&&this._eventCallback(a[b],b)},_evtMsg:function(a){if(a){var b="Event Triggered:"+a.type+" node:"+(a.srcElement||a.target).nodeName+
" #";b+=(a.srcElement||a.target).id+" class:"+(a.srcElement||a.target).className;ORA.Debug.info(b,"ANA-ET")}else ORA.Debug.info("Event Triggered for immediate event","ANA-ET")},_fnCreator:function(a){return"string"===typeof a?new Function("e",a):"function"===typeof a?a:function(){}},_addMatches:function(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||
Element.prototype.oMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector||function(a){a=(this.document||this.ownerDocument).querySelectorAll(a);var b=a.length;for(--b;0<=b&&a.item(b)!==this;)--b;return-1<b})},_isRightClick:function(a){a=a||window.event;if(a.which)a=3===a.which;else if(a.button)a=2===a.button;else return!1;return a},_getHrefInfo:function(a){a=a.target||a.srcElement||{};var b={},c=a,d=document.createElement("a");a=this._findA(a);
if(!a.href)return{};d.href=a.href;b.dcssip=d.hostname?d.hostname.split(":")[0]:window.location.hostname;d.pathname&&0!==d.pathname.indexOf("/")?b.dcsuri="/"+d.pathname:b.dcsuri=d.pathname?d.pathname:"/";d.search&&(b.dcsqry=d.search.substring(d.search.indexOf("?")+1,d.search.length));b.dcsref=document.referrer;b["WT.nv"]=ORA.common.getObjId(c);b["WT.dl"]="24";return this._cleanPayload(b)},_cleanPayload:function(a){for(var b in a)a.hasOwnProperty(b)&&!a[b]&&delete a[b];return a},_findA:function(a){for(;a&&
"A"!==a.nodeName;)a=a.parentNode;return a},_checkOnsiteDom:function(a,b){var c=ORA.analytics.dcsRef._onsitedoms;c.test||(1===c.length&&""===c[0]&&(c=[location.host.split(":")[0]]),c=new RegExp(c.join(",").toLowerCase().replace(",","|").replace(/^\s*/,"").replace(/\s*$/,"")));return!(l._isRightClick(b)||!c.test(a.hostname))},_isEmptyObj:function(a){if("object"!==typeof a)return!0;for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},_addStandardEvents:function(){var a={download:"_addDownloadTracking",
offsite:"_addOffsiteTracking",onsite:"_addOnsiteLinkTracking",anchor:"_addAnchorTracking",rightclick:"_addRightClickTracking",javascript:"_addJavaScriptTracking",scrollTracking:"_addScrollTracking"},b;for(b in this.cfg.standardEvents)if(this.cfg.standardEvents.hasOwnProperty(b)&&this.cfg.standardEvents[b])this[a[b]]()},_addDownloadTracking:function(){ORA.Debug.info("Event Track plugin Add download tracking","ANA-ET");for(var a=[],b=l.cfg.downloadtypes.toLowerCase().split(","),c=0;c<b.length;c++)a.push('A[href*\x3d".'+
b[c]+'" i]');l.cfg.eventList.download={eventTrigger:"click",selector:a.join(","),eventCallback:function(d){var f=d.target||d.srcElement||d.target||{},g=l._getHrefInfo(d);ORA.Debug.debug("Download Callback Called");if(l._isRightClick(d)||!g)return{};g["WT.ti"]="Download:"+f.textContent||f.innerText;g["WT.dl"]="20";return{data:g}}}},testSocial:function(a,b,c){for(var d=0;d<a[b].length;d++)if(-1<c.toLowerCase().indexOf(a[b][d].toLowerCase()))return!0;return!1},isSocial:function(a){var b=l.cfg.socialTypes,
c;for(c in b)if(b.hasOwnProperty(c)&&l.testSocial(b,c,a))return c;return null},_addOnsiteLinkTracking:function(){ORA.Debug.info("Event Track plugin add onsite link tracking","ANA-ET");for(var a=l.cfg.downloadtypes.toLowerCase().split(","),b=':not([href*\x3d"javascript:"])',c=0;c<a.length;c++)b+=':not([href*\x3d".'+a[c]+'" i])';a=['A:not([href^\x3d"//"])'+b];c=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(c=ORA.analytics.dcsRef._onsitedoms);if(!c.test){if(""===c||0===
c[0].length)c=[location.hostname];for(var d=0;d<c.length;d++)a.push('A[href*\x3d"'+c[d]+'"]'+b)}l.cfg.eventList.onsite={eventTrigger:"click",selector:a.join(","),eventCallback:function(f){var g=f.target||f.srcElement||{},q=l._getHrefInfo(f);ORA.Debug.debug("Onsite Link Callback Called");if(l._isEmptyObj(q))return{};for(;g&&"A"!==g.nodeName;)g=g.parentNode;if(!l._checkOnsiteDom(g,f))return ORA.Debug.debug("Onsite Link Callback Called - fails onsite test. Exiting"),{};q["WT.ti"]="Onsite:"+q.dcssip+
q.dcsuri;q.dcsqry&&(q["WT.ti"]+=q.dcsqry);q["WT.dl"]="1";return{data:q}}}},_addOffsiteTracking:function(){ORA.Debug.info("Event Track plugin add offsite tracking","ANA-ET");var a=['A:not(A[href*\x3d"javascript:"])'],b=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(b=ORA.analytics.dcsRef._onsitedoms);if(!b.test){a=[];""===b&&(b=[location.host]);for(var c=0;c<b.length;c++)a.push('A:not([href*\x3d"'+b[c]+'"]):not([href*\x3d"javascript:"])')}l.cfg.eventList.offsite={eventTrigger:"click",
selector:a.join(","),eventCallback:function(d){var f=d.target||d.srcElement||{},g=l._getHrefInfo(d);ORA.Debug.debug("Offsite Callback Called");if(l._isEmptyObj(g))return{};for(;f&&"A"!==f.nodeName;)f=f.parentNode;var q=l.isSocial(f.href);q&&l.cfg.trackSocial&&(g["WT.soc_action"]=q+":click");if(l._checkOnsiteDom(f,d))return ORA.Debug.debug("Offsite Callback Called - fails offsite test exiting"),{};g["WT.ti"]="Offsite:"+g.dcssip+g.dcsuri;g.dcsqry&&(g["WT.ti"]+=g.dcsqry);g["WT.dl"]="24";return{data:g}}}},
_addRightClickTracking:function(){ORA.Debug.info("Event Track plugin add right click tracking","ANA-ET");for(var a=[],b=l.cfg.downloadtypes.toLowerCase().split(","),c=0;c<b.length;c++)a.push('A[href*\x3d".'+b[c]+'" i]');l.cfg.eventList.rightClick={eventTrigger:"mousedown",selector:a.join(","),eventCallback:function(d){ORA.Debug.debug("Rightclick Callback Called");if(!l._isRightClick(d)&&!l.cfg.testRightClick)return ORA.Debug.debug("RightClick Callback Called - exiting fails rightclick test"),{};var f=
d.element||d.srcElement||d.target||{};d=l._getHrefInfo(d);if(!d)return{};d["WT.ti"]="RightClick:"+f.textContent||f.innerText;d["WT.dl"]="25";return{data:d}}}},_addJavaScriptTracking:function(){ORA.Debug.info("Event Track plugin add javascript tracking","ANA-ET");l.cfg.eventList.javaScript={eventTrigger:"click",selector:'A[href*\x3d"javascript:"]',eventCallback:function(a){var b=a.element||a.srcElement||a.target||{};a=l._getHrefInfo(a);if(l._isEmptyObj(a))return{};ORA.Debug.debug("JavaScript Callback Called");
a["WT.ti"]=b.innerHTML?"JavaScript:"+b.innerHTML:"JavaScript:";a["WT.dl"]="22";a.dcssip=window.location.hostname;a.dcsuri=b.href;return{data:a}}}},_addAnchorTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking","ANA-ET");var a=window.location.pathname.split("/").pop();l.cfg.eventList.anchorTracking={eventTrigger:"click",selector:'A[href^\x3d"#"],A[href*\x3d"'+a+'#"]',eventCallback:function(b,c){var d=b.target||b.srcElement||{},f=l._getHrefInfo(b);if(l._isEmptyObj(f))return{};
for(ORA.Debug.debug("Anchor Callback Called");d&&"A"!==d.nodeName;)d=d.parentNode;if(!l._checkOnsiteDom(d,b)||!c.hasHash(d))return ORA.Debug.debug("Anchor Callback Called - no Hash address found, or offsite link - exiting hash:"+d.hash,"ANA-ET"),{};f["WT.ti"]="Anchor:"+(d.hash||"#");f["WT.dl"]="21";c.checkFragment(d);return{data:f}},hasHash:function(b){return b.hash&&-1<b.hash.indexOf("#")},checkFragment:function(b){ORA.analytics.plugins&&ORA.analytics.plugins.fragment&&ORA.analytics.plugins.fragment.updateFragData&&
ORA.analytics.plugins.fragment.updateFragData(b.hash)}}},_isMissingSent:!1,_getScrollPayload:function(a,b){return{"WT.page_scroll_depth":100<a*b?100:a*b,"WT.dl":"71"}},_addScrollTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking","ANA-ET");l.cfg.eventList.scrollTracking={selector:"",eventTrigger:"scroll",eventCallback:function(){var a=l.cfg.scroll_frequency,b=ORA.common.scrollEventCallback(a);window.evtScrollTracker||(window.evtScrollTracker={});if(!window.evtScrollTracker[b]){window.evtScrollTracker[b]=
!0;if(!l._isMissingSent){l._isMissingSent=!0;for(var c=1;c<b;c++)window.evtScrollTracker.hasOwnProperty(c)||(window.evtScrollTracker[c]=!0,ORA.collect({config:{endpoints:[{endpoint:ORA.analytics.getEndPoint(),protocolType:"beaconProtocol"}],applyMutations:!0},data:l._getScrollPayload(c,a)}))}return{data:l._getScrollPayload(b,a)}}return{}}}},addTracking:function(a,b){"object"===typeof a&&"string"===typeof b?l._eventCallback(a,b):ORA.Debug.debug("Ignoring addTrack call - obj or trigger type error",
"ANA-ET")}};ORA.regPlugin("evtTrack",l.init);ORA.analytics.plugins.evtTrack||(ORA.analytics.plugins.evtTrack={});ORA.analytics.plugins.evtTrack.addTracking=l.addTracking;ORA.analytics.plugins.evtTrack.eventTrack=l})();
(function(){function l(){if(this.href){var h=this.href;if(k.hasOwnProperty("addHash")||k.hasOwnProperty("addParam")||k.hasOwnProperty("autoSelect")){var n=h;if(k.autoSelect||k.addHash)n=a(n);if(k.autoSelect&&n===h||!k.autoSelect&&k.addParam)n=b(n);h=n}else if("parameter"!==k.addIdTreatment&&(h=a(this.href)),"auto"===k.addIdTreatment&&h===this.href||"parameter"===k.addIdTreatment)h=b(this.href);this.href=h}}function a(h){var n=m()||{};if(h&&-1<h.indexOf("#")||!n.id||!k.guard)return h;k.encode&&window.btoa&&
(n.id=btoa(n.id));ORA.Debug.debug("Adding hash to href: "+h+"#xd_co_f\x3d"+n.id+k.guard,"crossDomain-ANA");return h+"#xd_co_f\x3d"+n.id+k.guard}function b(h){var n=m();if(!h||n&&!n.id||!k.guard)return h;k.encode&&window.btoa&&(n.id=btoa(n.id));ORA.Debug.debug("Adding parameters to href: "+h+"?xd_co_f\x3d"+n.id+k.guard,"crossDomain-ANA");a:{n="xd_co_f\x3d"+n.id;var x=h.replace(RegExp("(\x26|\\?)xd_co_f\x3d[^\x26|#]*"),"$1"+n);if(h&&-1===h.indexOf("xd_co_f\x3d"))if(-1!==h.indexOf("?")){h=-1!==h.indexOf("#")?
-1!==h.split("#")[0].indexOf("?")?h.split("?")[0]+"?"+n+"\x26"+h.split("?")[1]:h.split("#")[0]+"?"+n+"#"+h.split("#")[1]:h.split("?")[0]+"?"+n+"\x26"+h.split("?")[1];break a}else x=-1!==h.indexOf("#")?h.split("#")[0]+"?"+n+"#"+h.split("#")[1]:h+"?"+n;h=x}return h}function c(h){var n=/[^A-Z0-9+\/=]/i,x=h.length;if(!x||0!==x%4||n.test(h))return!1;n=h.indexOf("\x3d");return-1===n||n===x-1||n===x-2&&"\x3d"===h[x-1]}function d(h,n){var x=h.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),w;(x=(new RegExp("[\\?\x26]"+
x+"\x3d([^\x26#]*)")).exec(n||location.search))&&(w=decodeURIComponent(x[1].replace(/\+/g," ")))&&c(w)&&window.atob&&(w=atob(w));return w}function f(h,n){var x,w=h.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");(w=(new RegExp("[#]"+w+"\x3d(.*)"+k.guard)).exec(n||location.hash))&&(x=decodeURIComponent(w[1].replace(/\+/g," ")))&&c(x)&&window.atob&&(x=atob(x));return x}function g(h,n,x,w){function y(A){return function(D){for(var C=D.target;C&&C!==document;){var B=C;if("A"===B.nodeName){var E=B.cloneNode(!0);
E.href=B.href;B=E}if(!B.matches)break;if(B.matches(n))break;if(B.matches(h)){w.call(C,D);break}C=C.parentNode}}.apply(this,[A])}if(document.addEventListener)document.addEventListener(x,y);else{var z=x;"click"===x&&(z="mousedown");document.attachEvent("on"+z,y)}}function q(h){if(v&&h.payload["wt.co_f"]!==v){ORA.Debug.debug("Resessionizing from "+h.payload["wt.co_f"]+"to"+v,"crossDomain-ANA");h.payload["wt.co_f"]=v;h=m();h.id=v;var n=ORA.analytics.dcsRef,x=n.FPCConfig.expireDate||new Date((new Date).getTime()+
63113851500),w="";n.FPCConfig.sessionOnly||(w="; expires\x3d"+x.toGMTString());ORA.analytics.setCookie(n.FPCConfig.name||"ORA_FPC",{id:h.id},""===n.FPCConfig.domain?w+"; path\x3d/":w+"; path\x3d/; domain\x3d"+n.FPCConfig.domain)}ORA.analytics.rmMutation("crossDomain")}function u(h){for(var n in h)h.hasOwnProperty(n)&&(k[n]=h[n]);return k}function t(h){var n=[location.hostname],x=['A[href*\x3d"'+location.hostname+'"]'];!k.ignoreOnsiteDoms&&ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&!n.test&&
""!==ORA.analytics.dcsRef._onsitedoms[0]&&(n=ORA.analytics.dcsRef._onsitedoms);if(n.test)ORA.Debug.debug("crossDomain does not support using regex for onsitedom list - using localhost","crossDomain-ANA");else{x=[];""===n&&(n=[location.host]);for(var w=0;w<n.length;w++)x.push('A[href*\x3d"'+n[w]+'/"]')}x.push('A[href*\x3d"javascript:"],A[href*\x3d"mailto:"],A[href*\x3d"tel:"],A[href*\x3d"sms:"]');n=x.join(",");"localhost"!==h&&(n=n.concat(",",h));ORA.Debug.debug("CrossDomain using deny list: "+n,"crossDomain-ANA");
return n}function r(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||function(h){h=(this.document||this.ownerDocument).querySelectorAll(h);var n=h.length;for(--n;0<=n&&h.item(n)!==this;)--n;return-1<n})}
function e(){if(!k.enable)return ORA.Debug.info("crossDomain Plugin is disabled","crossDomain-ANA"),!0;if(k.hasOwnProperty("addHash")||k.hasOwnProperty("addParam")||k.hasOwnProperty("autoSelect")){if(!(k.autoSelect||k.addHash||k.addParam))return ORA.Debug.info("Plugin config invalid: Must specify at least one way of adding visitor`s ID","crossDomain-ANA"),!0}else if("auto"!==k.addIdTreatment&&"hash"!==k.addIdTreatment&&"parameter"!==k.addIdTreatment)return ORA.Debug.info("Plugin config invalid: Must specify at least one way of adding visitor`s ID",
"crossDomain-ANA"),!0;var h=ORA.getIEVer();return h&&9>h?(ORA.Debug.info("Browser is not compatible, requires IE9+","crossDomain-ANA"),!0):!1}function m(){var h=ORA.analytics.dcsRef,n="ORA_FPC";h&&h.FPCConfig&&h.FPCConfig.name&&(n=h.FPCConfig.name);var x={};h=RegExp(""+n+"[^;]+").exec(document.cookie)||"";h=decodeURIComponent(h.toString().replace(/^[^=]+./,""));try{h&&h.split(":").forEach(function(w){x[w.split("\x3d")[0]]=w.split("\x3d")[1]})}catch(w){return null}return x}var v,k={enable:!0,guard:"~",
addIdTreatment:"auto",encode:!0,denyListSelector:"localhost",allowListSelector:"A",testSessionId:!1,ignoreOnsiteDoms:!1},p=function(){var h=document.createElement("br");return function(n){try{h.querySelector(n)}catch(x){return!1}return!0}}();ORA.Debug.info("crossDomain plugin Register (blocking)","crossDomain-ANA");ORA.regPlugin("crossDomain",function(h,n){var x=n||function(){},w=h.config;r();try{u(w);if(e())return x();var y=k.hasOwnProperty("whiteListSelector")?k.whiteListSelector:k.allowListSelector;
var z=k.hasOwnProperty("blackListSelector")?t(k.blackListSelector):t(k.denyListSelector);if(!p(y))return ORA.Debug.info("allowList selector is invalid - exiting: "+y,"crossDomain-ANA"),x();if(!p(z))return ORA.Debug.info("denyList selector is invalid - exiting: "+z,"crossDomain-ANA"),x();ORA.Debug.debug("binding using allowList:"+y+" denyList: "+z,"crossDomain-ANA");g(y,z,"mousedown",l);g(y,z,"click",l);if((v=f("xd_co_f")||d("xd_co_f"))||k.testSessionId)ORA.Debug.debug("Adding Mutation","crossDomain-ANA"),
ORA.analytics.addMutation("crossDomain",q,3);ORA.Debug.debug("crossDomain Start Init Complete (unblock)","crossDomain-ANA");return x()}catch(A){return ORA.Debug.debug("crossDomain plugin Init Error (unblock)"+A.message,"crossDomain-ANA"),x()}},{blockCollect:!0});ORA.analytics.plugins.crossDomain={};ORA.analytics.plugins.crossDomain.testNode=function(h){return eval(h)};ORA.analytics.plugins.crossDomain.deleteProperty=function(h){delete k[h]};ORA.analytics.plugins.crossDomain.addProperty=function(h,
n){k[h]=n}})();
(function(){var l=[],a=[],b=function(){if(window.onYouTubeIframeAPIReady){var e=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=function(){e();c()}}else window.onYouTubeIframeAPIReady=function(){c()}},c=function(){for(var e=document.querySelectorAll("IFRAME"),m=0;m<e.length;m++)e[m].src&&(0<=e[m].src.toLowerCase().indexOf("//www.youtube.com/embed")||0<=e[m].src.toLowerCase().indexOf("//www.unittest.com/embed"))&&"ytBound"!==e[m].getAttribute("data-ora")&&(-1===e[m].src.indexOf("enablejsapi")&&(-1===
e[m].src.indexOf("?")?e[m].src+="?enablejsapi\x3d1":e[m].src+="\x26enablejsapi\x3d1"),d(e[m]))},d=function(e){var m=l.length;l[m]=new g(e,m);f(e)&&e.setAttribute("data-ora","ytBound");f(e)?ORA.Debug.debug("YT - adding player number "+m+" - binding to "+e.src,"YT_PLUGIN"):ORA.Debug.debug("YT - adding player number "+m+" - binding to manual player object","YT_PLUGIN");"function"===typeof q.addPlayerCallback&&q.addPlayerCallback(e)},f=function(e){return"object"===typeof HTMLElement?e instanceof HTMLElement:
e&&"object"===typeof e&&1===e.nodeType&&"string"===typeof e.nodeName},g=function(e,m,v){var k=this,p={id:m,ready:!1,loaded:!1,info:{playerState:null,currentTime:null,duration:null,videoData:{video_id:null,video_author:"",title:"",list:null},isMuted:!1,volume:null,videoUrl:"",playbackQuality:null,playlist:null,playlistIndex:-1}},h=null,n=function(y){var z=w.getVideoData();p.info.videoData.video_id=z.video_id;p.info.videoData.title=z.title;p.info.videoData.author=z.author;p.info.duration=w.getDuration();
p.info.currentTime=w.getCurrentTime();p.info.playerState=w.getPlayerState();p.info.playlist=w.getPlaylist();p.info.playlistIndex=w.getPlaylistIndex();p.info.muted=w.isMuted();p.info.volume=w.getVolume();p.info.playbackQuality=w.getPlaybackQuality();p.info.videoUrl=w.getVideoUrl();y&&(videoEventFn(k.videoStates,p,"updatemeta"),videoEventFn(k.videoStates,p,"load"))},x=function(){p.info.currentTime=w.getCurrentTime();w.isMuted()!==p.info.isMuted&&(p.info.isMuted=w.isMuted(),videoEventFn(k.videoStates,
p,"mute"));w.getVolume()!==p.info.volume&&(p.info.volume=w.getVolume(),videoEventFn(k.videoStates,p,"volume"));w.getPlayerState()!==p.info.playerState&&(ORA.Debug.debug("YT discovered missing change event - resending "+p.info.videoData.title+" - Last State:"+p.info.playerState+" current state:"+w.getPlayerState(),"YT_PLUGIN"),window["ORA_YTStateChange"+p.id]({target:w,data:w.getPlayerState()}));videoEventFn(k.videoStates,p,"timeupdate")};var w=f(e)?new YT.Player(e):e;k.videoStates={WT:{clip_n:null,
clip_id:null,clip_secs:null,clip_mins:null,clip_ct:null,clip_perc:null,clip_ev:null,clip_duration:null,clip_t:null,clip_player:"youtube",clip_provider:null,clip_vol:null,clip_res:null,clip_player_res:null,clip_duration_n:null,clip_tv:"2.0.0",clip_mode:null,dl:40},_state:"loading",_lastBeacon:0,_eventThrottle:0,_lastQuartile:0,_pauseDelay:null,_currentQuartile:0,_pauseTime:null,_hasPlayed:!1};k.isReady=function(){return p.ready};w.oraId=m;videoEventFn=v?v:r;window["ORA_YTReady"+m]=function(y){ORA.Debug.debug("YT Player ready for "+
y.target.getVideoData().title,"YT_PLUGIN");n(!0);h||(h=setInterval(x,100));p.ready=!0};w.addEventListener("onReady","ORA_YTReady"+m);window["ORA_YTStateChange"+m]=function(y){var z=y.target.getVideoData(),A="unstarted ended play pause buffering undefined cued".split(" "),D=p.info.playerState;y.data!==YT.PlayerState.PAUSED&&(p.info.currentTime=w.getCurrentTime());ORA.Debug.debug("YT "+z.title+" State Change to "+A[y.data+1]+" from "+A[p.info.playerState+1],"YT_PLUGIN");p.info.playerState=y.data;(y.data===
YT.PlayerState.UNSTARTED||D===YT.PlayerState.UNSTARTED&&y.data===YT.PlayerState.BUFFERING)&&n(y.data===YT.PlayerState.BUFFERING);y.data===YT.PlayerState.ENDED||y.data===YT.PlayerState.UNSTARTED&&D!==YT.PlayerState.CUED?(h&&clearInterval(h),h=null,p.loaded=!1):h||h||(h=setInterval(x,100));ORA.Debug.debug("YT "+z.title+" videoEventCallback "+A[y.data+1]+" at "+w.getCurrentTime(),"YT_PLUGIN");videoEventFn(k.videoStates,p,A[y.data+1])};w.addEventListener("onStateChange","ORA_YTStateChange"+m);window["ORA_YTError"+
m]=function(y){ORA.Debug.debug("YT Player error for "+y.target.getVideoData().title,"YT_PLUGIN");p.error=y.data;videoEventFn(k.videoStates,p,"error")};w.addEventListener("onError","ORA_YTError"+m);k.getMeta=function(){return p};k.player=w;k.getProgressEventId=function(){return h};k.reset=function(){h&&clearInterval(h);h=null;delete window["ORA_YTError"+p.id];delete window["ORA_YTStateChange"+p.id];delete window["ORA_YTReady"+p.id]}},q={load:!0,loadMeta:!0,pause:!0,quartile:!0,beacon:!0,seek:!0,beaconRate:30,
pctInc:25,volume:!0,buffering:!0,cued:!0,mute:!0,bins:15,poll:!1,pollRate:500,screenMode:!0,trackCallback:function(e){ORA.click({data:e.args})},loadAPI:!1,mode:"automatic",pollId:null},u=function(e,m){var v,k=e.config||{};window.ORA&&ORA.Debug.info("YouTube Plugin Init Started","YT_PLUGIN");try{if(!window.postMessage){ORA.Debug("YT - Browser does not support postMessage which is required for YouTube tracking - exiting","YT_PLUGIN");m&&m();return}for(v in k)k.hasOwnProperty(v)&&void 0!==k[v]&&(q[v]=
k[v]);if(void 0!==q.enable&&!q.enable){ORA.Debug.info("YT loading is disabled plugin","YT_PLUGIN");return}window.YT&&window.YT.Player?t():(ORA.Debug.debug("YT - defering init, the youtube iframe_api script has not loaded"),b());if(q.loadAPI&&!window.YT){ORA.Debug.info("YT loading iframe_api plugin","YT_PLUGIN");var p=document.createElement("script");p.src="//www.youtube.com/iframe_api";var h=document.getElementsByTagName("script")[0];h.parentNode.insertBefore(p,h)}}catch(n){window.ORA&&(ORA.Debug.info("YT Plugin Init Error",
"YT_PLUGIN"),m&&m())}window.ORA&&ORA.Debug.info("YT Plugin Init Complete","YT_PLUGIN");m&&m()},t=function(){"automatic"===q.mode||"auto"===q.mode?(ORA.Debug.info("YT configuring for automatic mode","YT_PLUGIN"),c()):ORA.Debug.info("YT configuring for manual mode","YT_PLUGIN");q.poll&&(ORA.Debug.info("YT polling for videos","YT_PLUGIN"),q.pollId=setTimeout(function(){c()},q.pollRate));ORA.Debug.info("YT Plugin Init Complete","YT_PLUGIN")},r=function(e,m,v){var k=q;var p=m.info;var h=m.info.videoData;
"timeupdate"!==v&&window.ORA&&window.ORA.Debug.debug("YT Plugin player event received: "+v+" for "+e.WT.clip_n,"YT_PLUGIN");p.playlist&&(e.WT.clip_playlist_items=p.playlist.length,-1!==p.playlistIndex&&(e.WT.clip_playlist_index=p.playlistIndex));var n=!1;switch(v){case "play":e._pauseDelay&&(clearTimeout(e._pauseDelay),e._pauseDelay=null,1.2<Math.abs(e._pauseTime-p.currentTime)?(r(e,m,"seek"),e._state=v):r(e,m,"sendpause"));if("play"===e._state)break;if("seek"===e._state){e._state=v;break}"pause"===
e._state?k.pause&&(e.WT.clip_ev="Resume",n=!0):("loading"===e._state&&(r(e,m,"load"),r(e,m,"meta")),r(e,m,"meta"),e.WT.clip_ev="Play",e._lastBeacon=0,e.WT.clip_perc=null,e.WT.clip_secs=null,e.WT.clip_mins=null,e._currentQuartile=0,e._lastQuartile=0,e._hasPlayed=!0,n="play"!==e._state);e._state=v;break;case "pause":e._pauseTime=p.currentTime;e._pauseDelay||"seek"===e._state||(e._pauseDelay=setTimeout(function(){e._pauseDelay=null;r(e,m,"sendpause")},2E3));break;case "sendpause":k.pause&&(n=!0);e._state=
"pause";e.WT.clip_ev="Pause";break;case "ended":if("compete"===e._state||!e._hasPlayed){e._state="complete";break}m.info.currentTime=m.info.duration;r(e,m,"timeupdate");e.WT.clip_ev="Complete";e._hasPlayed=!1;n=!0;e._state=v;break;case "buffering":e._pauseDelay?(clearTimeout(e._pauseDelay),e._pauseDelay=null,r(e,m,"seek"),k.buffering&&(e.WT.clip_ev="Buffering",n=!0,e._state="seek")):k.buffering&&(e.WT.clip_ev="Buffering",n=!0,e._state=v);break;case "unstarted":r(e,m,"updatemeta");e._lastBeacon=0;
e.WT.clip_perc=null;e.WT.clip_secs=null;e.WT.clip_mins=null;e._currentQuartile=0;e._lastQuartile=0;e.WT.dl=40;break;case "cued":k.cued&&(e.WT.clip_ev="Cued",n=!0,e._state=v);break;case "timeupdate":e.WT.clip_secs=Math.floor(100*p.currentTime)/100;e.WT.clip_mins=Math.floor(100*p.currentTime/60)/100;e.WT.clip_vol=Math.floor(p.volume);0<p.duration&&0<p.currentTime&&(e.WT.clip_perc=Math.floor(p.currentTime/p.duration*100));if(0===e._eventThrottle&&k.beacon&&p.currentTime>e._lastBeacon+k.beaconRate){e.WT.clip_ev=
"Beacon";n=!0;e._lastBeacon=p.currentTime+k.beaconRate;break}if(k.quartile&&(e.WT.clip_perc||0)>=e._lastQuartile+k.pctInc){e._currentQuartile=Math.floor(e.WT.clip_perc/k.pctInc)*k.pctInc;e._currentQuartile>e._lastQuartile+k.pctInc&&(p=JSON.parse(JSON.stringify(e)),p._currentQuartile-=k.pctInc,r(p,m,"quartile"));r(e,m,"quartile");break}0<a.length&&k.trackCallback(a.shift());0<e._eventThrottle&&e._eventThrottle--;break;case "quartile":e.WT.clip_perc=e._currentQuartile;e._lastQuartile=e._currentQuartile;
e.WT.clip_ev="Quartile";n=!0;break;case "seek":if(0===p.currentTime&&"play"!==e._state){e._state="Ended";break}e._lastBeacon=p.currentTime;"ended"!==e._state&&k.seek&&0===e._eventThrottle&&0!==p.currentTime&&k.seek&&(e.WT.clip_ev="Seek",n=!0);e._state="seek";e._eventThrottle=10;break;case "load":m.loaded||(k.load&&(e.WT.clip_ev="Load",e.WT.dl=40,n=!0),e._lastBeacon=0,e.WT.clip_perc=null,e.WT.clip_secs=null,e.WT.clip_mins=null,e._currentQuartile=0,e._lastQuartile=0,e._state=v,m.loaded=!0);break;case "mute":k.mute&&
(e.WT.clip_ev=p.isMuted?"Mute":"UnMute",n=!0);e._state=v;break;case "meta":r(e,m,"updatemeta");m.loaded||r(e,m,"load");k.loadMeta&&(e.WT.clip_ev="Loadedmetadata",n=!0);break;case "updatemeta":isFinite(p.duration)?(e.WT.clip_duration=Math.floor(100*p.duration)/100,e.WT.clip_duration_min=Math.floor(100*p.duration/60)/100,e.WT.clip_mode="FixedDuration"):(k.quartile=!1,e.WT.clip_mode="Stream");k.bins&&isFinite(p.duration)&&(n=Math.floor((p.duration+k.bins)/k.bins),e.WT.clip_duration_n=(n-1)*k.bins+"-"+
n*k.bins);p.videoUrl?(e.WT.clip_src=p.videoUrl,e.WT.clip_ct="youtube",1<p.videoUrl.match(/:\/\/(www\.)?(.[^/:]+)/).length?e.WT.clip_provider=p.videoUrl.match(/:\/\/(www\.)?(.[^/:]+)/)[2]:e.WT.clip_provider="unknown"):(e.WT.clip_ct="unknown",e.WT.clip_provider="self");e.WT.clip_n=h.title?h.title:p.videoUrl?p.videoUrl.split("/").pop().split(".")[0]:"unknown";h.video_id&&(e.WT.clip_id=h.video_id);p.playerType&&(e.WT.clip_t=p.playerType);p.playbackQuality&&(e.WT.clip_res=p.playbackQuality);e.WT.clip_vol=
Math.floor(p.volume);n=!1;break;case "volume":k.volume&&0===e._eventThrottle&&(e.WT.clip_vol=Math.floor(p.volume),e.WT.clip_ev="Volume",n=!0,e._eventThrottle=20);break;case "error":switch(m.error){case 2:e.WT.clip_ev="Error - request contains invalid parameter";break;case 5:e.WT.clip_ev="Error - Content can not be played in a H%ML5 Player";break;case 100:e.WT.clip_ev="Error - Requested video was not found";break;case 101:case 102:e.WT.clip_ev="Error - Video can not be played in embeded players";break;
default:e.WT.clip_ev="Error - Unknown video error"}e.WT.dl=42;n=!0}if(n){window.ORA&&window.ORA.Debug.debug("YT Plugin queueing data for "+e.WT.clip_n+" : "+e.WT.clip_ev,"YT_PLUGIN");n={};p=Object.keys(e.WT);for(h=0;h<p.length;h++)"number"===typeof e.WT[p[h]]?n["WT."+p[h]]=e.WT[p[h]].toString():null===e.WT[p[h]]?delete n["WT."+p[h]]:n["WT."+p[h]]=e.WT[p[h]];a.push({element:this,args:n,transform:k.transformCallback,data:e.WT});if("function"===typeof k.trackCallback)try{k.trackCallback(a.pop())}catch(x){window.ORA&&
ORA.Debug.info("YT Plugin Error with trackCallback","YT_PLUGIN")}}e.WT.dl=41};ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.yt||(ORA.analytics.plugins.yt={});ORA.analytics.plugins.yt.init=u;ORA.analytics.plugins.yt.reset=function(){for(var e in l)l.hasOwnProperty(e)&&l[e].reset();q.pollId&&(clearInterval(q.pollId),q.pollId=null);l=[]};ORA.analytics.plugins.yt.ytVideoClass=g;ORA.analytics.plugins.yt.videoEventCallback=r;ORA.analytics.plugins.yt.getConfig=function(){return q};
ORA.analytics.plugins.yt.setConfig=function(e){q=e};ORA.analytics.plugins.yt.addPlayer=d;ORA.Debug.debug("YouTube Plugin registration start","ANA");ORA.regPlugin("yt",u)})();
(function(){var l={cgDefs:["wt.cg_n","wt.cg_s","wt.cg_s#"],urlData:window.location.pathname.split("/"),init:function(a,b){var c=a.config||{},d=b||function(){};c.cgDefs&&(l.cgDefs=c.cgDefs);if(void 0===c.enable||c.enable){for(c=0;c<l.urlData.length;){if(""===l.urlData[c]||-1<l.urlData[c].indexOf("."))l.urlData.splice(c,1),c--;c++}ORA.Debug.debug("cg URL parsing is "+JSON.stringify({urlData:l.urlData},null,4),"ANA-cg");ORA.analytics.addMutation("addCg",l.addCgMutation);d();ORA.Debug.debug("cg Plugin init complete",
"ANA-cg")}else ORA.Debug.debug("content group plugin is disabled, exiting","ANA-cg"),d()},addCgMutation:function(a){try{for(var b=l.cgDefs||[],c=0;(c<b.length||-1<b[b.length-1].indexOf("#"))&&c<l.urlData.length;c++)c>=b.length-1&&-1<b[b.length-1].indexOf("#")?a.payload[b[b.length-1].replace("#",c)]=l.urlData[c]:a.payload[b[c]]=l.urlData[c]}catch(d){ORA.Debug.debug("cg Plugin mutation error","ANA-cg")}},rmCgMutation:function(){ORA.analytics.rmMutation("addCg")}};ORA.Debug.debug("cg - Registering Plugin",
"ANA-cg");ORA.regPlugin("cg",l.init,{blockCollect:!0});ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.cg||(ORA.analytics.plugins.cg={});ORA.analytics.plugins.cg.addCg=l})();
(function(){var l={readCookies:[],enable:!0},a={},b={},c,d=function(u,t,r){-1<u.indexOf(t.parseOn||":")||-1<u.indexOf(t.parseLv||"\x3d")?u.split(t.parseOn||":").forEach(function(e){c[r]||(c[r]={});c[r][e.substr(0,e.indexOf(t.parseLv||"\x3d"))]=e.substr(e.indexOf(t.parseLv||"\x3d")+1)}):c[r]=u},f=function(u,t,r){var e=!0;r&&void 0!==r.persist&&(e=r.persist);e?a[t]=u:b[t]=u},g=function(u){for(var t in a)a.hasOwnProperty(t)&&u.setParam(t,a[t]);if("seed message"===u.desc)for(var r in b)b.hasOwnProperty(r)&&
u.setParam(r,b[r])},q=function(u){for(var t in l)l.hasOwnProperty(t)&&void 0!==u[t]&&(l[t]=u[t])};ORA.Debug.info("cookie cutter start registration","ANA-cookieCutter");ORA.regPlugin("cookieCutter",function(u,t){ORA.Debug.info("cookie cutter start init","ANA-cookieCutter");var r=t||function(){},e=ORA.getIEVer();if(e&&9>e)return ORA.Debug.info("requires \x3e\x3d ie9, disabling plugin","ANA-cookieCutter"),r();q(u.config);if(!l.enable)return ORA.Debug.info("cookie cutter is disables","ANA-cookieCutter"),
r();Object.values||(Object.values=function(m){var v=[],k;for(k in m)m.hasOwnProperty(k)&&v.push(m[k]);return v});l.readCookies.forEach(function(m){var v=Object.keys(m.cookie).shift(),k=Object.values(m.cookie).shift(),p=m.options;c||(c={});if(void 0===c[v]){var h=document.cookie.split(";");p=p||{};for(var n=h.length-1;0<=n;n--){var x=h[n].substr(0,h[n].indexOf("\x3d")).replace(/^\s+|\s+$/g,""),w=h[n].substr(h[n].indexOf("\x3d")+1);v&&x===v&&d(w,p,x)}}h=c[v]||"";ORA.Debug.debug("cookieCutter looking at: "+
v);if(h)if(m=m.options,"object"===typeof h)for(var y in h)h.hasOwnProperty(y)&&void 0!==k[y]&&(f(h[y],k[y],m),ORA.Debug.debug("cookie cutter found target "+k[y]+"\x3d"+h[y]+" - "+JSON.stringify(m)));else f(h,k,m),ORA.Debug.debug("cookie cutter found target "+h+"\x3d"+k+" - "+JSON.stringify(m))});ORA.analytics.addMutation("cookiecutter",g);ORA.Debug.info("cookie cutter complete init","ANA-cookieCutter");return r()});ORA.Debug.info("cookie cutter start registration complete","ANA-cookieCutter");ORA.analytics.plugins.cookieCutter=
{};ORA.analytics.plugins.cookieCutter.testNode=function(u){return eval(u)};ORA.analytics.plugins.cookieCutter.t1=function(){return l};ORA.analytics.plugins.cookieCutter.t2=function(){return c};ORA.analytics.plugins.cookieCutter.t3=function(){return{persist:a,session:b}};ORA.analytics.plugins.cookieCutter.t3=function(){a={};b={}}})();
(function(){var l={htmlvid:[],cache:[],loaded:!1,unitTest:!1,config:{load:!1,loadMeta:!1,pause:!0,quartile:!0,beacon:!0,seek:!0,beaconRate:60,pctInc:25,volume:!0,bins:15,poll:!1,pollRate:250,screenMode:!0,trackCallback:null,postMessage:!1,nameCallback:null,transformCallback:null,pollId:null},videoStates:function(){this.data={ORA:{clip_n:null,clip_id:null,clip_secs:null,clip_mins:null,clip_ct:null,clip_perc:null,clip_ev:null,clip_duration:null,clip_t:null,clip_player:"html5",clip_provider:null,clip_vol:null,
clip_res:null,clip_player_res:null,clip_duration_n:null,clip_tv:"2.2.5",clip_mode:null,clip_screen:"FullscreenOff",dl:41},_state:"load",_lastBeacon:0,_volSettle:-1,_seekSettle:0,_lastQuartile:0,node:null}},attachVideo:function(a){if(a){var b=new l.videoStates,c=null;b.data.node=a;"function"!==typeof l.config.trackCallback&&(window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video setting tracking Callback to ORA.click","ANA"),l.config.trackCallback=function(g){ORA.click({data:g.args})});try{try{"function"===
typeof l.config.nameCallback&&(c=l.config.nameCallback(a))}catch(g){window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video nameCallback error","ANA")}a.getAttribute("name")?b.data.ORA.clip_n=a.getAttribute("name"):b.data.ORA.clip_n=a.videoSetSource?a.videoSetSource.split("/").pop().split(".")[0]:a.currentSrc.split("/").pop().split(".")[0];a.currentSrc&&(b.data.ORA.clip_src=a.currentSrc)}catch(g){b.data.ORA.clip_n="unknown"}c&&(b.data.ORA.clip_n=c);try{b.data.ORA.clip_ct=a.currentSrc.match(/.+\.([^?]+)(\?|$)/)[1]}catch(g){b.data.ORA.clip_ct=
"unknown",window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video no file type found from currentSrc","ANA")}try{b.data.ORA.clip_provider=a.currentSrc.match(/:\/\/(www\.)?(.[^/:]+)/)[2]}catch(g){b.data.ORA.clip_provider="self",window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video no provider found from currentSrc","ANA")}l.config.volume&&(b.data.ORA.clip_vol=Math.floor(100*a.volume));a.seekable||(l.config.seek=!1);var d=function(g){a.addEventListener(f[g],function(q){l.callback(b,q)})};var f="play pause ended error timeupdate seeking loadstart seeked loadedmetadata volumechange".split(" ");
for(c=0;c<f.length;c++)d(c);a.setAttribute("data-ora-track","bound");window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video Plugin Attached to video:"+b.data.ORA.clip_n,"ANA");return b}window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video no element provided to attach to","ANA")},videoBind:function(a){var b;for(b=0;b<document.getElementsByTagName("video").length;b++)"bound"!==document.getElementsByTagName("video")[b].getAttribute("data-ora-track")&&(l.htmlvid.push(new l.attachVideo(document.getElementsByTagName("video")[b])),
window.ORA&&window.ORA.Debug&&window.ORA.Debug.info("hrml5Video Plugin Found Video using "+a,"ANA"))},pollStop:function(){null!==l.config.pollId&&(clearInterval(l.config.pollId),l.config.pollId=null)},setTrackingCallback:function(a){this.config.trackCallback=a},init:function(a){var b;a=a.config||{};l.htmlvid=[];window.ORA&&ORA.Debug&&ORA.Debug.info("html5Video Plugin Init Started","ANA");if(a&&void 0!==a.enable&&!a.enable)ORA.Debug.info("html5 Plugin is disabled","ANA");else{try{if(!document.createElement("video").canPlayType&&
!a.test){window.ORA&&ORA.Debug&&ORA.Debug.info("html5Video: not html5 compliant - exiting","ANA");return}for(b in l.config)l.config.hasOwnProperty(b)&&void 0!==a[b]&&(l.config[b]=a[b]);0<document.getElementsByTagName("video").length&&l.videoBind("Static");l.config.poll&&(l.config.pollId=setInterval(function(){0<document.getElementsByTagName("video").length&&l.videoBind("Static")},a.pollRate))}catch(c){window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video Plugin Init Error","ANA")}window.ORA&&ORA.Debug&&
ORA.Debug.info("hrml5Video Plugin Init Complete","ANA")}},callback:function(a,b){var c=b.target||b.srcElement||{},d,f,g=this.config;"timeupdate"!==b.type&&window.ORA&&window.ORA.Debug&&window.ORA.Debug.info("hrml5Video Plugin player event received: "+b.type,"ANA");if(""===a.data.ORA.clip_n||null===a.data.ORA.clip_n){try{c.getAttribute("name")&&-1<c.getAttribute("name").indexOf("meta")?a.data.ORA.clip_n=c.getAttribute("name"):a.data.ORA.clip_n=c.currentSrc.split("/").pop().split(".")[0]}catch(u){a.data.ORA.clip_n=
"unknown"}try{a.data.ORA.clip_ct=c.currentSrc.match(/.+\.([^?]+)(\?|$)/)[1]}catch(u){a.data.ORA.clip_ct="unknown"}try{a.data.ORA.clip_provider=c.currentSrc.match(/:\/\/(www\.)?(.[^/:]+)/)[2]}catch(u){a.data.ORA.clip_provider="self"}}c.currentSrc&&(a.data.ORA.clip_src=c.currentSrc);var q=!1;g.screenMode&&(d=document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||document.msFullscreenElement)&&(a.data.ORA.clip_screen=d?"FullscreenOn":"FullscreenOff");switch(b.type){case "play":if("seeking"===
a.data._state||"seeked"===a.data._state){a.data._state=b.type;break}"pause"===a.data._state?g.pause&&(a.data.ORA.clip_ev="Resume",q=!0):("load"===a.data._state&&(l.callback(a,{type:"loadstart",target:c}),l.callback(a,{type:"loadedmetadata",target:c})),a.data.ORA.clip_ev="Play",a.data._lastBeacon=0,a.data.ORA.clip_perc=null,a.data.ORA.clip_secs=null,a.data.ORA.clip_mins=null,q="play"!==a.data._state);a.data._state=b.type;break;case "pause":c.ended||c.seeking||"ended"===a.data._state.toLowerCase()||
!g.pause||(q=!0);a.data._state=b.type;a.data.ORA.clip_ev="Pause";break;case "ended":a.data.ORA.clip_ev="Complete";q=!0;a.data._state=b.type;break;case "error":q=!0;a.data.ORA.clip_ev="Error";switch(c.error.code){case c.error.MEDIA_ERR_ABORTED:a.data.ORA.clip_ev+=": You aborted the video playback.";break;case c.error.MEDIA_ERR_NETWORK:a.data.ORA.clip_ev+=": A network error caused the video download to fail part-way.";break;case c.error.MEDIA_ERR_DECODE:a.data.ORA.clip_ev+=": The video playback was aborted due to a corruption problem or because the video used features your browser did not support.";
break;case c.error.MEDIA_ERR_SRC_NOT_SUPPORTED:a.data.ORA.clip_ev+=": The video could not be loaded, either because the server or network failed or because the format is not supported.";break;default:a.data.ORA.clip_ev+=": An unknown error occurred."}break;case "timeupdate":0<a.data._seekSettle&&a.data._seekSettle--;a.data.ORA.clip_secs=Math.floor(100*c.currentTime)/100;a.data.ORA.clip_mins=Math.floor(100*c.currentTime/60)/100;0<a.data.ORA.clip_secs&&"load"===a.data._state&&(this.callback(a,{type:"loadstart",
target:c}),this.callback(a,{type:"loadedmetadata",target:c}),this.callback(a,{type:"play",target:c}));a.data.ORA.clip_duration=c.duration&&Math.floor(100*c.duration)/100;0<c.duration&&(a.data.ORA.clip_perc=Math.floor(c.currentTime/c.duration*100),a.data.ORA.clip_duration_min=Math.floor(100*c.duration/60)/100,a.data.ORA.clip_mode="FixedDuration");if(g.quartile&&(a.data.ORA.clip_perc||0)>=a.data._lastQuartile+g.pctInc){a.data.ORA.clip_perc=Math.floor(a.data.ORA.clip_perc/g.pctInc)*g.pctInc;a.data._lastQuartile=
a.data.ORA.clip_perc;a.data.ORA.clip_ev="Quartile";q=!0;break}if(g.beacon&&c.currentTime>a.data._lastBeacon+g.beaconRate){a.data.ORA.clip_ev="Beacon";q=!0;a.data._lastBeacon+=g.beaconRate;break}0<a.data._volSettle&&a.data._volSettle--;0===a.data._volSettle&&(a.data._volSettle--,a.data.ORA.clip_ev="Volume",q=!0);0<l.cache.length&&g.trackCallback(this.cache.shift());"ended"===a.data._state&&(a.data.ORA.clip_ev="play",a.data.ORA.clip_secs="0",a.data.ORA.clip_mins="0",a.data.ORA.clip_perc=null,a.data._lastQuartile=
0,q=!0,a.data._state="Play");break;case "seeked":"Ended"===a.data._state&&(a.data.ORA.clip_secs="0",a.data.ORA.clip_mins="0",a.data.ORA.clip_perc=null,a.data._lastQuartile=0,this.callback(a,{type:"play",target:c}));a.data._state=b.type;break;case "seeking":if(0===c.currentTime&&"play"!==a.data._state){a.data._state="Ended";break}a.data._lastBeacon=c.currentTime;"ended"!==a.data._state&&g.seek&&0===a.data._seekSettle&&0!==c.currentTime&&(g.seek&&(a.data.ORA.clip_ev="Seek",q=!0),a.data._seekSettle=
50);a.data._state=b.type;break;case "loadstart":g.load&&(a.data.ORA.clip_ev="Load",q=!0);a.data._state=b.type;break;case "loadedmetadata":g.loadMeta&&(a.data.ORA.clip_ev="Loadedmetadata",a.data.ORA.dl=41,q=!0);isFinite(c.duration)?(a.data.ORA.clip_duration=Math.floor(100*c.duration)/100,a.data.ORA.clip_duration_min=Math.floor(100*c.duration/60)/100,a.data.ORA.clip_mode="FixedDuration"):a.data.ORA.clip_mode="Stream";a.data.ORA.clip_res=c.videoHeight+"x"+c.videoWidth;a.data.ORA.clip_player_res=c.height||
c.clientHeight+"x"+c.clientWidth;g.bins&&isFinite(c.duration)&&(d=Math.floor((c.duration+g.bins)/g.bins),a.data.ORA.clip_durration_n=(d-1)*g.bins+"-"+d*g.bins);break;case "volumechange":g.volume&&(a.data._volSettle=5,a.data.ORA.clip_vol=Math.floor(100*c.volume),a.data.ORA.clip_ev="Volume",q=!0)}if(q){window.ORA&&window.ORA.Debug&&window.ORA.Debug.info("html5Video queueing data for "+a.data.ORA.clip_n+" : "+a.data.ORA.clip_ev,"ANA");q={};for(f in a.data.ORA)a.data.ORA.hasOwnProperty(f)&&("number"===
typeof a.data.ORA[f]?("clip_secs"===f||"clip_perc"===f||"clip_mins"===f)&&0===a.data.ORA[f]||isNaN(a.data.ORA[f])?delete q["WT."+f]:q["WT."+f]=a.data.ORA[f].toString():null===a.data.ORA[f]?delete q["WT."+f]:q["WT."+f]=a.data.ORA[f]);this.cache.push({element:this,args:q,transform:g.transformCallback,data:a.data.ORA,videoEle:c});if("function"===typeof g.trackCallback)try{g.trackCallback(this.cache.pop())}catch(u){window.ORA&&ORA.Debug&&ORA.Debug.info("hrml5Video Error with trackCallback","ANA")}}a.data.ORA.dl=
40}};window.ORA&&ORA.regPlugin?(ORA.regPlugin("html5Video",l.init),window.ORA.Debug.info("hrml5Video Plugin registration request","ANA")):(window.html5VideoConf||(window.html5VideoConf={}),window.html5VideoConf.trackCallback=function(a){a=JSON.stringify({company:"Oracle-102820161056",product:"ORA",action:"click",data:a.args});window.parent.postMessage(a,"*")},l.init({config:window.html5VideoConf}),window.ORA={});ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.html5Video=l})();
ORA.setExecuteState("analytics","ready");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_LOAD_COMPLETE,ORA.Event.STATUS_SUCCESS),!0);