/** Safety Control Tower - Motor de Formularios Dinámicos / Administración */
document.addEventListener('DOMContentLoaded', function(){
 const root=document.querySelector('.container[data-csrf-token]');if(!root)return;
 const csrf=root.dataset.csrfToken||'',isGlobal=root.dataset.isGlobalAdmin==='1',$=id=>document.getElementById(id);
 const i18nEl=$('formsI18n');let I={};try{I=i18nEl?JSON.parse(i18nEl.textContent||'{}'):{};}catch(_){ }const S=(k,f)=>I[k]||f||k;
 const companySelect=$('companySelect'),formsAlert=$('formsAlert'),formsStatus=$('formsStatus'),formsTableWrap=$('formsTableWrap'),formsTableBody=$('formsTableBody'),formEditor=$('formEditor'),formEditorTitle=$('formEditorTitle'),formMode=$('formMode'),formTarget=$('formTarget'),formName=$('formName'),formDescription=$('formDescription'),formSubmitBtn=$('formSubmitBtn'),formCancelEditBtn=$('formCancelEditBtn'),formsDetail=$('formsDetail'),formsDetailName=$('formsDetailName'),formsDetailClose=$('formsDetailClose'),detailAlert=$('detailAlert'),lockedNote=$('lockedNote'),fieldsList=$('fieldsList'),fieldForm=$('fieldForm'),fieldMode=$('fieldMode'),fieldTarget=$('fieldTarget'),fieldLabel=$('fieldLabel'),fieldType=$('fieldType'),fieldOrder=$('fieldOrder'),fieldRequired=$('fieldRequired'),fieldOptions=$('fieldOptions'),fieldSubmitBtn=$('fieldSubmitBtn'),fieldCancelEdit=$('fieldCancelEdit'),submissionsList=$('submissionsList'),submissionDetail=$('submissionDetail'),submissionDetailClose=$('submissionDetailClose'),submissionAnswers=$('submissionAnswers'),pageLanguageSelect=$('pageLanguageSelect');
 let currentForm=null,currentScope=isGlobal?'global':null;
 function esc(v){const e=document.createElement('div');e.textContent=v==null?'':String(v);return e.innerHTML;}
 function alert(el,msg,variant){if(!el)return;el.textContent=msg||'';el.classList.remove('d-none','alert-success','alert-danger','alert-warning','alert-info');el.classList.add('alert-'+(variant||'danger'));}
 function hide(el){if(el)el.classList.add('d-none');}
 async function api(url,opt){try{const r=await fetch(url,opt||{});return await r.json();}catch(_){return{success:false,message:S('forms_error_response','Respuesta inválida del servidor.')}}}
 function post(url,data){return api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({csrf_token:csrf},data||{}))});}
 // El cambio de idioma (confirmación + guardado en perfil) lo maneja js/lang-switcher.js.
 async function loadCompanies(){if(!isGlobal||!companySelect)return;const r=await api('./empresas-disponibles.php');if(!r.success){alert(formsAlert,r.message,'danger');return;}companySelect.innerHTML='<option value="global">'+esc(S('forms_scope_global','Plantillas globales'))+'</option>';(r.data||[]).forEach(c=>{const o=document.createElement('option');o.value=c.id_company;o.textContent=c.razon_social+(String(c.state)==='1'?'':' · '+S('common_inactive','Inactivo'));companySelect.appendChild(o);});companySelect.value='global';currentScope='global';}
 function resetForm(){formMode.value='create';formTarget.value='';formName.value='';formDescription.value='';formEditorTitle.textContent=S('forms_form_new','Nuevo formulario');formSubmitBtn.textContent=S('forms_save','Guardar formulario');formCancelEditBtn.classList.add('d-none');}
 function resetField(){fieldMode.value='create';fieldTarget.value='';fieldLabel.value='';fieldType.value='text';fieldOrder.value='0';fieldRequired.checked=false;fieldOptions.value='';fieldSubmitBtn.textContent=S('forms_field_new','Agregar campo');fieldCancelEdit.classList.add('d-none');}
 function closeDetail(){currentForm=null;formsDetail.classList.remove('active');submissionDetail.classList.add('d-none');resetField();}
 async function loadForms(){hide(formsAlert);formsStatus.className='alert alert-info mb-0';formsStatus.textContent=S('forms_loading','Cargando formularios...');formsTableWrap.classList.add('d-none');let url='./formularios-listar.php';if(isGlobal&&currentScope!=='global')url+='?id_company='+encodeURIComponent(currentScope);const r=await api(url);if(!r.success){formsStatus.className='alert alert-danger mb-0';formsStatus.textContent=r.message||S('forms_error_load');return;}const items=r.data||[];if(!items.length){formsStatus.textContent=S('forms_empty','No hay formularios configurados para este ámbito.');return;}formsStatus.classList.add('d-none');formsTableWrap.classList.remove('d-none');renderForms(items);}
 function renderForms(items){formsTableBody.innerHTML='';items.forEach(f=>{const global=f.id_company==null,editable=!!f.editable,locked=!!f.locked,active=String(f.state)==='1';const tr=document.createElement('tr');const scope=global?'<span class="scope-badge global">'+esc(S('forms_global_badge','Global'))+'</span>':'<span class="scope-badge">'+esc(f.company_name||S('forms_company_badge','Empresa'))+'</span>';let actions='<div class="d-flex gap-1 flex-wrap"><button class="btn btn-outline-custom btn-sm" data-a="manage">'+esc(S('forms_manage','Gestionar'))+'</button>';if(editable&&!locked)actions+='<button class="btn btn-outline-custom btn-sm" data-a="edit">'+esc(S('forms_edit','Editar'))+'</button>';if(editable)actions+='<button class="btn '+(active?'btn-outline-danger':'btn-outline-success')+' btn-sm" data-a="toggle">'+esc(active?S('forms_deactivate','Dar de baja'):S('forms_reactivate','Reactivar'))+'</button>';actions+='</div>';tr.innerHTML='<td><strong>'+esc(f.name)+'</strong>'+(locked?' <span class="badge text-bg-warning">'+esc(S('forms_locked','Bloqueado'))+'</span>':'')+'</td><td>'+scope+'</td><td>'+esc(f.field_count||0)+'</td><td>'+esc(f.submission_count||0)+'</td><td>'+esc(active?S('common_active','Activo'):S('common_inactive','Inactivo'))+'</td><td>'+actions+'</td>';tr.querySelector('[data-a="manage"]').addEventListener('click',()=>openDetail(f));const eb=tr.querySelector('[data-a="edit"]');if(eb)eb.addEventListener('click',()=>startEdit(f));const tb=tr.querySelector('[data-a="toggle"]');if(tb)tb.addEventListener('click',()=>toggle(f));formsTableBody.appendChild(tr);});}
 function startEdit(f){formMode.value='edit';formTarget.value=f.id_form;formName.value=f.name||'';formDescription.value=f.description||'';formEditorTitle.textContent=S('forms_form_edit','Editar formulario');formSubmitBtn.textContent=S('forms_update','Guardar cambios');formCancelEditBtn.classList.remove('d-none');formEditor.scrollIntoView({behavior:'smooth',block:'center'});}
 if(formCancelEditBtn)formCancelEditBtn.addEventListener('click',resetForm);
 if(formEditor)formEditor.addEventListener('submit',async e=>{e.preventDefault();hide(formsAlert);const payload={name:formName.value.trim(),description:formDescription.value.trim()};let url='./formularios-crear.php';if(formMode.value==='edit'){url='./formularios-editar.php';payload.id_form=parseInt(formTarget.value,10);}else if(isGlobal){if(currentScope==='global')payload.scope='global';else{payload.scope='company';payload.id_company=parseInt(currentScope,10);}}formSubmitBtn.disabled=true;const r=await post(url,payload);formSubmitBtn.disabled=false;if(!r.success){alert(formsAlert,r.message,'danger');return;}alert(formsAlert,r.message,'success');resetForm();loadForms();});
 async function toggle(f){if(!confirm(String(f.state)==='1'?S('forms_confirm_deactivate','¿Dar de baja este formulario?'):S('forms_confirm_reactivate','¿Reactivar este formulario?')))return;const r=await post('./formularios-cambiar-estado.php',{id_form:parseInt(f.id_form,10),state:String(f.state)==='1'?0:1});if(!r.success){alert(formsAlert,r.message,'danger');return;}alert(formsAlert,r.message,'success');if(currentForm&&parseInt(currentForm.id_form,10)===parseInt(f.id_form,10))closeDetail();loadForms();}
 async function openDetail(f){hide(detailAlert);currentForm=f;formsDetailName.textContent=f.name;formsDetail.classList.add('active');formsDetail.scrollIntoView({behavior:'smooth'});await Promise.all([loadDetail(),loadSubmissions()]);}
 async function loadDetail(){if(!currentForm)return;const r=await api('./formularios-detalle.php?id='+encodeURIComponent(currentForm.id_form));if(!r.success){alert(detailAlert,r.message,'danger');return;}currentForm=r.data;formsDetailName.textContent=currentForm.name;lockedNote.classList.toggle('d-none',!currentForm.locked);fieldForm.classList.toggle('d-none',!currentForm.editable||currentForm.locked);renderFields(currentForm.campos||[]);}
 function renderFields(fields){fieldsList.innerHTML='';if(!fields.length){fieldsList.innerHTML='<p class="text-muted">'+esc(S('forms_fields_empty','Todavía no hay campos configurados.'))+'</p>';return;}fields.forEach(f=>{const row=document.createElement('div');row.className='field-row';const opts=f.options?' · '+esc(f.options):'';const req=String(f.is_required)==='1'?S('forms_required_yes','Obligatorio'):S('forms_required_no','Opcional');let actions='';if(currentForm.editable&&!currentForm.locked)actions='<div class="d-flex gap-1"><button class="btn btn-outline-custom btn-sm" data-a="edit">'+esc(S('forms_edit','Editar'))+'</button><button class="btn btn-outline-danger btn-sm" data-a="delete">×</button></div>';row.innerHTML='<div><strong>'+esc(f.label)+'</strong><div class="meta">'+esc(f.field_type)+' · '+esc(req)+' · #'+esc(f.sort_order)+opts+'</div></div>'+actions;const eb=row.querySelector('[data-a="edit"]');if(eb)eb.addEventListener('click',()=>startFieldEdit(f));const db=row.querySelector('[data-a="delete"]');if(db)db.addEventListener('click',()=>deleteField(f));fieldsList.appendChild(row);});}
 function startFieldEdit(f){fieldMode.value='edit';fieldTarget.value=f.id_field;fieldLabel.value=f.label||'';fieldType.value=f.field_type||'text';fieldOrder.value=f.sort_order||0;fieldRequired.checked=String(f.is_required)==='1';fieldOptions.value=f.options||'';fieldSubmitBtn.textContent=S('forms_field_edit','Guardar campo');fieldCancelEdit.classList.remove('d-none');fieldForm.scrollIntoView({behavior:'smooth',block:'center'});}
 if(fieldCancelEdit)fieldCancelEdit.addEventListener('click',resetField);
 if(fieldForm)fieldForm.addEventListener('submit',async e=>{e.preventDefault();if(!currentForm)return;hide(detailAlert);const payload={label:fieldLabel.value.trim(),field_type:fieldType.value,sort_order:parseInt(fieldOrder.value||'0',10),is_required:fieldRequired.checked?1:0,options:fieldOptions.value.trim()};let url='./campos-agregar.php';if(fieldMode.value==='edit'){url='./campos-editar.php';payload.id_field=parseInt(fieldTarget.value,10);}else payload.id_form=parseInt(currentForm.id_form,10);fieldSubmitBtn.disabled=true;const r=await post(url,payload);fieldSubmitBtn.disabled=false;if(!r.success){alert(detailAlert,r.message,'danger');return;}alert(detailAlert,r.message||S('forms_field_saved','Campo guardado.'),'success');resetField();loadDetail();loadForms();});
 async function deleteField(f){if(!confirm(S('forms_confirm_field_delete','¿Eliminar este campo?')))return;const r=await post('./campos-eliminar.php',{id_field:parseInt(f.id_field,10)});if(!r.success){alert(detailAlert,r.message,'danger');return;}alert(detailAlert,r.message||S('forms_field_deleted','Campo eliminado.'),'success');loadDetail();loadForms();}
 async function loadSubmissions(){if(!currentForm)return;const r=await api('./envios-listar.php?id_form='+encodeURIComponent(currentForm.id_form));if(!r.success){submissionsList.innerHTML='<div class="alert alert-warning">'+esc(r.message||S('forms_error_submissions'))+'</div>';return;}renderSubmissions(r.data||[]);}
 function renderSubmissions(items){submissionsList.innerHTML='';if(!items.length){submissionsList.innerHTML='<p class="text-muted">'+esc(S('forms_submissions_empty','Todavía no hay respuestas registradas.'))+'</p>';return;}items.forEach(s=>{const row=document.createElement('div');row.className='submission-row';const full=((s.name||'')+' '+(s.lastname||'')).trim()||s.id_users;row.innerHTML='<div class="d-flex justify-content-between gap-3 flex-wrap"><div><strong>'+esc(full)+'</strong><div class="text-muted" style="font-size:.82rem">'+esc(s.id_users)+' · '+esc(s.company_name||'')+'</div></div><div class="text-end"><div>'+esc(S('forms_submission_date','Enviado'))+': '+esc((s.submitted_at||'').replace('T',' '))+'</div><button class="btn btn-outline-custom btn-sm mt-1">'+esc(S('forms_submission_view','Ver respuesta'))+'</button></div></div>';row.querySelector('button').addEventListener('click',()=>openSubmission(s.id_submission));submissionsList.appendChild(row);});}
 async function openSubmission(id){const r=await api('./envio-detalle.php?id_submission='+encodeURIComponent(id));if(!r.success){alert(detailAlert,r.message,'danger');return;}submissionAnswers.innerHTML='';(r.data.respuestas||[]).forEach(a=>{const line=document.createElement('div');line.className='answer-line';let value='';if(a.file_path)value='<a class="btn btn-outline-custom btn-sm" href="./archivo-descargar.php?id_answer='+encodeURIComponent(a.id_answer)+'">'+esc(S('forms_file_download','Descargar archivo'))+' · '+esc(a.original_name||'archivo')+'</a>';else if(Array.isArray(a.display_value))value=esc(a.display_value.join(', '));else value='<div class="answer-value">'+esc(a.display_value==null||a.display_value===''?'—':a.display_value)+'</div>';line.innerHTML='<div class="answer-label">'+esc(a.label)+'</div>'+value;submissionAnswers.appendChild(line);});submissionDetail.classList.remove('d-none');submissionDetail.scrollIntoView({behavior:'smooth'});}
 if(submissionDetailClose)submissionDetailClose.addEventListener('click',()=>submissionDetail.classList.add('d-none'));if(formsDetailClose)formsDetailClose.addEventListener('click',closeDetail);
 if(companySelect)companySelect.addEventListener('change',()=>{currentScope=companySelect.value||'global';resetForm();closeDetail();loadForms();});
 (async()=>{if(isGlobal)await loadCompanies();await loadForms();})();
});
