/** Safety Control Tower - Historial de cambios / Etapa 3 */
document.addEventListener('DOMContentLoaded',()=>{
 const shell=document.querySelector('.history-shell'); if(!shell)return;
 const I=(()=>{try{return JSON.parse(document.getElementById('historyI18n')?.textContent||'{}')}catch{return {}}})();
 const $=id=>document.getElementById(id), isGlobal=shell.dataset.isGlobal==='1';
 let page=1,pages=1,lastRows=[];
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const text=v=>(v===null||v===undefined||v==='')?'—':String(v);
 const actionLabel=v=>String(v||'').replaceAll('_',' ');
 function alertMsg(msg,type='danger'){const a=$('historyAlert');a.className=`alert alert-${type}`;a.textContent=msg;a.classList.remove('d-none')}
 function clearAlert(){$('historyAlert').classList.add('d-none')}
 async function json(url){const r=await fetch(url,{headers:{'Accept':'application/json'}});const p=await r.json().catch(()=>({success:false,message:I.history_error||'Error'}));if(!r.ok||!p.success)throw new Error(p.message||I.history_error||'Error');return p.data}
 async function loadCompanies(){if(!isGlobal)return;try{const rows=await json('empresas-disponibles.php');const s=$('companySelect');rows.forEach(r=>s.insertAdjacentHTML('beforeend',`<option value="${Number(r.id_company)}">${esc(r.razon_social)}${Number(r.state)===0?' · inactiva':''}</option>`))}catch(e){alertMsg(e.message)}}
 function query(){const q=new URLSearchParams({page:String(page),per_page:'50'});if(isGlobal&&$('companySelect').value)q.set('id_company',$('companySelect').value);for(const [id,key] of [['moduleSelect','module'],['actionSelect','action'],['actorSelect','changed_by'],['dateFrom','date_from'],['dateTo','date_to'],['searchInput','search']]){const v=$(id)?.value?.trim();if(v)q.set(key,v)}return q}
 function fillSelect(id,values,current){const s=$(id);const first=s.options[0]?.outerHTML||'<option value=""></option>';s.innerHTML=first;for(const v of values||[])s.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(actionLabel(v))}</option>`);if(current&&[...s.options].some(o=>o.value===current))s.value=current}
 function render(data){
  lastRows=data.rows||[]; const sm=data.summary||{}; $('kpiTotal').textContent=sm.total_rows??0;$('kpiOperations').textContent=sm.operations??0;$('kpiActors').textContent=sm.actors??0;$('kpiToday').textContent=sm.today_rows??0;
  const currentModule=$('moduleSelect').value,currentAction=$('actionSelect').value,currentActor=$('actorSelect').value;fillSelect('moduleSelect',data.catalogs?.modules,currentModule);fillSelect('actionSelect',data.catalogs?.actions,currentAction);fillSelect('actorSelect',data.catalogs?.actors,currentActor);
  const tb=$('historyTbody'),mobile=$('historyMobile');tb.innerHTML='';mobile.innerHTML='';
  if(!lastRows.length){$('historyStatus').className='alert alert-secondary';$('historyStatus').textContent=I.history_empty||'Sin cambios';}
  else{$('historyStatus').className='d-none';}
  lastRows.forEach((r,i)=>{
    const record=r.record_label||`${r.table_name} #${r.record_id}`;const before=text(r.old_value),after=text(r.new_value);
    tb.insertAdjacentHTML('beforeend',`<tr><td class="small">${esc(r.changed_at)}</td><td><span class="history-tag">${esc(r.module)}</span></td><td>${esc(actionLabel(r.action))}</td><td>${esc(record)}</td><td><code>${esc(r.field_name)}</code></td><td><div class="value-preview">${esc(before)}</div></td><td><div class="value-preview">${esc(after)}</div></td><td class="small">${esc(r.changed_by)}</td><td><button class="btn btn-outline-custom btn-sm detail-btn" data-i="${i}" type="button"><i class="bi bi-eye"></i></button></td></tr>`);
    mobile.insertAdjacentHTML('beforeend',`<article class="history-mobile-card"><div class="d-flex justify-content-between gap-2"><div><strong>${esc(record)}</strong><div class="small text-muted">${esc(r.changed_at)} · ${esc(r.changed_by)}</div></div><span class="history-tag">${esc(r.module)}</span></div><div class="small mt-2"><strong>${esc(actionLabel(r.action))}</strong> · <code>${esc(r.field_name)}</code></div><div class="change"><div><span class="small text-muted">${esc(I.history_before||'Antes')}</span><div class="value-preview">${esc(before)}</div></div><div><span class="small text-muted">${esc(I.history_after||'Después')}</span><div class="value-preview">${esc(after)}</div></div></div><button class="btn btn-outline-custom btn-sm mt-2 detail-btn" data-i="${i}" type="button">${esc(I.history_details||'Detalle')}</button></article>`);
  });
  pages=data.pagination?.pages||1;page=data.pagination?.page||1;$('pageInfo').textContent=`${I.history_page||'Página'} ${page} / ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;
 }
 function showDetail(i){const r=lastRows[Number(i)];if(!r)return;const record=r.record_label||`${r.table_name} #${r.record_id}`;$('historyDetailBody').innerHTML=`<dl class="row"><dt class="col-sm-4">${esc(I.history_date||'Fecha')}</dt><dd class="col-sm-8">${esc(r.changed_at)}</dd><dt class="col-sm-4">${esc(I.history_company||'Empresa')}</dt><dd class="col-sm-8">${esc(r.company_name||'—')}</dd><dt class="col-sm-4">${esc(I.history_module||'Módulo')}</dt><dd class="col-sm-8">${esc(r.module)}</dd><dt class="col-sm-4">${esc(I.history_action||'Acción')}</dt><dd class="col-sm-8">${esc(actionLabel(r.action))}</dd><dt class="col-sm-4">${esc(I.history_record||'Registro')}</dt><dd class="col-sm-8">${esc(record)} <span class="text-muted">(${esc(r.table_name)} #${esc(r.record_id)})</span></dd><dt class="col-sm-4">${esc(I.history_field||'Campo')}</dt><dd class="col-sm-8"><code>${esc(r.field_name)}</code></dd><dt class="col-sm-4">${esc(I.history_user||'Usuario')}</dt><dd class="col-sm-8">${esc(r.changed_by)}</dd></dl><h3 class="h6">${esc(I.history_before||'Antes')}</h3><div class="history-value">${esc(text(r.old_value))}</div><h3 class="h6 mt-3">${esc(I.history_after||'Después')}</h3><div class="history-value">${esc(text(r.new_value))}</div><div class="small text-muted mt-3">request_id: ${esc(r.request_id)}</div>`;bootstrap.Modal.getOrCreateInstance($('historyDetailModal')).show()}
 async function load(){clearAlert();$('historyStatus').className='alert alert-info';$('historyStatus').textContent=I.history_loading||'Cargando...';try{render(await json(`historial-listar.php?${query()}`))}catch(e){$('historyStatus').className='alert alert-danger';$('historyStatus').textContent=e.message;alertMsg(e.message)}}
 $('applyFilters').addEventListener('click',()=>{page=1;load()});$('clearFilters').addEventListener('click',()=>{for(const id of ['moduleSelect','actionSelect','actorSelect','dateFrom','dateTo','searchInput'])$(id).value='';if(isGlobal)$('companySelect').value='';page=1;load()});$('prevPage').addEventListener('click',()=>{if(page>1){page--;load()}});$('nextPage').addEventListener('click',()=>{if(page<pages){page++;load()}});document.addEventListener('click',e=>{const b=e.target.closest('.detail-btn');if(b)showDetail(b.dataset.i)});$('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){page=1;load()}});
 loadCompanies().then(load);
});
