/** Safety Control Tower - Programas y seguimiento mensual (Etapa 3). */
document.addEventListener('DOMContentLoaded',()=>{
  const shell=document.querySelector('.program-shell[data-csrf-token]'); if(!shell)return;
  const csrf=shell.dataset.csrfToken||'', isGlobal=shell.dataset.isGlobalAdmin==='1';
  const canCreate=shell.dataset.canCreate==='1',canEdit=shell.dataset.canEdit==='1',canState=shell.dataset.canState==='1',canTracking=shell.dataset.canTracking==='1';
  const i18n=JSON.parse(document.getElementById('programsI18n')?.textContent||'{}');
  const company=document.getElementById('companySelect'),statusFilter=document.getElementById('statusFilter'),stateFilter=document.getElementById('stateFilter'),projectFilter=document.getElementById('projectFilter'),searchFilter=document.getElementById('searchFilter');
  const list=document.getElementById('programsList'),statusBox=document.getElementById('programsStatus'),alertBox=document.getElementById('programsAlert');
  const detail=document.getElementById('detailPanel'),trackingBody=document.getElementById('trackingBody');
  const programForm=document.getElementById('programForm'),programId=document.getElementById('programId'),programName=document.getElementById('programName'),programProject=document.getElementById('programProject'),programDescription=document.getElementById('programDescription'),programResponsible=document.getElementById('programResponsible'),programStart=document.getElementById('programStart'),programEnd=document.getElementById('programEnd'),programStatus=document.getElementById('programStatus'),programCancel=document.getElementById('programCancelBtn'),programFormTitle=document.getElementById('programFormTitle');
  const trackingForm=document.getElementById('trackingForm'),trackingProgramId=document.getElementById('trackingProgramId'),trackingMonth=document.getElementById('trackingMonth'),trackingTarget=document.getElementById('trackingTarget'),trackingProgress=document.getElementById('trackingProgress'),trackingComments=document.getElementById('trackingComments'),trackingCancel=document.getElementById('trackingCancelBtn');
  let catalogs={projects:[],users:[]}, currentProgram=null,currentTracking=[];

  const api=async(url,options={})=>{const r=await fetch(url,{credentials:'same-origin',...options});let j=null;try{j=await r.json()}catch{}if(!r.ok||!j?.success)throw new Error(j?.message||i18n.programs_error||'Error');return j.data;};
  const showAlert=(msg,type='danger')=>{alertBox.className=`alert alert-${type}`;alertBox.textContent=msg;alertBox.classList.remove('d-none');window.scrollTo({top:0,behavior:'smooth'});};
  const hideAlert=()=>alertBox.classList.add('d-none');
  const tStatus=s=>i18n[`programs_status_${s}`]||s;
  const pct=v=>v===null||v===undefined||v===''?'—':`${Number(v).toFixed(Number(v)%1?1:0)}%`;
  const displayUser=u=>{const n=`${u.name||''} ${u.lastname||''}`.trim();return n?`${n} · ${u.id_users}`:u.id_users};
  const companyId=()=>isGlobal?Number(company?.value||0):null;
  const qs=()=>{const p=new URLSearchParams();if(isGlobal&&company?.value)p.set('id_company',company.value);if(statusFilter.value)p.set('status',statusFilter.value);if(stateFilter.value!=='')p.set('state',stateFilter.value);if(projectFilter.value)p.set('id_project',projectFilter.value);if(searchFilter.value.trim())p.set('search',searchFilter.value.trim());return p.toString();};
  const resetProgramForm=()=>{if(!programForm)return;programForm.reset();programId.value='';programStatus.value='planificado';[...programStatus.options].forEach(o=>o.disabled=!['planificado','en_curso'].includes(o.value));programCancel.classList.add('d-none');programFormTitle.textContent=i18n.programs_new||'Nuevo programa';if(!canCreate)programForm.closest('section')?.classList.add('d-none');};
  const resetTrackingForm=()=>{if(!trackingForm)return;trackingForm.reset();trackingProgramId.value=currentProgram?.id_program||'';trackingCancel.classList.add('d-none');};

  const fillSelect=(select,rows,valueKey,labelFn,emptyLabel)=>{if(!select)return;select.innerHTML='';const e=document.createElement('option');e.value='';e.textContent=emptyLabel;select.appendChild(e);for(const r of rows){const o=document.createElement('option');o.value=String(r[valueKey]);o.textContent=labelFn(r);if(Number(r.state)===0)o.textContent+=` · ${i18n.programs_inactive||'Inactivo'}`;select.appendChild(o)}};

  const loadCompanies=async()=>{if(!isGlobal)return;const rows=await api('empresas-disponibles.php');for(const c of rows){const o=document.createElement('option');o.value=c.id_company;o.textContent=c.razon_social;company.appendChild(o)}};
  const loadCatalogs=async()=>{if(isGlobal&&!company.value){catalogs={projects:[],users:[]};fillSelect(projectFilter,[],'id_project',x=>x.name,i18n.programs_all_projects||'Todos los proyectos');fillSelect(programProject,[],'id_project',x=>x.name,i18n.programs_no_project||'Sin proyecto');fillSelect(programResponsible,[],'id_users',displayUser,i18n.programs_select_responsible||'Selecciona responsable');return;}const q=isGlobal?`?id_company=${encodeURIComponent(company.value)}`:'';catalogs=await api(`catalogos-empresa.php${q}`);fillSelect(projectFilter,catalogs.projects,'id_project',x=>x.name,i18n.programs_all_projects||'Todos los proyectos');fillSelect(programProject,catalogs.projects,'id_project',x=>x.name,i18n.programs_no_project||'Sin proyecto');fillSelect(programResponsible,catalogs.users.filter(u=>Number(u.state)===1),'id_users',displayUser,i18n.programs_select_responsible||'Selecciona responsable');};

  const updateKpis=s=>{document.getElementById('kpiTotal').textContent=s.total??0;document.getElementById('kpiActive').textContent=s.active??0;document.getElementById('kpiAverage').textContent=`${Number(s.average_progress||0).toFixed(1)}%`;document.getElementById('kpiCompleted').textContent=s.completed??0;document.getElementById('kpiBehind').textContent=s.behind_target??0;};
  const addMeta=(parent,icon,text)=>{const span=document.createElement('span');span.className='badge text-bg-light border fw-normal';const i=document.createElement('i');i.className=`bi ${icon} me-1`;span.append(i,document.createTextNode(text));parent.appendChild(span)};
  const renderPrograms=rows=>{list.innerHTML='';if(!rows.length){statusBox.className='alert alert-light border';statusBox.textContent=i18n.programs_empty||'Sin programas.';statusBox.classList.remove('d-none');return;}statusBox.classList.add('d-none');for(const p of rows){const card=document.createElement('article');card.className=`program-card${Number(p.state)===0?' inactive':''}`;const top=document.createElement('div');top.className='program-card-top';const left=document.createElement('div');left.className='flex-grow-1';const h=document.createElement('h3');h.className='h6 mb-2';h.textContent=p.name;const meta=document.createElement('div');meta.className='program-meta mb-2';addMeta(meta,'bi-activity',tStatus(p.status));addMeta(meta,'bi-person',p.responsible_name?.trim()||p.responsible_user||'—');if(p.project_name)addMeta(meta,'bi-diagram-3',p.project_name);addMeta(meta,'bi-calendar3',`${p.start_date||'—'} → ${p.end_date||'∞'}`);left.append(h,meta);if(p.description){const d=document.createElement('p');d.className='small-muted mb-2';d.textContent=p.description;left.appendChild(d)}const progress=document.createElement('div');progress.className='progress mb-1';const bar=document.createElement('div');bar.className='progress-bar';bar.style.width=`${Math.max(0,Math.min(100,Number(p.latest_progress||0)))}%`;bar.setAttribute('aria-valuenow',String(Number(p.latest_progress||0)));bar.setAttribute('aria-valuemin','0');bar.setAttribute('aria-valuemax','100');progress.appendChild(bar);const pm=document.createElement('div');pm.className='small-muted';pm.textContent=p.latest_progress===null||p.latest_progress===undefined?(i18n.programs_no_tracking||'Sin seguimiento'):`${pct(p.latest_progress)} · ${p.latest_period||''}${p.latest_target!==null&&p.latest_target!==undefined?` · meta ${pct(p.latest_target)}`:''}`;left.append(progress,pm);
      const actions=document.createElement('div');actions.className='program-actions';const detailBtn=document.createElement('button');detailBtn.type='button';detailBtn.className='btn btn-outline-primary btn-sm';detailBtn.innerHTML='<i class="bi bi-eye"></i>';detailBtn.title=i18n.programs_view_detail||'Ver detalle';detailBtn.addEventListener('click',()=>loadDetail(Number(p.id_program)));actions.appendChild(detailBtn);if(canEdit){const edit=document.createElement('button');edit.type='button';edit.className='btn btn-outline-secondary btn-sm';edit.innerHTML='<i class="bi bi-pencil"></i>';edit.title=i18n.programs_edit||'Editar';edit.addEventListener('click',()=>editProgram(p));actions.appendChild(edit)}if(canState){const st=document.createElement('button');st.type='button';st.className=`btn btn-sm ${Number(p.state)===1?'btn-outline-danger':'btn-outline-success'}`;st.innerHTML=Number(p.state)===1?'<i class="bi bi-pause-circle"></i>':'<i class="bi bi-play-circle"></i>';st.title=Number(p.state)===1?(i18n.programs_deactivate||'Desactivar'):(i18n.programs_activate||'Activar');st.addEventListener('click',()=>toggleState(p));actions.appendChild(st)}top.append(left,actions);card.appendChild(top);list.appendChild(card)}};
  const loadPrograms=async()=>{hideAlert();if(isGlobal&&!company.value){list.innerHTML='';updateKpis({});statusBox.className='alert alert-info';statusBox.textContent=i18n.programs_select_company||'Selecciona una empresa.';statusBox.classList.remove('d-none');return;}statusBox.className='alert alert-info';statusBox.textContent=i18n.programs_loading||'Cargando...';statusBox.classList.remove('d-none');try{const data=await api(`programas-listar.php?${qs()}`);renderPrograms(data.programs||[]);updateKpis(data.summary||{})}catch(e){statusBox.className='alert alert-danger';statusBox.textContent=e.message}};

  const editProgram=p=>{if(!programForm)return;programForm.closest('section')?.classList.remove('d-none');[...programStatus.options].forEach(o=>o.disabled=false);programId.value=p.id_program;programName.value=p.name||'';programDescription.value=p.description||'';programProject.value=p.id_project||'';programResponsible.value=p.responsible_user||'';programStart.value=p.start_date||'';programEnd.value=p.end_date||'';programStatus.value=p.status||'planificado';programCancel.classList.remove('d-none');programFormTitle.textContent=i18n.programs_edit||'Editar programa';programForm.scrollIntoView({behavior:'smooth',block:'start'})};
  const toggleState=async p=>{const next=Number(p.state)===1?0:1;if(!confirm((i18n.programs_confirm_state||'¿Confirmas el cambio de estado?').replace('{name}',p.name)))return;try{await api('programas-cambiar-estado.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:csrf,id_program:Number(p.id_program),state:next})});showAlert(i18n.programs_state_updated||'Estado actualizado.','success');await loadPrograms();if(currentProgram?.id_program===p.id_program)await loadDetail(Number(p.id_program))}catch(e){showAlert(e.message)}};

  const renderTracking=rows=>{trackingBody.innerHTML='';if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=canTracking?7:6;td.className='text-muted';td.textContent=i18n.programs_no_tracking||'Sin seguimiento';tr.appendChild(td);trackingBody.appendChild(tr);return;}for(const r of rows){const tr=document.createElement('tr');const target=r.target_percentage===null?null:Number(r.target_percentage),progress=Number(r.progress_percentage),variance=target===null?null:progress-target;const vals=[r.period_month?.slice(0,7)||'',pct(target),pct(progress),variance===null?'—':`${variance>=0?'+':''}${variance.toFixed(1)} pp`,r.comments||'—',r.created_by||'—'];const labels=['programs_period','programs_target','programs_progress','programs_variance','programs_comments','programs_reported_by'];vals.forEach((v,i)=>{const td=document.createElement('td');td.dataset.label=document.querySelector(`label[for="${['trackingMonth','trackingTarget','trackingProgress','','trackingComments',''][i]}"]`)?.textContent||labels[i];td.textContent=v;if(i===3&&variance!==null)td.className=`variance ${variance>=0?'pos':'neg'}`;tr.appendChild(td)});if(canTracking){const td=document.createElement('td');td.dataset.label='Acciones';const b=document.createElement('button');b.type='button';b.className='btn btn-outline-secondary btn-sm';b.innerHTML='<i class="bi bi-pencil"></i>';b.title=i18n.programs_tracking_edit||'Editar seguimiento';b.addEventListener('click',()=>editTracking(r));td.appendChild(b);tr.appendChild(td)}trackingBody.appendChild(tr)}};
  const loadDetail=async id=>{try{const d=await api(`programa-detalle.php?id_program=${encodeURIComponent(id)}`);currentProgram=d.program;currentTracking=d.tracking||[];document.getElementById('detailName').textContent=currentProgram.name;document.getElementById('detailMeta').textContent=[currentProgram.company_name,currentProgram.project_name,tStatus(currentProgram.status),Number(currentProgram.state)===1?(i18n.programs_active||'Activo'):(i18n.programs_inactive||'Inactivo')].filter(Boolean).join(' · ');document.getElementById('detailDescription').textContent=currentProgram.description||'';document.getElementById('detailResponsible').textContent=currentProgram.responsible_name?.trim()||currentProgram.responsible_user||'—';document.getElementById('detailProgress').textContent=pct(currentProgram.latest_progress);document.getElementById('detailTarget').textContent=pct(currentProgram.latest_target);document.getElementById('detailTrackingCount').textContent=String(currentTracking.length);if(trackingProgramId)trackingProgramId.value=String(id);renderTracking(currentTracking);detail.classList.add('active');detail.scrollIntoView({behavior:'smooth',block:'start'});resetTrackingForm();if(trackingProgramId)trackingProgramId.value=String(id)}catch(e){showAlert(e.message)}};
  const editTracking=r=>{if(!trackingForm)return;trackingProgramId.value=currentProgram.id_program;trackingMonth.value=(r.period_month||'').slice(0,7);trackingTarget.value=r.target_percentage??'';trackingProgress.value=r.progress_percentage??'';trackingComments.value=r.comments??'';trackingCancel.classList.remove('d-none');trackingForm.scrollIntoView({behavior:'smooth',block:'center'})};

  if(programForm)programForm.addEventListener('submit',async e=>{e.preventDefault();hideAlert();if(isGlobal&&!company.value)return showAlert(i18n.programs_select_company||'Selecciona una empresa.');const payload={csrf_token:csrf,id_company:isGlobal?Number(company.value):undefined,id_program:programId.value?Number(programId.value):undefined,name:programName.value.trim(),description:programDescription.value.trim(),id_project:programProject.value?Number(programProject.value):null,responsible_user:programResponsible.value,start_date:programStart.value,end_date:programEnd.value,status:programStatus.value};const edit=Boolean(programId.value);try{await api(edit?'programas-editar.php':'programas-crear.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});showAlert(edit?(i18n.programs_updated||'Programa actualizado.'):(i18n.programs_saved||'Programa creado.'),'success');resetProgramForm();await loadPrograms()}catch(err){showAlert(err.message)}});
  programCancel?.addEventListener('click',resetProgramForm);
  if(trackingForm)trackingForm.addEventListener('submit',async e=>{e.preventDefault();hideAlert();try{await api('tracking-guardar.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:csrf,id_program:Number(trackingProgramId.value),period_month:trackingMonth.value,target_percentage:trackingTarget.value,progress_percentage:trackingProgress.value,comments:trackingComments.value.trim()})});showAlert(i18n.programs_tracking_saved||'Seguimiento guardado.','success');resetTrackingForm();await loadDetail(Number(trackingProgramId.value));await loadPrograms()}catch(err){showAlert(err.message)}});
  trackingCancel?.addEventListener('click',resetTrackingForm);
  document.getElementById('closeDetailBtn')?.addEventListener('click',()=>detail.classList.remove('active'));
  document.getElementById('reloadBtn')?.addEventListener('click',loadPrograms);
  [statusFilter,stateFilter,projectFilter].forEach(x=>x?.addEventListener('change',loadPrograms));
  let timer=null;searchFilter?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(loadPrograms,300)});
  company?.addEventListener('change',async()=>{resetProgramForm();detail.classList.remove('active');try{await loadCatalogs();await loadPrograms()}catch(e){showAlert(e.message)}});
  (async()=>{try{await loadCompanies();if(!isGlobal)await loadCatalogs();await loadPrograms()}catch(e){showAlert(e.message)}})();
});
